CREATE TABLE IF NOT EXISTS "avis" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "note" INTEGER NOT NULL,
  "commentaire" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "avis_pkey" PRIMARY KEY ("id")
);

DO $$ BEGIN
  ALTER TABLE "avis" ADD CONSTRAINT "avis_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
