// Bibliothèque de recettes COAI (19/08/2026, demande Anthony — "des recettes
// avec de belles images", façon MyFitnessCoach). Contenu éditorial rédigé
// ici, distinct du plan nutrition généré par l'IA (NutritionView) : ces
// recettes sont une bibliothèque commune consultable par tous les abonnés,
// pas une personnalisation par profil. Macros données à titre indicatif
// (estimation pour une portion), jamais présentées comme un calcul exact —
// même principe de prudence que le reste du contenu nutrition de COAI.
import { RECETTES_EXTENSION } from "./recettes-extension";
import { RECETTES_V6 } from "./recettes-v6";

export type ObjectifRecette = "PERTE_DE_POIDS" | "PRISE_DE_MASSE" | "EQUILIBRE";
export type TypeRepas = "PETIT_DEJEUNER" | "DEJEUNER" | "DINER" | "COLLATION";
export type RegimeRecette = "VEGETARIEN" | "SANS_GLUTEN" | "ANTI_INFLAMMATOIRE";
export type VarianteRecette = "LEAN" | "RESET_TRX" | "HYBRID" | "MASS";

export type Recette = {
  slug: string;
  nom: string;
  description: string;
  photoQuery: string;
  photoLocale?: string;
  typeRepas: TypeRepas;
  objectifs: ObjectifRecette[];
  regimes: RegimeRecette[];
  tempsMinutes: number;
  macros: { calories: number; proteines: number; glucides: number; lipides: number };
  ingredients: string[];
  etapes: string[];
  portion?: string;
  allergenes?: string[];
  conservation?: string;
  variantes?: Partial<Record<VarianteRecette, string>>;
};

export const RECETTES: Recette[] = [
  {
    slug: "poulet-boulgour-courgettes",
    nom: "Poulet, boulgour et courgettes rôties",
    description: "Un classique protéiné et coloré, facile à préparer en avance pour plusieurs déjeuners.",
    photoQuery: "grilled chicken bulgur roasted zucchini",
    photoLocale: "/repas/plat-poulet-boulgour-courgettes.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: [],
    tempsMinutes: 30,
    macros: { calories: 520, proteines: 42, glucides: 48, lipides: 16 },
    portion: "1 personne",
    allergenes: ["Gluten"],
    conservation: "3 jours au réfrigérateur dans une boîte hermétique ; congélation possible.",
    variantes: {
      LEAN: "Passe à 60 g de boulgour et augmente les courgettes.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 30 g de boulgour sec les jours intenses.",
      MASS: "Ajoute 40 g de boulgour sec et une cuillère d'huile d'olive.",
    },
    ingredients: [
      "150 g de blanc de poulet",
      "80 g de boulgour (poids sec)",
      "2 petites courgettes",
      "1/2 oignon rouge",
      "1 c. à soupe d'huile d'olive",
      "Cumin, paprika, sel, poivre",
    ],
    etapes: [
      "Cuire le boulgour selon les indications du paquet, puis l'égoutter.",
      "Couper les courgettes et l'oignon, puis les rôtir au four 20 min à 200°C avec l'huile et les épices.",
      "Griller le poulet à la poêle 5-6 minutes de chaque côté, épicer avec cumin et paprika.",
      "Assembler le plat : boulgour, courgettes rôties et poulet tranché.",
    ],
  },
  {
    slug: "porridge-fruits-rouges",
    nom: "Porridge avoine, fruits rouges et amandes",
    description: "Un petit-déjeuner qui tient au corps, riche en fibres et à index glycémique modéré.",
    photoQuery: "oatmeal porridge berries almonds breakfast",
    photoLocale: "/repas/petit-dejeuner-avoine-fruits-rouges.jpg",
    typeRepas: "PETIT_DEJEUNER",
    objectifs: ["EQUILIBRE", "PERTE_DE_POIDS"],
    regimes: ["VEGETARIEN"],
    tempsMinutes: 10,
    macros: { calories: 340, proteines: 12, glucides: 48, lipides: 10 },
    portion: "1 bol",
    allergenes: ["Gluten", "Fruits à coque", "Lait selon la boisson"],
    conservation: "Préparation possible la veille ; 24 h au réfrigérateur dans un récipient fermé.",
    variantes: {
      LEAN: "40 g d'avoine, sans miel, avec 150 g de skyr.",
      RESET_TRX: "Version de base, avec un yaourt si la faim est importante.",
      HYBRID: "Ajoute une banane et 20 g d'avoine avant une séance longue.",
      MASS: "Ajoute 30 g d'avoine et une cuillère de purée d'amande.",
    },
    ingredients: [
      "50 g de flocons d'avoine",
      "200 ml de lait (ou boisson végétale)",
      "80 g de fruits rouges (frais ou surgelés)",
      "1 c. à soupe d'amandes effilées",
      "1 c. à café de miel (optionnel)",
    ],
    etapes: [
      "Faire chauffer le lait, ajouter les flocons d'avoine, cuire 5 minutes à feu doux en remuant.",
      "Verser dans un bol, ajouter les fruits rouges et les amandes.",
      "Sucrer légèrement au miel si besoin.",
    ],
  },
  {
    slug: "saumon-quinoa-brocolis",
    nom: "Saumon, quinoa et brocolis",
    description: "Riche en omégas-3, protéines et fibres, avec une portion de glucides facile à ajuster.",
    photoQuery: "salmon quinoa broccoli healthy plate",
    photoLocale: "/repas/plat-saumon-quinoa-brocolis.jpg",
    typeRepas: "DINER",
    objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"],
    regimes: ["SANS_GLUTEN", "ANTI_INFLAMMATOIRE"],
    tempsMinutes: 25,
    macros: { calories: 540, proteines: 39, glucides: 48, lipides: 21 },
    portion: "1 personne",
    allergenes: ["Poisson"],
    conservation: "2 jours au réfrigérateur ; réchauffer doucement ou consommer froid.",
    variantes: {
      LEAN: "50 g de quinoa sec et 250 g de brocolis.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 30 g de quinoa sec les jours de volume élevé.",
      MASS: "Ajoute du quinoa et un demi-avocat.",
    },
    ingredients: [
      "150 g de pavé de saumon",
      "180 g de brocolis",
      "70 g de quinoa (poids sec)",
      "1 c. à soupe d'huile d'olive",
      "Jus de citron, aneth",
    ],
    etapes: [
      "Rincer le quinoa et le cuire dans deux fois son volume d'eau, environ 15 minutes.",
      "Cuire les brocolis à la vapeur 8 à 10 minutes pour qu'ils restent légèrement fermes.",
      "Cuire le saumon à la poêle ou au four, 12-15 minutes selon l'épaisseur.",
      "Arroser d'huile d'olive, de jus de citron et d'aneth avant de servir.",
    ],
  },
  {
    slug: "curry-pois-chiches-riz",
    nom: "Curry de pois chiches et riz",
    description: "Un plat végétal réconfortant, riche en fibres, simple à préparer en grande quantité.",
    photoQuery: "chickpea curry rice healthy bowl",
    photoLocale: "/repas/plat-curry-pois-chiches-riz.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["EQUILIBRE", "PERTE_DE_POIDS"],
    regimes: ["VEGETARIEN", "SANS_GLUTEN"],
    tempsMinutes: 25,
    macros: { calories: 510, proteines: 17, glucides: 77, lipides: 14 },
    portion: "1 personne",
    allergenes: [],
    conservation: "3 jours au réfrigérateur ; le curry se congèle jusqu'à 2 mois.",
    variantes: {
      LEAN: "50 g de riz sec et du lait de coco léger.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 30 g de riz sec avant une grosse séance.",
      MASS: "Ajoute riz, noix de cajou et une portion de yaourt végétal.",
    },
    ingredients: [
      "150 g de pois chiches cuits",
      "70 g de riz basmati (poids sec)",
      "150 g de tomates concassées",
      "80 ml de lait de coco léger",
      "1/2 oignon",
      "Curry, curcuma, coriandre",
    ],
    etapes: [
      "Cuire le riz selon les indications du paquet.",
      "Faire revenir l'oignon et les épices 2 minutes, puis ajouter tomates et lait de coco.",
      "Ajouter les pois chiches et laisser mijoter 12 à 15 minutes.",
      "Servir le curry avec le riz et la coriandre.",
    ],
  },
  {
    slug: "omelette-legumes",
    nom: "Omelette aux légumes de saison",
    description: "Rapide, économique et riche en protéines — un grand classique qui ne déçoit jamais.",
    photoQuery: "vegetable omelette healthy breakfast plate",
    photoLocale: "/repas/petit-dejeuner-omelette-epinards.jpg",
    typeRepas: "PETIT_DEJEUNER",
    objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["VEGETARIEN", "SANS_GLUTEN"],
    tempsMinutes: 12,
    macros: { calories: 320, proteines: 22, glucides: 8, lipides: 22 },
    portion: "1 personne",
    allergenes: ["Œufs"],
    conservation: "À consommer immédiatement ; les légumes peuvent être préparés 2 jours à l'avance.",
    variantes: {
      LEAN: "2 œufs + 120 g de blancs d'œufs et davantage de légumes.",
      RESET_TRX: "Version de base avec une tranche de pain complet si besoin.",
      HYBRID: "Ajoute deux tranches de pain et un fruit.",
      MASS: "Ajoute fromage, pain complet et avocat.",
    },
    ingredients: [
      "3 œufs",
      "1/2 poivron",
      "Quelques champignons",
      "1 poignée d'épinards",
      "1 c. à café d'huile d'olive",
    ],
    etapes: [
      "Faire revenir les légumes coupés en petits morceaux dans l'huile d'olive.",
      "Battre les œufs, verser sur les légumes dans la poêle chaude.",
      "Cuire 3-4 minutes à feu moyen, replier et servir.",
    ],
  },
  {
    slug: "tofu-sarrasin-legumes",
    nom: "Tofu, sarrasin et légumes croquants",
    description: "Un plat végétal complet, riche en protéines et naturellement sans gluten.",
    photoQuery: "tofu buckwheat vegetables healthy bowl",
    photoLocale: "/repas/plat-tofu-sarrasin-legumes.jpg",
    typeRepas: "DINER",
    objectifs: ["EQUILIBRE", "PERTE_DE_POIDS", "PRISE_DE_MASSE"],
    regimes: ["VEGETARIEN", "SANS_GLUTEN", "ANTI_INFLAMMATOIRE"],
    tempsMinutes: 30,
    macros: { calories: 480, proteines: 25, glucides: 52, lipides: 18 },
    portion: "1 personne",
    allergenes: ["Soja"],
    conservation: "3 jours au réfrigérateur ; conserver la sauce à part pour garder les légumes croquants.",
    variantes: {
      LEAN: "50 g de sarrasin sec et davantage de légumes.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 30 g de sarrasin sec les jours de circuit long.",
      MASS: "Ajoute sarrasin, avocat et graines de sésame.",
    },
    ingredients: [
      "180 g de tofu ferme",
      "70 g de sarrasin (poids sec)",
      "1 carotte",
      "1/2 brocoli",
      "1 c. à soupe de sauce tamari",
    ],
    etapes: [
      "Cuire le sarrasin selon les indications, puis l'égoutter.",
      "Presser le tofu, le couper en cubes et le poêler jusqu'à ce qu'il soit doré.",
      "Sauter les légumes 6 à 8 minutes, ajouter le tamari, puis assembler avec le sarrasin.",
    ],
  },
  {
    slug: "amandes-noix-cajou",
    nom: "Mélange amandes et noix de cajou",
    description: "Une collation nomade à portionner à l'avance pour éviter de manger directement dans le paquet.",
    photoQuery: "almonds cashews healthy snack portion",
    photoLocale: "/repas/collation-amandes-cajou.jpg",
    typeRepas: "COLLATION",
    objectifs: ["PRISE_DE_MASSE", "EQUILIBRE", "PERTE_DE_POIDS"],
    regimes: ["VEGETARIEN", "SANS_GLUTEN", "ANTI_INFLAMMATOIRE"],
    tempsMinutes: 2,
    macros: { calories: 190, proteines: 6, glucides: 8, lipides: 15 },
    portion: "30 g",
    allergenes: ["Fruits à coque"],
    conservation: "Jusqu'à 1 mois dans un contenant hermétique, au sec et à l'abri de la chaleur.",
    variantes: {
      LEAN: "Une portion pesée de 20 g, accompagnée d'un fruit.",
      RESET_TRX: "Une portion de 30 g.",
      HYBRID: "Ajoute un fruit et un yaourt pour une collation complète.",
      MASS: "Passe à 45 g et ajoute des fruits secs.",
    },
    ingredients: [
      "15 g d'amandes non salées",
      "15 g de noix de cajou non salées",
      "Cannelle ou paprika fumé (optionnel)",
    ],
    etapes: ["Peser une portion de 30 g.", "Mélanger avec l'épice choisie et conserver dans un petit contenant fermé."],
  },
  {
    slug: "poulet-riz-haricots",
    nom: "Poulet, riz et haricots verts",
    description: "Le meal prep sportif par excellence : simple, digeste et facile à ajuster selon la dépense.",
    photoQuery: "chicken rice green beans meal prep",
    photoLocale: "/repas/plat-poulet-riz-haricots.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"],
    regimes: ["SANS_GLUTEN"],
    tempsMinutes: 30,
    macros: { calories: 520, proteines: 45, glucides: 58, lipides: 12 },
    portion: "1 personne",
    allergenes: [],
    conservation: "3 jours au réfrigérateur ; refroidir le riz rapidement avant de fermer les boîtes.",
    variantes: {
      LEAN: "55 g de riz sec et davantage de haricots verts.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 30 à 50 g de riz sec les jours de simulation.",
      MASS: "Ajoute riz, huile d'olive et une sauce au yaourt.",
    },
    ingredients: [
      "160 g de blanc de poulet",
      "75 g de riz (poids sec)",
      "200 g de haricots verts",
      "1 c. à soupe d'huile d'olive",
      "Paprika, ail, herbes",
    ],
    etapes: [
      "Cuire le riz et les haricots verts séparément.",
      "Assaisonner le poulet et le cuire 5 à 6 minutes par face.",
      "Répartir dans une assiette ou trois boîtes de meal prep en multipliant les quantités.",
    ],
  },
  {
    slug: "boeuf-patate-douce-salade",
    nom: "Bœuf, patate douce et salade croquante",
    description: "Une assiette dense en protéines et en fer, avec des glucides adaptés à l'entraînement.",
    photoQuery: "beef sweet potato salad healthy plate",
    photoLocale: "/repas/plat-boeuf-patate-douce-salade.jpg",
    typeRepas: "DINER",
    objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["SANS_GLUTEN"],
    tempsMinutes: 30,
    macros: { calories: 590, proteines: 43, glucides: 54, lipides: 23 },
    portion: "1 personne",
    allergenes: [],
    conservation: "2 jours au réfrigérateur ; conserver la salade séparément.",
    variantes: {
      LEAN: "Choisis du bœuf à 5 % MG, 200 g de patate douce et double la salade.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute une portion de pain ou de riz après une séance longue.",
      MASS: "Ajoute 100 g de patate douce et une cuillère d'huile.",
    },
    ingredients: [
      "170 g de bœuf maigre",
      "280 g de patate douce",
      "1 grand bol de salade et crudités",
      "1 c. à soupe d'huile d'olive",
      "Paprika, cumin, vinaigre balsamique",
    ],
    etapes: ["Couper la patate douce et la rôtir 25 minutes à 200°C avec les épices.", "Saisir le bœuf selon la cuisson souhaitée et le laisser reposer 3 minutes.", "Assaisonner la salade, trancher le bœuf et dresser."],
  },
  {
    slug: "saumon-papillote-riz-sauvage",
    nom: "Saumon en papillote et riz sauvage",
    description: "Une cuisson douce et sans complication, idéale pour préserver le moelleux du saumon.",
    photoQuery: "salmon papillote wild rice healthy dinner",
    photoLocale: "/repas/plat-saumon-papillote-riz-sauvage.jpg",
    typeRepas: "DINER",
    objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"],
    regimes: ["SANS_GLUTEN", "ANTI_INFLAMMATOIRE"],
    tempsMinutes: 30,
    macros: { calories: 560, proteines: 38, glucides: 55, lipides: 22 },
    portion: "1 personne",
    allergenes: ["Poisson"],
    conservation: "2 jours au réfrigérateur ; conserver le riz et la papillote ensemble après refroidissement.",
    variantes: {
      LEAN: "55 g de riz sec et davantage de courgette.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 30 g de riz sec les jours intenses.",
      MASS: "Ajoute riz, huile d'olive et un dessert lacté.",
    },
    ingredients: [
      "160 g de pavé de saumon",
      "75 g de riz sauvage (poids sec)",
      "1 petite courgette",
      "Quelques tomates cerises",
      "Citron, aneth, 1 c. à café d'huile d'olive",
    ],
    etapes: [
      "Cuire le riz sauvage selon les indications du paquet.",
      "Déposer saumon, courgette et tomates sur du papier cuisson, ajouter citron, aneth et huile, puis fermer la papillote.",
      "Cuire 15 à 18 minutes à 190°C et servir avec le riz.",
    ],
  },
  {
    slug: "oeufs-brouilles-avocat",
    nom: "Œufs brouillés, avocat et pain complet",
    description: "Un petit-déjeuner salé, rassasiant et ajustable selon le volume d'entraînement de la journée.",
    photoQuery: "scrambled eggs avocado wholegrain toast",
    photoLocale: "/repas/petit-dejeuner-oeufs-avocat.jpg",
    typeRepas: "PETIT_DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["VEGETARIEN"],
    tempsMinutes: 12,
    macros: { calories: 430, proteines: 23, glucides: 31, lipides: 23 },
    portion: "1 personne",
    allergenes: ["Œufs", "Gluten"],
    conservation: "À consommer immédiatement. L'avocat citronné se conserve jusqu'à 12 h au frais.",
    ingredients: ["3 œufs", "1/2 avocat", "2 tranches de pain complet", "1 c. à café d'huile d'olive", "Citron, poivre, paprika"],
    etapes: [
      "Écraser l'avocat avec un trait de citron, du poivre et du paprika.",
      "Battre les œufs, puis les cuire à feu doux dans l'huile en remuant jusqu'à une texture encore crémeuse.",
      "Griller le pain, répartir l'avocat et servir avec les œufs.",
    ],
    variantes: {
      LEAN: "2 œufs + 100 g de blancs d'œufs, une seule tranche de pain.",
      RESET_TRX: "Version de base, avec un fruit si la séance est prévue le matin.",
      HYBRID: "Ajoute une tranche de pain et une banane les jours d'intervalles.",
      MASS: "Ajoute 30 g de fromage, une tranche de pain et un fruit.",
    },
  },
  {
    slug: "fromage-blanc-miel-noix",
    nom: "Fromage blanc, miel, noix et fruits",
    description: "Une collation protéinée en cinq minutes, facile à emporter et à décliner selon l'objectif.",
    photoQuery: "fromage blanc honey walnuts fruit bowl",
    photoLocale: "/repas/petit-dejeuner-fromage-blanc-miel.jpg",
    typeRepas: "COLLATION",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["VEGETARIEN", "SANS_GLUTEN"],
    tempsMinutes: 5,
    macros: { calories: 300, proteines: 22, glucides: 29, lipides: 10 },
    portion: "1 bol",
    allergenes: ["Lait", "Fruits à coque"],
    conservation: "Jusqu'à 24 h au réfrigérateur dans un contenant fermé ; ajoute les noix au dernier moment.",
    ingredients: ["250 g de fromage blanc", "100 g de fruits de saison", "15 g de noix", "1 c. à café de miel", "Cannelle"],
    etapes: ["Verser le fromage blanc dans un bol.", "Ajouter les fruits découpés, les noix et la cannelle.", "Terminer par le miel juste avant de servir."],
    variantes: {
      LEAN: "Fromage blanc 0-3 %, retire le miel si les fruits sont bien mûrs.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 40 g de flocons d'avoine avant une séance longue.",
      MASS: "Ajoute 60 g de granola et une cuillère de purée d'amande.",
    },
  },
  {
    slug: "cabillaud-lentilles-carottes",
    nom: "Cabillaud, lentilles et carottes rôties",
    description: "Un plat complet riche en protéines, fibres et glucides à diffusion progressive.",
    photoQuery: "cod lentils roasted carrots healthy plate",
    photoLocale: "/repas/plat-cabillaud-lentilles-carottes.jpg",
    typeRepas: "DINER",
    objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"],
    regimes: ["SANS_GLUTEN", "ANTI_INFLAMMATOIRE"],
    tempsMinutes: 35,
    macros: { calories: 470, proteines: 43, glucides: 49, lipides: 11 },
    portion: "1 personne",
    allergenes: ["Poisson", "Moutarde (si utilisée)"],
    conservation: "2 jours au réfrigérateur. Réchauffer doucement le poisson pour éviter qu'il ne sèche.",
    ingredients: ["170 g de cabillaud", "160 g de lentilles cuites", "2 carottes", "1 c. à soupe d'huile d'olive", "Citron, thym, moutarde facultative"],
    etapes: [
      "Couper les carottes, les mélanger avec la moitié de l'huile et le thym, puis rôtir 25 minutes à 200°C.",
      "Déposer le cabillaud sur une plaque, assaisonner et cuire 12 à 15 minutes selon l'épaisseur.",
      "Réchauffer les lentilles, assaisonner avec citron et le reste d'huile, puis dresser.",
    ],
    variantes: {
      LEAN: "Garde 120 g de lentilles cuites et double les légumes.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 100 à 150 g de pommes de terre les jours de séance intense.",
      MASS: "Ajoute 80 g de pain complet et une cuillère d'huile d'olive.",
    },
  },
  {
    slug: "dinde-grenailles-epinards",
    nom: "Dinde, pommes grenailles et épinards",
    description: "Un repas simple de préparation sportive, digeste et facile à cuisiner en plusieurs portions.",
    photoQuery: "turkey baby potatoes spinach meal prep",
    photoLocale: "/repas/plat-dinde-grenaille-epinards.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["SANS_GLUTEN"],
    tempsMinutes: 35,
    macros: { calories: 560, proteines: 48, glucides: 58, lipides: 15 },
    portion: "1 personne",
    allergenes: [],
    conservation: "3 jours au réfrigérateur dans une boîte hermétique ; congélation possible sans les épinards.",
    ingredients: ["170 g d'escalope de dinde", "250 g de pommes grenailles", "150 g d'épinards", "1 c. à soupe d'huile d'olive", "Ail, paprika, herbes"],
    etapes: [
      "Couper les pommes de terre en deux, assaisonner et rôtir 25 à 30 minutes à 200°C.",
      "Poêler la dinde 4 à 6 minutes par face selon l'épaisseur.",
      "Faire tomber les épinards avec l'ail pendant 2 minutes et servir ensemble.",
    ],
    variantes: {
      LEAN: "180 g de pommes de terre et une cuillère à café d'huile.",
      RESET_TRX: "Version de base, portion de pommes de terre selon la faim.",
      HYBRID: "Ajoute 100 g de pommes de terre avant une grosse séance.",
      MASS: "Passe à 350 g de pommes de terre et ajoute une sauce yaourt-herbes.",
    },
  },
  {
    slug: "thon-patate-douce-asperges",
    nom: "Thon, patate douce et asperges",
    description: "Une assiette colorée, riche en protéines, pratique pour un déjeuner après l'entraînement.",
    photoQuery: "tuna sweet potato asparagus healthy plate",
    photoLocale: "/repas/plat-thon-patate-douce-asperges.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["SANS_GLUTEN", "ANTI_INFLAMMATOIRE"],
    tempsMinutes: 30,
    macros: { calories: 500, proteines: 42, glucides: 52, lipides: 14 },
    portion: "1 personne",
    allergenes: ["Poisson"],
    conservation: "2 jours au réfrigérateur. Conserver l'assaisonnement citronné à part.",
    ingredients: ["160 g de thon au naturel égoutté", "250 g de patate douce", "180 g d'asperges", "1 c. à soupe d'huile d'olive", "Citron, persil, poivre"],
    etapes: [
      "Couper la patate douce en cubes et la rôtir 25 minutes à 200°C avec la moitié de l'huile.",
      "Cuire les asperges à la vapeur ou à la poêle 6 à 8 minutes.",
      "Égoutter le thon, l'assaisonner avec citron et persil, puis assembler l'assiette.",
    ],
    variantes: {
      LEAN: "180 g de patate douce, davantage d'asperges et une cuillère à café d'huile.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 100 g de patate douce ou un fruit en dessert.",
      MASS: "Ajoute 100 g de riz cuit et un demi-avocat.",
    },
  },
  {
    slug: "pancakes-proteines-fruits-rouges",
    nom: "Pancakes protéinés, skyr et fruits rouges",
    description: "Des pancakes moelleux à l'avoine, rassasiants et faciles à ajuster selon l'objectif du jour.",
    photoQuery: "protein pancakes skyr red berries",
    photoLocale: "/repas/petit-dejeuner-pancakes-proteines-fruits-rouges.jpg",
    typeRepas: "PETIT_DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["VEGETARIEN"],
    tempsMinutes: 18,
    macros: { calories: 410, proteines: 29, glucides: 53, lipides: 9 },
    portion: "4 petits pancakes",
    allergenes: ["Œufs", "Lait", "Gluten possible dans l'avoine"],
    conservation: "2 jours au réfrigérateur ou 1 mois au congélateur, séparés par du papier cuisson.",
    variantes: {
      LEAN: "40 g d'avoine, 100 g de skyr et davantage de fruits rouges.",
      RESET_TRX: "Version de base, sans sirop ajouté.",
      HYBRID: "Ajoute une banane entière et 20 g d'avoine avant une séance longue.",
      MASS: "Ajoute une cuillère de purée d'amande et 30 g de granola.",
    },
    ingredients: [
      "50 g de flocons d'avoine mixés",
      "1 petite banane",
      "1 œuf",
      "100 g de skyr",
      "80 g de fruits rouges",
      "1/2 c. à café de levure",
    ],
    etapes: [
      "Mixer l'avoine, la banane, l'œuf, la moitié du skyr et la levure.",
      "Cuire quatre petits pancakes 2 minutes par face dans une poêle antiadhésive.",
      "Servir avec le reste du skyr et les fruits rouges.",
    ],
  },
  {
    slug: "overnight-oats-cacao-poire",
    nom: "Overnight oats cacao, poire et noisettes",
    description: "Un petit-déjeuner préparé la veille, crémeux et riche en fibres avec une note chocolatée.",
    photoQuery: "cocoa overnight oats pear hazelnuts jar",
    photoLocale: "/repas/petit-dejeuner-overnight-oats-cacao-poire.jpg",
    typeRepas: "PETIT_DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["VEGETARIEN"],
    tempsMinutes: 8,
    macros: { calories: 430, proteines: 23, glucides: 58, lipides: 13 },
    portion: "1 bocal",
    allergenes: ["Lait", "Fruits à coque", "Gluten possible dans l'avoine"],
    conservation: "Jusqu'à 2 jours au réfrigérateur dans un bocal fermé.",
    variantes: {
      LEAN: "40 g d'avoine, lait écrémé et 10 g de noisettes.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 20 g d'avoine et une cuillère de miel avant une grosse séance.",
      MASS: "Ajoute 20 g de noisettes et une cuillère de purée de noisette.",
    },
    ingredients: [
      "50 g de flocons d'avoine",
      "150 g de skyr",
      "120 ml de lait",
      "1 c. à café de cacao non sucré",
      "1/2 poire en dés",
      "15 g de noisettes concassées",
    ],
    etapes: [
      "Mélanger l'avoine, le skyr, le lait et le cacao dans un bocal.",
      "Fermer et laisser reposer au réfrigérateur pendant au moins 6 heures.",
      "Ajouter la poire et les noisettes juste avant de manger.",
    ],
  },
  {
    slug: "bowl-crevettes-mangue-riz",
    nom: "Bowl crevettes, mangue et riz",
    description: "Un bowl frais et complet qui associe protéines maigres, glucides et légumes croquants.",
    photoQuery: "shrimp mango rice edamame cucumber bowl",
    photoLocale: "/repas/plat-bowl-crevettes-mangue-riz.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["SANS_GLUTEN"],
    tempsMinutes: 25,
    macros: { calories: 550, proteines: 39, glucides: 76, lipides: 10 },
    portion: "1 bowl",
    allergenes: ["Crustacés", "Soja"],
    conservation: "24 heures au réfrigérateur ; conserver la mangue et la sauce séparément.",
    variantes: {
      LEAN: "55 g de riz sec, 180 g de crevettes et davantage de concombre.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 30 g de riz sec les jours de simulation.",
      MASS: "Ajoute riz, edamame et un demi-avocat.",
    },
    ingredients: [
      "170 g de crevettes décortiquées",
      "75 g de riz, poids sec",
      "100 g de mangue en cubes",
      "100 g de concombre",
      "80 g d'edamame",
      "Citron vert et sauce tamari",
    ],
    etapes: [
      "Cuire le riz puis le laisser tiédir.",
      "Saisir les crevettes 2 à 3 minutes par face avec un peu de citron vert.",
      "Assembler le riz, les crevettes, la mangue, le concombre et l'edamame, puis assaisonner.",
    ],
  },
  {
    slug: "chili-dinde-haricots-rouges",
    nom: "Chili de dinde et haricots rouges",
    description: "Un plat chaud riche en protéines et en fibres, parfait pour le batch cooking.",
    photoQuery: "lean turkey chili kidney beans tomato corn",
    photoLocale: "/repas/plat-chili-dinde-haricots-rouges.jpg",
    typeRepas: "DINER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["SANS_GLUTEN"],
    tempsMinutes: 40,
    macros: { calories: 510, proteines: 47, glucides: 53, lipides: 13 },
    portion: "1 grand bol",
    allergenes: ["Lait si yaourt ajouté"],
    conservation: "3 jours au réfrigérateur ou 2 mois au congélateur.",
    variantes: {
      LEAN: "Dinde à 5 % MG, plus de tomate et 100 g de haricots cuits.",
      RESET_TRX: "Version de base avec une cuillère de yaourt.",
      HYBRID: "Ajoute une portion de riz les jours intenses.",
      MASS: "Ajoute riz, fromage râpé et davantage de haricots rouges.",
    },
    ingredients: [
      "170 g de dinde hachée maigre",
      "140 g de haricots rouges cuits",
      "200 g de tomates concassées",
      "50 g de maïs",
      "1/2 oignon",
      "Cumin, paprika fumé, piment doux",
    ],
    etapes: [
      "Faire revenir l'oignon puis la dinde jusqu'à légère coloration.",
      "Ajouter les épices, les tomates, les haricots et le maïs.",
      "Laisser mijoter 20 à 25 minutes à feu doux et rectifier l'assaisonnement.",
    ],
  },
  {
    slug: "pates-lentilles-pesto-courgettes",
    nom: "Pâtes de lentilles, pesto et courgettes",
    description: "Une option végétarienne riche en protéines, avec des légumes grillés et un pesto maîtrisé.",
    photoQuery: "red lentil pasta pesto zucchini cherry tomatoes",
    photoLocale: "/repas/plat-pates-lentilles-pesto-courgettes.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["VEGETARIEN", "SANS_GLUTEN"],
    tempsMinutes: 22,
    macros: { calories: 520, proteines: 27, glucides: 62, lipides: 18 },
    portion: "1 personne",
    allergenes: ["Lait", "Fruits à coque"],
    conservation: "2 jours au réfrigérateur ; ajouter un trait d'eau au réchauffage.",
    variantes: {
      LEAN: "70 g de pâtes sèches, 10 g de pesto et davantage de courgettes.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 25 g de pâtes sèches avant une séance longue.",
      MASS: "Ajoute pesto, parmesan et pignons de pin.",
    },
    ingredients: [
      "85 g de pâtes de lentilles corail, poids sec",
      "1 petite courgette en rubans",
      "120 g de tomates cerises",
      "20 g de pesto de basilic",
      "Basilic frais et poivre",
    ],
    etapes: [
      "Cuire les pâtes al dente selon les indications du paquet.",
      "Griller les rubans de courgette et les tomates 6 à 8 minutes.",
      "Mélanger les pâtes avec le pesto et deux cuillères d'eau de cuisson, puis ajouter les légumes.",
    ],
  },
  {
    slug: "wok-boeuf-nouilles-riz",
    nom: "Wok de bœuf, nouilles de riz et brocolis",
    description: "Un plat rapide et complet avec bœuf maigre, légumes croquants et sauce légère.",
    photoQuery: "lean beef rice noodle broccoli red pepper wok",
    photoLocale: "/repas/plat-wok-boeuf-nouilles-riz.jpg",
    typeRepas: "DINER",
    objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["SANS_GLUTEN"],
    tempsMinutes: 25,
    macros: { calories: 610, proteines: 43, glucides: 76, lipides: 16 },
    portion: "1 personne",
    allergenes: ["Soja", "Sésame"],
    conservation: "2 jours au réfrigérateur ; réchauffer rapidement au wok pour préserver la texture.",
    variantes: {
      LEAN: "60 g de nouilles sèches, 180 g de bœuf maigre et davantage de brocolis.",
      RESET_TRX: "Version de base avec une sauce peu salée.",
      HYBRID: "Ajoute 30 g de nouilles sèches après les intervalles.",
      MASS: "Ajoute nouilles, huile de sésame et noix de cajou.",
    },
    ingredients: [
      "170 g de bœuf maigre en lamelles",
      "80 g de nouilles de riz, poids sec",
      "180 g de brocolis",
      "1/2 poivron rouge",
      "1 c. à soupe de sauce tamari",
      "1 c. à café de graines de sésame",
    ],
    etapes: [
      "Réhydrater ou cuire les nouilles selon le paquet.",
      "Saisir le bœuf 2 minutes à feu vif, puis le réserver.",
      "Sauter brocolis et poivron, remettre le bœuf, ajouter nouilles et tamari puis mélanger 1 minute.",
    ],
  },
  {
    slug: "shakshuka-pois-chiches",
    nom: "Shakshuka aux pois chiches",
    description: "Deux œufs cuits dans une sauce tomate-poivron, enrichie de pois chiches pour les fibres.",
    photoQuery: "shakshuka eggs chickpeas tomato red pepper",
    photoLocale: "/repas/plat-shakshuka-pois-chiches.jpg",
    typeRepas: "DINER",
    objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"],
    regimes: ["VEGETARIEN", "SANS_GLUTEN"],
    tempsMinutes: 30,
    macros: { calories: 440, proteines: 25, glucides: 43, lipides: 19 },
    portion: "1 poêlon",
    allergenes: ["Œufs"],
    conservation: "La sauce se conserve 3 jours ; ajouter et cuire les œufs au moment de servir.",
    variantes: {
      LEAN: "100 g de pois chiches et davantage de poivron.",
      RESET_TRX: "Version de base avec une tranche de pain si besoin.",
      HYBRID: "Ajoute pain complet ou riz avant une séance longue.",
      MASS: "Ajoute un troisième œuf, du pain complet et de la feta.",
    },
    ingredients: [
      "2 œufs",
      "120 g de pois chiches cuits",
      "220 g de tomates concassées",
      "1/2 poivron rouge",
      "1/2 oignon",
      "Cumin, paprika et persil",
    ],
    etapes: [
      "Faire revenir l'oignon et le poivron 6 minutes avec les épices.",
      "Ajouter tomates et pois chiches, puis mijoter 10 minutes.",
      "Creuser deux espaces, casser les œufs, couvrir et cuire jusqu'à ce que les blancs soient pris.",
    ],
  },
  {
    slug: "bowl-mediterraneen-quinoa",
    nom: "Bowl méditerranéen au quinoa",
    description: "Un bowl végétarien frais avec quinoa, pois chiches rôtis, crudités, feta et olives.",
    photoQuery: "mediterranean quinoa chickpea feta olive bowl",
    photoLocale: "/repas/plat-bowl-mediterraneen-quinoa.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["VEGETARIEN", "SANS_GLUTEN"],
    tempsMinutes: 25,
    macros: { calories: 560, proteines: 23, glucides: 69, lipides: 22 },
    portion: "1 bowl",
    allergenes: ["Lait"],
    conservation: "2 jours au réfrigérateur ; conserver l'assaisonnement séparément.",
    variantes: {
      LEAN: "50 g de quinoa sec, 30 g de feta et davantage de concombre.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 30 g de quinoa sec les jours intenses.",
      MASS: "Ajoute quinoa, feta et une cuillère d'huile d'olive.",
    },
    ingredients: [
      "70 g de quinoa, poids sec",
      "130 g de pois chiches cuits",
      "120 g de concombre",
      "120 g de tomates cerises",
      "50 g de feta",
      "25 g d'olives noires, persil et citron",
    ],
    etapes: [
      "Cuire le quinoa puis le laisser tiédir.",
      "Rôtir les pois chiches 15 minutes à 200°C avec paprika et cumin.",
      "Assembler quinoa, pois chiches, concombre, tomates, feta et olives, puis assaisonner au citron.",
    ],
  },
  {
    slug: "skyr-pomme-cannelle-granola",
    nom: "Bowl skyr, pomme, cannelle et granola",
    description: "Un bowl frais, riche en protéines et prêt en cinq minutes pour les matins pressés.",
    photoQuery: "skyr apple cinnamon granola bowl",
    photoLocale: "/repas/petit-dejeuner-skyr-pomme-granola.jpg",
    typeRepas: "PETIT_DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["VEGETARIEN"],
    tempsMinutes: 5,
    macros: { calories: 390, proteines: 27, glucides: 53, lipides: 9 },
    portion: "1 bowl",
    allergenes: ["Lait", "Gluten", "Graines"],
    conservation: "À assembler au dernier moment ; pomme coupée et skyr se conservent 12 heures séparément.",
    variantes: {
      LEAN: "20 g de granola, 250 g de skyr et une pomme entière.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 30 g de granola et une banane avant une séance longue.",
      MASS: "Ajoute une cuillère de purée d'amande et 30 g de granola.",
    },
    ingredients: ["250 g de skyr", "1 petite pomme rouge", "35 g de granola", "10 g de graines de courge", "Cannelle"],
    etapes: ["Verser le skyr dans un bowl.", "Couper la pomme en dés et la disposer avec le granola.", "Ajouter les graines de courge et la cannelle."],
  },
  {
    slug: "tartines-ricotta-figues-noix",
    nom: "Tartines ricotta, figues et noix",
    description: "Deux tartines sucrées-salées avec des glucides complets et une portion mesurée de bonnes graisses.",
    photoQuery: "wholegrain ricotta fig walnut toast",
    photoLocale: "/repas/petit-dejeuner-tartines-ricotta-figues-noix.jpg",
    typeRepas: "PETIT_DEJEUNER",
    objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["VEGETARIEN"],
    tempsMinutes: 8,
    macros: { calories: 460, proteines: 19, glucides: 52, lipides: 20 },
    portion: "2 tartines",
    allergenes: ["Gluten", "Lait", "Fruits à coque"],
    conservation: "À consommer immédiatement ; les éléments se conservent 2 jours séparément.",
    variantes: {
      LEAN: "Une grande tartine, 60 g de ricotta et 10 g de noix.",
      RESET_TRX: "Version de base avec un filet de miel très léger.",
      HYBRID: "Ajoute une troisième tartine avant une longue séance.",
      MASS: "Ajoute ricotta, noix et une cuillère de miel.",
    },
    ingredients: ["2 tranches de pain complet", "100 g de ricotta", "2 figues fraîches", "15 g de noix", "1 c. à café de miel"],
    etapes: ["Griller le pain complet.", "Étaler la ricotta et répartir les figues en quartiers.", "Ajouter les noix concassées et un filet de miel."],
  },
  {
    slug: "burrito-oeufs-dinde-epinards",
    nom: "Burrito petit-déjeuner aux œufs, dinde et épinards",
    description: "Un petit-déjeuner salé et transportable, complet sans fromage ni sauce lourde.",
    photoQuery: "breakfast burrito eggs turkey spinach red pepper",
    photoLocale: "/repas/petit-dejeuner-burrito-oeufs-dinde-epinards.jpg",
    typeRepas: "PETIT_DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: [],
    tempsMinutes: 15,
    macros: { calories: 470, proteines: 36, glucides: 42, lipides: 17 },
    portion: "1 burrito",
    allergenes: ["Œufs", "Gluten"],
    conservation: "24 heures au réfrigérateur ; réchauffer à la poêle ou au four.",
    variantes: {
      LEAN: "Une petite tortilla, 1 œuf + 120 g de blancs et 80 g de dinde.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute une tortilla plus grande et un fruit.",
      MASS: "Ajoute un œuf, davantage de dinde et un demi-avocat au moment de servir.",
    },
    ingredients: ["1 tortilla complète", "2 œufs", "80 g de blanc de dinde", "80 g d'épinards", "1/2 poivron rouge"],
    etapes: ["Faire revenir le poivron et les épinards.", "Ajouter les œufs battus et cuire doucement.", "Garnir la tortilla avec les œufs et la dinde, rouler fermement puis dorer à la poêle."],
  },
  {
    slug: "pudding-chia-mangue-coco",
    nom: "Pudding de chia, mangue et coco",
    description: "Une préparation fraîche à faire la veille, riche en fibres et naturellement sans gluten.",
    photoQuery: "chia pudding mango coconut glass",
    photoLocale: "/repas/petit-dejeuner-chia-mangue-coco.jpg",
    typeRepas: "PETIT_DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"],
    regimes: ["VEGETARIEN", "SANS_GLUTEN", "ANTI_INFLAMMATOIRE"],
    tempsMinutes: 8,
    macros: { calories: 350, proteines: 14, glucides: 38, lipides: 17 },
    portion: "1 verre",
    allergenes: ["Lait selon la boisson utilisée"],
    conservation: "2 jours au réfrigérateur dans un contenant fermé.",
    variantes: {
      LEAN: "25 g de chia, boisson végétale non sucrée et 100 g de mangue.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 40 g d'avoine et davantage de mangue.",
      MASS: "Ajoute yaourt grec, noix de cajou et copeaux de coco.",
    },
    ingredients: ["30 g de graines de chia", "200 ml de lait ou boisson végétale", "120 g de mangue", "10 g de coco râpée non sucrée", "Vanille"],
    etapes: ["Mélanger les graines de chia, le lait et la vanille.", "Réfrigérer au moins 4 heures en remuant après 15 minutes.", "Ajouter la mangue et la coco au moment de servir."],
  },
  {
    slug: "baked-oats-myrtilles-citron",
    nom: "Baked oats myrtilles et citron",
    description: "Un porridge cuit au four, moelleux au centre et pratique à préparer pour plusieurs matins.",
    photoQuery: "baked oats blueberry lemon ceramic dish",
    photoLocale: "/repas/petit-dejeuner-baked-oats-myrtilles-citron.jpg",
    typeRepas: "PETIT_DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["VEGETARIEN"],
    tempsMinutes: 30,
    macros: { calories: 420, proteines: 23, glucides: 59, lipides: 11 },
    portion: "1 petit plat",
    allergenes: ["Œufs", "Lait", "Gluten possible dans l'avoine"],
    conservation: "3 jours au réfrigérateur ou 1 mois au congélateur en portions.",
    variantes: {
      LEAN: "45 g d'avoine, 100 g de skyr et davantage de myrtilles.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 25 g d'avoine et une banane écrasée.",
      MASS: "Ajoute purée d'amande et noix concassées.",
    },
    ingredients: ["60 g de flocons d'avoine", "1 œuf", "100 g de skyr", "80 ml de lait", "100 g de myrtilles", "Zeste d'un demi-citron", "1/2 c. à café de levure"],
    etapes: ["Mélanger l'avoine, l'œuf, le skyr, le lait, le zeste et la levure.", "Incorporer la moitié des myrtilles et verser dans un petit plat.", "Ajouter le reste des myrtilles et cuire 22 à 25 minutes à 180°C."],
  },
  {
    slug: "porridge-sale-oeuf-epinards",
    nom: "Porridge salé, œuf et épinards",
    description: "Une alternative salée et rassasiante au porridge sucré, avec des fibres et une protéine complète.",
    photoQuery: "savory oatmeal poached egg spinach pumpkin seeds",
    photoLocale: "/repas/petit-dejeuner-porridge-sale-oeuf-epinards.jpg",
    typeRepas: "PETIT_DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["VEGETARIEN"],
    tempsMinutes: 15,
    macros: { calories: 380, proteines: 21, glucides: 42, lipides: 15 },
    portion: "1 bowl",
    allergenes: ["Œufs", "Lait", "Gluten possible dans l'avoine", "Graines"],
    conservation: "Le porridge se conserve 24 heures au réfrigérateur ; cuire l'œuf au moment de servir.",
    variantes: {
      LEAN: "40 g d'avoine, davantage d'épinards et 5 g de graines de courge.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 20 g d'avoine et un deuxième œuf après une séance matinale.",
      MASS: "Ajoute un deuxième œuf, 20 g d'avoine et 30 g de feta.",
    },
    ingredients: ["50 g de flocons d'avoine", "1 œuf", "150 ml de lait demi-écrémé", "100 g de jeunes épinards", "10 g de graines de courge", "Poivre noir"],
    etapes: ["Cuire l'avoine avec le lait et 100 ml d'eau pendant 5 à 7 minutes.", "Faire tomber les épinards dans une poêle puis les incorporer au porridge.", "Cuire l'œuf poché ou mollet, le déposer sur le bowl et terminer avec les graines et le poivre."],
  },
  {
    slug: "quinoa-petit-dejeuner-pomme-cannelle",
    nom: "Quinoa petit-déjeuner, pomme et cannelle",
    description: "Un bowl chaud sans gluten qui change de l'avoine, équilibré entre quinoa, fruit et skyr.",
    photoQuery: "breakfast quinoa apple cinnamon skyr almonds",
    photoLocale: "/repas/petit-dejeuner-quinoa-pomme-cannelle.jpg",
    typeRepas: "PETIT_DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["VEGETARIEN", "SANS_GLUTEN"],
    tempsMinutes: 20,
    macros: { calories: 445, proteines: 24, glucides: 61, lipides: 12 },
    portion: "1 bowl",
    allergenes: ["Lait", "Fruits à coque"],
    conservation: "Quinoa cuit et pomme se conservent 2 jours au réfrigérateur ; ajouter le skyr au service.",
    variantes: {
      LEAN: "45 g de quinoa sec, 200 g de skyr et 5 g d'amandes.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 20 g de quinoa sec et une demi-pomme avant une séance longue.",
      MASS: "Ajoute 20 g d'amandes et une cuillère de purée d'amande.",
    },
    ingredients: ["60 g de quinoa, poids sec", "1 petite pomme rouge", "150 g de skyr", "10 g d'amandes", "Cannelle", "Vanille"],
    etapes: ["Rincer le quinoa puis le cuire 12 à 15 minutes dans deux fois son volume d'eau avec la vanille.", "Couper la pomme en fines tranches et les poêler 3 minutes avec la cannelle.", "Servir le quinoa chaud avec le skyr, la pomme et les amandes concassées."],
  },
  {
    slug: "pain-perdu-proteine-banane",
    nom: "Pain perdu protéiné à la banane",
    description: "Un petit-déjeuner gourmand avec une base de pain complet, enrichi en protéines sans beurre ni friture.",
    photoQuery: "protein french toast banana skyr cinnamon",
    photoLocale: "/repas/petit-dejeuner-pain-perdu-proteine-banane.jpg",
    typeRepas: "PETIT_DEJEUNER",
    objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["VEGETARIEN"],
    tempsMinutes: 15,
    macros: { calories: 520, proteines: 32, glucides: 78, lipides: 10 },
    portion: "2 grandes tranches",
    allergenes: ["Œufs", "Lait", "Gluten"],
    conservation: "24 heures au réfrigérateur ; réchauffer au grille-pain ou à la poêle sans matière grasse.",
    variantes: {
      LEAN: "Une grande tranche, une demi-banane et 150 g de skyr.",
      RESET_TRX: "Deux petites tranches, sans sirop.",
      HYBRID: "Version de base, adaptée avant ou après une séance intense.",
      MASS: "Ajoute une tranche, une banane entière et une cuillère de purée de cacahuète.",
    },
    ingredients: ["2 grandes tranches de pain complet", "1 œuf", "100 g de blancs d'œufs", "120 ml de lait", "1 banane", "100 g de skyr", "Cannelle", "1 c. à café de sirop d'érable"],
    etapes: ["Battre l'œuf, les blancs, le lait et la cannelle puis imbiber le pain.", "Cuire 3 à 4 minutes par face dans une poêle antiadhésive.", "Servir avec le skyr, la banane en rondelles et un filet mesuré de sirop d'érable."],
  },
  {
    slug: "tartines-cottage-cheese-tomate-basilic",
    nom: "Tartines cottage cheese, tomate et basilic",
    description: "Deux tartines salées, fraîches et riches en protéines pour un matin rapide ou un brunch léger.",
    photoQuery: "wholegrain toast cottage cheese tomato basil",
    photoLocale: "/repas/petit-dejeuner-tartines-cottage-tomate-basilic.jpg",
    typeRepas: "PETIT_DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["VEGETARIEN"],
    tempsMinutes: 8,
    macros: { calories: 405, proteines: 29, glucides: 45, lipides: 12 },
    portion: "2 tartines",
    allergenes: ["Gluten", "Lait"],
    conservation: "À assembler au dernier moment ; la garniture se conserve 24 heures au réfrigérateur.",
    variantes: {
      LEAN: "Une grande tranche, 180 g de cottage cheese et sans huile ajoutée.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute une troisième tranche et un fruit.",
      MASS: "Ajoute une troisième tranche, davantage de cottage cheese et un filet d'huile d'olive.",
    },
    ingredients: ["2 tranches de pain complet au levain", "150 g de cottage cheese", "1 tomate mûre", "6 feuilles de basilic", "1 c. à café d'huile d'olive", "Poivre noir"],
    etapes: ["Griller le pain au levain.", "Répartir le cottage cheese puis les tranches de tomate.", "Ajouter le basilic, le poivre et un filet d'huile d'olive mesuré."],
  },
  {
    slug: "smoothie-bowl-ananas-epinards-kiwi",
    nom: "Smoothie bowl ananas, épinards et kiwi",
    description: "Un bowl vert frais et onctueux, avec des fruits entiers, du skyr et des graines pour mieux rassasier.",
    photoQuery: "green smoothie bowl pineapple spinach kiwi pumpkin seeds",
    photoLocale: "/repas/petit-dejeuner-smoothie-bowl-ananas-epinards-kiwi.jpg",
    typeRepas: "PETIT_DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"],
    regimes: ["VEGETARIEN", "SANS_GLUTEN", "ANTI_INFLAMMATOIRE"],
    tempsMinutes: 8,
    macros: { calories: 350, proteines: 20, glucides: 45, lipides: 11 },
    portion: "1 bowl",
    allergenes: ["Lait", "Graines"],
    conservation: "À consommer immédiatement pour préserver la texture ; les fruits peuvent être portionnés et congelés 1 mois.",
    variantes: {
      LEAN: "200 g de skyr, 100 g d'ananas et 5 g de coco.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 40 g d'avoine sans gluten et une banane.",
      MASS: "Ajoute 40 g d'avoine, une banane et une cuillère de purée de cajou.",
    },
    ingredients: ["150 g d'ananas surgelé", "1 kiwi", "60 g de jeunes épinards", "150 g de skyr", "80 ml d'eau", "10 g de graines de courge", "10 g de coco en copeaux non sucrée"],
    etapes: ["Mixer l'ananas, la moitié du kiwi, les épinards, le skyr et l'eau jusqu'à obtenir une texture épaisse.", "Verser dans un bowl froid.", "Ajouter le reste du kiwi, quelques cubes d'ananas, la coco et les graines de courge."],
  },
  {
    slug: "croque-madame-leger-dinde",
    nom: "Croque-madame léger au jambon de dinde",
    description: "Une version ouverte du croque-madame, riche en protéines et accompagnée d'une salade fraîche.",
    photoQuery: "light open croque madame turkey ham egg salad",
    photoLocale: "/repas/petit-dejeuner-croque-madame-dinde.jpg",
    typeRepas: "PETIT_DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: [],
    tempsMinutes: 15,
    macros: { calories: 385, proteines: 32, glucides: 34, lipides: 14 },
    portion: "1 grande tartine avec salade",
    allergenes: ["Œufs", "Lait", "Gluten", "Moutarde"],
    conservation: "À consommer immédiatement ; les éléments préparés se conservent 24 heures séparément.",
    variantes: {
      LEAN: "Pain complet de 50 g, fromage allégé mesuré et salade sans huile ajoutée.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute une deuxième tranche de pain complet et un fruit.",
      MASS: "Transforme en sandwich fermé et ajoute 30 g de fromage.",
    },
    ingredients: ["1 grande tranche de pain complet", "80 g de jambon de dinde", "1 œuf", "30 g d'emmental râpé", "1 c. à café de moutarde", "60 g de jeunes pousses"],
    etapes: ["Tartiner le pain de moutarde, ajouter le jambon de dinde et l'emmental.", "Gratiner 6 à 8 minutes sous le gril.", "Cuire l'œuf au plat, le poser sur la tartine et servir avec les jeunes pousses."],
  },
  {
    slug: "muffins-oeufs-epinards-feta",
    nom: "Muffins aux œufs, épinards et feta",
    description: "Trois bouchées salées préparables à l'avance, pratiques pour un petit-déjeuner riche en protéines.",
    photoQuery: "savory egg muffins spinach feta",
    photoLocale: "/repas/petit-dejeuner-muffins-oeufs-epinards-feta.jpg",
    typeRepas: "PETIT_DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["VEGETARIEN", "SANS_GLUTEN"],
    tempsMinutes: 30,
    macros: { calories: 315, proteines: 29, glucides: 6, lipides: 19 },
    portion: "3 muffins",
    allergenes: ["Œufs", "Lait"],
    conservation: "3 jours au réfrigérateur ou 1 mois au congélateur ; réchauffer à cœur.",
    variantes: {
      LEAN: "1 œuf, 150 g de blancs et 25 g de feta pour trois muffins.",
      RESET_TRX: "Version de base avec une tranche de pain complet à côté.",
      HYBRID: "Ajoute deux tranches de pain complet et un fruit.",
      MASS: "Passe à quatre muffins et ajoute pain, avocat et feta.",
    },
    ingredients: ["2 œufs", "100 g de blancs d'œufs", "100 g d'épinards", "40 g de feta", "1 petite échalote", "Poivre noir"],
    etapes: ["Faire tomber les épinards avec l'échalote puis laisser tiédir.", "Battre les œufs et les blancs, ajouter les épinards et la moitié de la feta.", "Répartir dans trois moules, ajouter le reste de feta et cuire 18 à 20 minutes à 180°C."],
  },
  {
    slug: "muesli-yaourt-kiwi-graines-courge",
    nom: "Muesli, yaourt, kiwi et graines de courge",
    description: "Un bowl sans cuisson, complet et croquant, avec un muesli non sucré et une base riche en protéines.",
    photoQuery: "plain yogurt muesli kiwi pumpkin seeds bowl",
    photoLocale: "/repas/petit-dejeuner-muesli-yaourt-kiwi-graines.jpg",
    typeRepas: "PETIT_DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["VEGETARIEN"],
    tempsMinutes: 5,
    macros: { calories: 455, proteines: 31, glucides: 58, lipides: 12 },
    portion: "1 bowl",
    allergenes: ["Lait", "Gluten", "Graines"],
    conservation: "À assembler au service ; le muesli se garde 1 mois au sec et le bowl préparé 12 heures au frais.",
    variantes: {
      LEAN: "35 g de muesli, 250 g de skyr et 5 g de graines.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 25 g de muesli et un deuxième kiwi.",
      MASS: "Ajoute 30 g de muesli, des raisins secs et une cuillère de purée d'amande.",
    },
    ingredients: ["250 g de skyr ou yaourt grec nature", "50 g de muesli sans sucre ajouté", "1 kiwi", "10 g de graines de courge", "Cannelle"],
    etapes: ["Verser le skyr dans un bowl.", "Ajouter le muesli sans l'enfoncer pour conserver le croquant.", "Disposer le kiwi en tranches, ajouter les graines et la cannelle."],
  },
  {
    slug: "galette-sarrasin-jambon-dinde-oeuf",
    nom: "Galette de sarrasin, jambon de dinde et œuf",
    description: "Une galette complète sans fromage, avec une garniture simple et protéinée pour un matin salé.",
    photoQuery: "buckwheat galette turkey ham fried egg",
    photoLocale: "/repas/petit-dejeuner-galette-sarrasin-dinde-oeuf.jpg",
    typeRepas: "PETIT_DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["SANS_GLUTEN"],
    tempsMinutes: 20,
    macros: { calories: 380, proteines: 31, glucides: 40, lipides: 11 },
    portion: "1 grande galette",
    allergenes: ["Œufs"],
    conservation: "La galette non garnie se conserve 2 jours au réfrigérateur ; garnir et cuire l'œuf au moment de servir.",
    variantes: {
      LEAN: "Une galette fine, 100 g de dinde et une grande salade.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute une deuxième galette nature et un fruit.",
      MASS: "Ajoute une seconde galette garnie et 30 g de fromage râpé.",
    },
    ingredients: ["60 g de farine de sarrasin", "140 ml d'eau", "1 œuf", "80 g de jambon de dinde", "60 g de mâche", "Sel et poivre"],
    etapes: ["Mélanger la farine, l'eau et une pincée de sel, puis laisser reposer 15 minutes si possible.", "Cuire la galette dans une poêle antiadhésive et ajouter le jambon de dinde.", "Casser l'œuf au centre, replier les bords et couvrir jusqu'à ce que le blanc soit pris ; servir avec la mâche."],
  },
  {
    slug: "riz-au-lait-proteine-vanille-framboises",
    nom: "Riz au lait protéiné, vanille et framboises",
    description: "Un riz au lait crémeux enrichi en protéines, servi avec des framboises fraîches sans sucre ajouté.",
    photoQuery: "protein rice pudding vanilla raspberries",
    photoLocale: "/repas/petit-dejeuner-riz-lait-proteine-framboises.jpg",
    typeRepas: "PETIT_DEJEUNER",
    objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["VEGETARIEN", "SANS_GLUTEN"],
    tempsMinutes: 35,
    macros: { calories: 440, proteines: 29, glucides: 69, lipides: 6 },
    portion: "1 bowl",
    allergenes: ["Lait"],
    conservation: "2 jours au réfrigérateur dans un contenant fermé ; détendre avec un peu de lait au service.",
    variantes: {
      LEAN: "45 g de riz sec, lait écrémé et 150 g de framboises.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 20 g de riz sec et une banane les jours de forte dépense.",
      MASS: "Ajoute 25 g de riz sec, du lait entier et une cuillère de purée d'amande.",
    },
    ingredients: ["60 g de riz rond, poids sec", "300 ml de lait demi-écrémé", "20 g de protéine whey vanille", "100 g de framboises", "1/2 gousse de vanille"],
    etapes: ["Rincer le riz puis le cuire à feu doux dans le lait avec la vanille pendant 25 à 30 minutes en remuant.", "Retirer du feu, laisser tiédir 5 minutes puis incorporer la whey progressivement pour éviter les grumeaux.", "Servir tiède ou froid avec les framboises."],
  },
  {
    slug: "salade-cesar-legere-poulet",
    nom: "Salade César légère au poulet",
    description: "Une César complète avec poulet grillé, sauce au yaourt et croûtons complets mesurés.",
    photoQuery: "light chicken Caesar salad yogurt dressing wholegrain croutons",
    photoLocale: "/repas/dejeuner-salade-cesar-legere-poulet.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: [],
    tempsMinutes: 25,
    macros: { calories: 505, proteines: 54, glucides: 38, lipides: 16 },
    portion: "1 grande salade",
    allergenes: ["Lait", "Gluten", "Moutarde"],
    conservation: "24 heures au réfrigérateur en séparant la sauce et les croûtons ; ne pas recongeler le poulet.",
    variantes: {
      LEAN: "20 g de croûtons, 15 g de parmesan et davantage de romaine.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 40 g de pain complet et un fruit.",
      MASS: "Double les croûtons, ajoute du parmesan et une tranche de pain complet.",
    },
    ingredients: ["160 g de blanc de poulet", "180 g de laitue romaine", "40 g de pain complet", "20 g de parmesan", "80 g de yaourt grec", "1 c. à café de moutarde", "Jus de citron, ail et poivre"],
    etapes: ["Griller le poulet assaisonné puis le laisser reposer avant de le trancher.", "Couper le pain en cubes et le dorer au four 8 minutes à 190°C.", "Mélanger yaourt, moutarde, citron et ail, puis assembler romaine, poulet, croûtons, parmesan et sauce."],
  },
  {
    slug: "wrap-dinde-houmous-crudites",
    nom: "Wrap dinde, houmous et crudités",
    description: "Un wrap complet, croquant et transportable, avec une sauce remplacée par une portion de houmous.",
    photoQuery: "wholegrain turkey hummus vegetable wrap",
    photoLocale: "/repas/dejeuner-wrap-dinde-houmous-crudites.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: [],
    tempsMinutes: 12,
    macros: { calories: 510, proteines: 40, glucides: 58, lipides: 15 },
    portion: "1 grand wrap",
    allergenes: ["Gluten", "Sésame"],
    conservation: "24 heures au réfrigérateur, bien emballé ; garder les crudités très sèches pour préserver la tortilla.",
    variantes: {
      LEAN: "Petite tortilla, 140 g de dinde, 30 g de houmous et davantage de crudités.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute un fruit et un yaourt après l'entraînement.",
      MASS: "Ajoute une seconde tortilla, davantage de houmous et un demi-avocat.",
    },
    ingredients: ["1 grande tortilla complète", "120 g de blanc de dinde cuit", "50 g de houmous", "60 g de carotte râpée", "60 g de concombre", "40 g de chou rouge", "40 g de laitue"],
    etapes: ["Réchauffer légèrement la tortilla pour l'assouplir.", "Étaler le houmous puis répartir la dinde et les crudités bien égouttées.", "Rabattre les côtés, rouler fermement et couper en deux."],
  },
  {
    slug: "poke-saumon-avocat-edamame",
    nom: "Poke saumon, avocat et edamame",
    description: "Un bowl frais riche en oméga-3, avec une portion contrôlée de riz, d'avocat et d'edamame.",
    photoQuery: "salmon poke bowl avocado edamame rice cucumber carrot",
    photoLocale: "/repas/dejeuner-poke-saumon-avocat-edamame.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["SANS_GLUTEN", "ANTI_INFLAMMATOIRE"],
    tempsMinutes: 25,
    macros: { calories: 680, proteines: 42, glucides: 70, lipides: 25 },
    portion: "1 grand bowl",
    allergenes: ["Poisson", "Soja", "Sésame"],
    conservation: "À consommer le jour même ; utiliser du saumon qualité sashimi et respecter strictement la chaîne du froid.",
    variantes: {
      LEAN: "45 g de riz sec, 150 g de saumon, 30 g d'avocat et davantage de concombre.",
      RESET_TRX: "Version de base avec 50 g de riz sec.",
      HYBRID: "Ajoute 25 g de riz sec les jours d'entraînement long.",
      MASS: "Ajoute riz, avocat, edamame et une cuillère d'huile de sésame.",
    },
    ingredients: ["120 g de saumon cru qualité sashimi", "60 g de riz à sushi, poids sec", "70 g d'edamame décortiqués", "50 g d'avocat", "80 g de concombre", "60 g de carotte", "1 c. à café de tamari sans gluten", "5 g de graines de sésame noir"],
    etapes: ["Cuire le riz, l'assaisonner légèrement au vinaigre de riz et le laisser refroidir.", "Couper le saumon, l'avocat, le concombre et la carotte, puis cuire les edamame.", "Disposer chaque élément en section dans le bowl et terminer avec le tamari et le sésame."],
  },
  {
    slug: "salade-pates-thon-legumes",
    nom: "Salade de pâtes au thon et légumes",
    description: "Une salade méditerranéenne complète et facile à préparer en avance, sans mayonnaise.",
    photoQuery: "wholegrain pasta tuna vegetable salad",
    photoLocale: "/repas/dejeuner-salade-pates-thon-legumes.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["ANTI_INFLAMMATOIRE"],
    tempsMinutes: 25,
    macros: { calories: 620, proteines: 46, glucides: 72, lipides: 17 },
    portion: "1 grand bowl",
    allergenes: ["Poisson", "Gluten"],
    conservation: "2 jours au réfrigérateur dans un contenant fermé ; ajouter le citron juste avant de servir.",
    variantes: {
      LEAN: "60 g de pâtes sèches, 160 g de thon et davantage de légumes.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 30 g de pâtes sèches après une séance intense.",
      MASS: "Ajoute pâtes, huile d'olive et une tranche de pain complet.",
    },
    ingredients: ["80 g de fusilli complets, poids sec", "140 g de thon au naturel égoutté", "100 g de tomates cerises", "80 g de concombre", "80 g de haricots verts", "60 g de poivron rouge rôti", "10 g d'huile d'olive", "Citron et persil"],
    etapes: ["Cuire les pâtes al dente et les haricots verts, puis refroidir rapidement.", "Égoutter le thon et couper tous les légumes.", "Mélanger avec l'huile, le citron et le persil, puis réserver au frais."],
  },
  {
    slug: "poulet-semoule-legumes-rotis",
    nom: "Poulet, semoule complète et légumes rôtis",
    description: "Une assiette meal-prep simple, colorée et équilibrée autour d'un poulet aux herbes.",
    photoQuery: "grilled chicken wholegrain couscous roasted vegetables",
    photoLocale: "/repas/dejeuner-poulet-semoule-legumes-rotis.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["ANTI_INFLAMMATOIRE"],
    tempsMinutes: 35,
    macros: { calories: 675, proteines: 55, glucides: 74, lipides: 15 },
    portion: "1 grande assiette",
    allergenes: ["Gluten"],
    conservation: "3 jours au réfrigérateur ou 2 mois au congélateur ; refroidir rapidement avant stockage.",
    variantes: {
      LEAN: "50 g de semoule sèche, 180 g de poulet et une double portion de légumes.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 30 g de semoule sèche les jours intenses.",
      MASS: "Ajoute semoule, huile d'olive et pois chiches rôtis.",
    },
    ingredients: ["160 g de blanc de poulet", "70 g de semoule complète, poids sec", "120 g de courgette", "100 g de poivron rouge", "100 g de carotte", "60 g d'oignon rouge", "5 g d'huile d'olive", "Citron, persil et herbes de Provence"],
    etapes: ["Couper les légumes, les mélanger avec l'huile et les rôtir 25 minutes à 200°C.", "Cuire le poulet aux herbes à la poêle ou au gril, puis le laisser reposer et le trancher.", "Réhydrater la semoule, l'aérer à la fourchette et servir avec le poulet, les légumes, le citron et le persil."],
  },
  {
    slug: "bowl-boeuf-quinoa-betterave",
    nom: "Bowl bœuf, quinoa et betterave",
    description: "Un bowl riche en fer et en protéines, avec betterave rôtie et sauce fraîche aux herbes.",
    photoQuery: "lean beef quinoa beetroot spinach cucumber bowl",
    photoLocale: "/repas/dejeuner-bowl-boeuf-quinoa-betterave.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["SANS_GLUTEN"],
    tempsMinutes: 30,
    macros: { calories: 640, proteines: 51, glucides: 61, lipides: 20 },
    portion: "1 grand bowl",
    allergenes: ["Lait"],
    conservation: "2 jours au réfrigérateur, sauce séparée ; réchauffer uniquement le bœuf, le quinoa et la betterave.",
    variantes: {
      LEAN: "45 g de quinoa sec, 180 g de bœuf maigre et sauce au skyr sans huile.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 25 g de quinoa sec après un entraînement intense.",
      MASS: "Ajoute quinoa, huile d'olive et une portion de noix.",
    },
    ingredients: ["160 g de steak de bœuf maigre", "60 g de quinoa, poids sec", "120 g de betterave cuite", "80 g de concombre", "60 g de jeunes épinards", "80 g de yaourt grec", "Citron, persil et poivre"],
    etapes: ["Cuire le quinoa et rôtir les cubes de betterave 15 minutes à 200°C.", "Saisir le bœuf selon la cuisson souhaitée, le laisser reposer puis le trancher.", "Mélanger yaourt, citron et persil, puis assembler tous les éléments dans le bowl."],
  },
  {
    slug: "salade-lentilles-feta-legumes-rotis",
    nom: "Salade de lentilles, feta et légumes rôtis",
    description: "Une salade végétarienne complète, riche en fibres, servie tiède ou froide.",
    photoQuery: "lentil feta roasted vegetable salad arugula",
    photoLocale: "/repas/dejeuner-salade-lentilles-feta-legumes-rotis.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["VEGETARIEN", "SANS_GLUTEN", "ANTI_INFLAMMATOIRE"],
    tempsMinutes: 35,
    macros: { calories: 585, proteines: 28, glucides: 61, lipides: 24 },
    portion: "1 grand bowl",
    allergenes: ["Lait"],
    conservation: "3 jours au réfrigérateur ; ajouter la roquette et la feta après réchauffage éventuel.",
    variantes: {
      LEAN: "180 g de lentilles cuites, 35 g de feta et double portion de légumes.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute une tranche de pain complet et un fruit.",
      MASS: "Ajoute lentilles, feta, huile d'olive et pain complet.",
    },
    ingredients: ["220 g de lentilles vertes cuites", "60 g de feta", "120 g de courgette", "100 g de poivron rouge", "80 g de carotte", "60 g d'oignon rouge", "40 g de roquette", "10 g d'huile d'olive", "Citron et persil"],
    etapes: ["Rôtir courgette, poivron, carotte et oignon avec la moitié de l'huile 25 minutes à 200°C.", "Rincer et égoutter les lentilles puis les mélanger aux légumes encore tièdes.", "Ajouter roquette, feta, persil, citron et le reste d'huile au moment de servir."],
  },
  {
    slug: "nouilles-tofu-cacahuete",
    nom: "Nouilles au tofu et sauce cacahuète",
    description: "Un plat végétarien complet avec tofu doré, légumes croquants et sauce cacahuète mesurée.",
    photoQuery: "rice noodles tofu peanut sauce vegetables",
    photoLocale: "/repas/dejeuner-nouilles-tofu-cacahuete.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["VEGETARIEN", "SANS_GLUTEN"],
    tempsMinutes: 30,
    macros: { calories: 715, proteines: 35, glucides: 87, lipides: 28 },
    portion: "1 grand bowl",
    allergenes: ["Soja", "Arachides"],
    conservation: "2 jours au réfrigérateur ; détendre la sauce avec une cuillère d'eau au réchauffage.",
    variantes: {
      LEAN: "55 g de nouilles sèches, 200 g de tofu, 10 g de cacahuètes et davantage de brocoli.",
      RESET_TRX: "Version de base avec 15 g de purée de cacahuète.",
      HYBRID: "Ajoute 25 g de nouilles sèches les jours longs.",
      MASS: "Ajoute nouilles, tofu et une cuillère supplémentaire de purée de cacahuète.",
    },
    ingredients: ["80 g de nouilles de riz, poids sec", "180 g de tofu ferme", "120 g de brocoli", "80 g de carotte", "80 g de poivron rouge", "20 g de purée de cacahuète", "1 c. à soupe de tamari sans gluten", "Citron vert et cébette"],
    etapes: ["Presser le tofu, le couper en cubes et le dorer à la poêle.", "Cuire les nouilles et sauter les légumes en les gardant croquants.", "Délayer purée de cacahuète, tamari, citron vert et eau chaude, puis mélanger avec les nouilles, le tofu et les légumes."],
  },
  {
    slug: "tacos-cabillaud-chou-yaourt",
    nom: "Tacos de cabillaud, chou et sauce yaourt",
    description: "Deux tacos frais et protéinés avec poisson grillé, chou croquant et sauce citron vert.",
    photoQuery: "cod tacos purple cabbage yogurt lime",
    photoLocale: "/repas/dejeuner-tacos-cabillaud-chou-yaourt.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["SANS_GLUTEN"],
    tempsMinutes: 25,
    macros: { calories: 420, proteines: 40, glucides: 43, lipides: 10 },
    portion: "2 tacos",
    allergenes: ["Poisson", "Lait"],
    conservation: "24 heures au réfrigérateur, éléments séparés ; réchauffer le poisson à cœur et garnir au dernier moment.",
    variantes: {
      LEAN: "Deux petites tortillas, 180 g de cabillaud et sauce au skyr 0 %.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute un troisième taco et un fruit.",
      MASS: "Ajoute deux tacos, un demi-avocat et davantage de poisson.",
    },
    ingredients: ["160 g de cabillaud", "2 tortillas de maïs", "100 g de chou rouge", "60 g de carotte", "80 g de yaourt grec", "1 citron vert", "Coriandre, cumin et paprika"],
    etapes: ["Assaisonner le cabillaud au cumin et paprika puis le griller 3 à 4 minutes par face.", "Mélanger chou, carotte, coriandre et la moitié du jus de citron vert.", "Réchauffer les tortillas, garnir de poisson et de chou, puis ajouter le yaourt mélangé au reste de citron."],
  },
  {
    slug: "poivrons-farcis-dinde-quinoa",
    nom: "Poivrons farcis à la dinde et au quinoa",
    description: "Des poivrons généreusement garnis d'une farce maigre, sans fromage et faciles à préparer en avance.",
    photoQuery: "bell peppers stuffed turkey quinoa tomato parsley",
    photoLocale: "/repas/dejeuner-poivrons-farcis-dinde-quinoa.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["SANS_GLUTEN"],
    tempsMinutes: 50,
    macros: { calories: 670, proteines: 50, glucides: 68, lipides: 21 },
    portion: "2 demi-poivrons garnis",
    allergenes: [],
    conservation: "3 jours au réfrigérateur ou 2 mois au congélateur ; réchauffer à cœur au four.",
    variantes: {
      LEAN: "45 g de quinoa sec, 180 g de dinde maigre et une grande salade.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 25 g de quinoa sec dans la farce.",
      MASS: "Ajoute quinoa, huile d'olive et 30 g de fromage râpé avant cuisson.",
    },
    ingredients: ["1 grand poivron rouge", "1 grand poivron jaune", "160 g de dinde hachée", "60 g de quinoa, poids sec", "150 g de tomates concassées", "1 petit oignon", "5 g d'huile d'olive", "Paprika et persil"],
    etapes: ["Cuire le quinoa et précuire les demi-poivrons 12 minutes à 190°C.", "Faire revenir oignon et dinde, ajouter tomate, paprika, persil et quinoa.", "Garnir les poivrons et cuire encore 20 à 25 minutes jusqu'à ce qu'ils soient tendres."],
  },
  {
    slug: "crevettes-semoule-courgettes",
    nom: "Crevettes, semoule complète et courgettes",
    description: "Une assiette citronnée rapide, riche en protéines et idéale pour un déjeuner après l'entraînement.",
    photoQuery: "garlic lemon shrimp wholegrain couscous zucchini",
    photoLocale: "/repas/dejeuner-crevettes-semoule-courgettes.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["ANTI_INFLAMMATOIRE"],
    tempsMinutes: 25,
    macros: { calories: 570, proteines: 45, glucides: 61, lipides: 15 },
    portion: "1 grande assiette",
    allergenes: ["Crustacés", "Gluten"],
    conservation: "2 jours au réfrigérateur ; refroidir vite et réchauffer les crevettes une seule fois à cœur.",
    variantes: {
      LEAN: "50 g de semoule sèche, 200 g de crevettes et davantage de courgettes.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 30 g de semoule sèche après une séance intense.",
      MASS: "Ajoute semoule, huile d'olive et une poignée d'amandes.",
    },
    ingredients: ["180 g de crevettes décortiquées", "70 g de semoule complète, poids sec", "250 g de courgette", "10 g d'huile d'olive", "1 gousse d'ail", "1/2 citron", "Persil et poivre"],
    etapes: ["Réhydrater la semoule avec son volume d'eau chaude et l'aérer à la fourchette.", "Sauter les courgettes dans la moitié de l'huile jusqu'à ce qu'elles soient dorées.", "Cuire les crevettes avec l'ail et le reste d'huile 3 à 4 minutes, puis servir avec citron et persil."],
  },
  {
    slug: "pates-poulet-pesto-tomates",
    nom: "Pâtes complètes, poulet, pesto et tomates",
    description: "Un plat généreux et simple avec pesto mesuré, poulet grillé et tomates fraîches.",
    photoQuery: "wholegrain penne grilled chicken basil pesto cherry tomatoes",
    photoLocale: "/repas/dejeuner-pates-poulet-pesto-tomates.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: [],
    tempsMinutes: 25,
    macros: { calories: 695, proteines: 59, glucides: 73, lipides: 20 },
    portion: "1 grand bowl",
    allergenes: ["Gluten", "Lait", "Fruits à coque"],
    conservation: "3 jours au réfrigérateur ; ajouter une cuillère d'eau avant de réchauffer doucement.",
    variantes: {
      LEAN: "60 g de pâtes sèches, 180 g de poulet et 10 g de pesto.",
      RESET_TRX: "Version de base avec 15 g de pesto.",
      HYBRID: "Ajoute 30 g de pâtes sèches les jours de forte dépense.",
      MASS: "Ajoute pâtes, pesto, parmesan et huile d'olive.",
    },
    ingredients: ["80 g de penne complètes, poids sec", "160 g de blanc de poulet", "20 g de pesto au basilic", "150 g de tomates cerises", "10 g de parmesan", "Basilic et poivre"],
    etapes: ["Cuire les pâtes al dente en réservant un peu d'eau de cuisson.", "Griller le poulet, le laisser reposer puis le trancher.", "Délayer le pesto avec une cuillère d'eau de cuisson et mélanger avec pâtes, poulet, tomates, basilic et parmesan."],
  },
  {
    slug: "salade-saumon-pommes-terre-haricots-verts",
    nom: "Salade de saumon, pommes de terre et haricots verts",
    description: "Une salade complète aux oméga-3, servie tiède ou froide avec une vinaigrette citron-moutarde.",
    photoQuery: "salmon potato green bean salad dill lemon",
    photoLocale: "/repas/dejeuner-salade-saumon-pommes-terre-haricots.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["SANS_GLUTEN", "ANTI_INFLAMMATOIRE"],
    tempsMinutes: 35,
    macros: { calories: 635, proteines: 41, glucides: 55, lipides: 27 },
    portion: "1 grande salade",
    allergenes: ["Poisson", "Moutarde"],
    conservation: "2 jours au réfrigérateur ; conserver la vinaigrette séparément et ne pas recongeler le saumon.",
    variantes: {
      LEAN: "180 g de saumon, 160 g de pommes de terre et davantage de haricots verts.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 120 g de pommes de terre les jours intenses.",
      MASS: "Ajoute pommes de terre, huile d'olive et une tranche de pain complet.",
    },
    ingredients: ["150 g de filet de saumon", "250 g de pommes de terre grenaille", "150 g de haricots verts", "100 g de tomates cerises", "50 g de jeunes épinards", "5 g d'huile d'olive", "1 c. à café de moutarde", "Citron et aneth"],
    etapes: ["Cuire les pommes de terre et les haricots verts séparément, puis les laisser tiédir.", "Cuire le saumon au four 12 à 15 minutes à 190°C et le détailler en gros morceaux.", "Mélanger huile, moutarde, citron et aneth, puis assembler tous les ingrédients sans écraser le saumon."],
  },
  {
    slug: "burrito-bowl-boeuf",
    nom: "Burrito bowl au bœuf",
    description: "Toutes les saveurs d'un burrito dans un bowl complet, sans tortilla ni fromage.",
    photoQuery: "lean beef burrito bowl brown rice black beans corn salsa",
    photoLocale: "/repas/dejeuner-burrito-bowl-boeuf.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["SANS_GLUTEN"],
    tempsMinutes: 30,
    macros: { calories: 735, proteines: 50, glucides: 88, lipides: 21 },
    portion: "1 grand bowl",
    allergenes: ["Lait"],
    conservation: "3 jours au réfrigérateur, yaourt et crudités séparés ; réchauffer bœuf, riz, haricots et maïs à cœur.",
    variantes: {
      LEAN: "45 g de riz sec, 180 g de bœuf maigre, davantage de laitue et sans maïs.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 25 g de riz sec après une séance intense.",
      MASS: "Ajoute riz, haricots, avocat et une tortilla complète.",
    },
    ingredients: ["150 g de bœuf haché 5 %", "60 g de riz complet, poids sec", "120 g de haricots noirs cuits", "80 g de maïs", "120 g de tomates", "60 g de laitue", "70 g de yaourt grec", "Cumin, paprika et citron vert"],
    etapes: ["Cuire le riz et réchauffer les haricots noirs avec le maïs.", "Faire revenir le bœuf avec cumin et paprika jusqu'à cuisson complète.", "Assembler chaque élément dans le bowl, ajouter tomate et laitue, puis terminer avec le yaourt citronné."],
  },
  {
    slug: "falafels-taboule-sauce-yaourt",
    nom: "Falafels au four, taboulé et sauce yaourt",
    description: "Un déjeuner végétarien complet avec falafels cuits au four et taboulé très riche en herbes.",
    photoQuery: "baked falafel bulgur tabbouleh yogurt lemon sauce",
    photoLocale: "/repas/dejeuner-falafels-taboule-sauce-yaourt.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["VEGETARIEN", "ANTI_INFLAMMATOIRE"],
    tempsMinutes: 40,
    macros: { calories: 620, proteines: 28, glucides: 92, lipides: 16 },
    portion: "4 falafels avec taboulé",
    allergenes: ["Gluten", "Lait"],
    conservation: "3 jours au réfrigérateur ou 2 mois au congélateur pour les falafels ; sauce 2 jours au frais.",
    variantes: {
      LEAN: "Trois falafels, 45 g de boulgour sec et davantage d'herbes et de concombre.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute deux falafels et 20 g de boulgour sec.",
      MASS: "Ajoute falafels, boulgour, huile d'olive et houmous.",
    },
    ingredients: ["180 g de pois chiches cuits", "60 g de boulgour, poids sec", "120 g de tomate", "100 g de concombre", "30 g de persil", "10 g de menthe", "100 g de yaourt grec", "1/2 citron", "Cumin, ail et coriandre"],
    etapes: ["Mixer grossièrement pois chiches, ail, cumin, coriandre et la moitié des herbes, former quatre falafels puis cuire 22 minutes à 200°C.", "Cuire et refroidir le boulgour, puis le mélanger avec tomate, concombre, persil, menthe et citron.", "Mélanger le yaourt avec citron et ail, puis servir avec les falafels et le taboulé."],
  },
  {
    slug: "riz-saute-oeuf-kimchi-doux",
    nom: "Riz sauté à l'œuf et kimchi doux",
    description: "Un riz complet anti-gaspi avec légumes, kimchi peu pimenté et protéines d'œuf.",
    photoQuery: "healthy kimchi egg fried brown rice vegetables",
    photoLocale: "/repas/dejeuner-riz-saute-oeuf-kimchi.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["VEGETARIEN", "SANS_GLUTEN"],
    tempsMinutes: 20,
    macros: { calories: 505, proteines: 25, glucides: 71, lipides: 13 },
    portion: "1 grand bowl",
    allergenes: ["Œufs", "Soja", "Sésame"],
    conservation: "24 heures au réfrigérateur ; refroidir le riz rapidement et réchauffer une seule fois jusqu'à ce qu'il soit fumant.",
    variantes: {
      LEAN: "50 g de riz sec, 150 g de blancs d'œufs et davantage de légumes.",
      RESET_TRX: "Version de base avec kimchi peu pimenté.",
      HYBRID: "Ajoute 30 g de riz sec et un deuxième œuf.",
      MASS: "Ajoute riz, deux œufs et une cuillère d'huile de sésame.",
    },
    ingredients: ["70 g de riz complet, poids sec", "1 œuf", "100 g de blancs d'œufs", "100 g de kimchi doux", "80 g de petits pois", "60 g de carotte", "1 c. à soupe de tamari sans gluten", "5 g de graines de sésame", "Cébette"],
    etapes: ["Cuire le riz à l'avance, le refroidir rapidement puis le conserver au frais.", "Sauter carotte, petits pois et kimchi, ajouter le riz et le tamari puis incorporer les blancs d'œufs en remuant.", "Cuire l'œuf au plat séparément, le poser sur le riz et terminer avec cébette et sésame."],
  },
  {
    slug: "club-sandwich-dinde",
    nom: "Club sandwich à la dinde",
    description: "Un club complet sans bacon ni mayonnaise, garni de dinde, crudités et sauce yaourt-moutarde.",
    photoQuery: "healthy wholegrain turkey club sandwich lettuce tomato cucumber",
    photoLocale: "/repas/dejeuner-club-sandwich-dinde.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: [],
    tempsMinutes: 15,
    macros: { calories: 550, proteines: 47, glucides: 64, lipides: 11 },
    portion: "1 club coupé en deux",
    allergenes: ["Gluten", "Lait", "Moutarde"],
    conservation: "À consommer dans les 12 heures, bien emballé au réfrigérateur ; garder la sauce séparée si possible.",
    variantes: {
      LEAN: "Deux tranches de pain, 160 g de dinde et davantage de crudités.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute un fruit et un yaourt après la séance.",
      MASS: "Ajoute une tranche de pain, davantage de dinde et un demi-avocat.",
    },
    ingredients: ["3 fines tranches de pain complet", "150 g de blanc de dinde", "80 g de yaourt grec", "1 c. à café de moutarde", "80 g de tomate", "60 g de concombre", "50 g de laitue"],
    etapes: ["Mélanger le yaourt et la moutarde puis griller légèrement le pain.", "Monter le club en deux étages avec sauce, dinde, tomate, concombre et laitue.", "Maintenir avec deux pics et couper en deux triangles."],
  },
  {
    slug: "tartines-sardines-tomate-haricots-blancs",
    nom: "Tartines sardines, tomate et haricots blancs",
    description: "Deux tartines méditerranéennes riches en oméga-3, fibres et calcium.",
    photoQuery: "sardine tomato white bean wholegrain toast",
    photoLocale: "/repas/dejeuner-tartines-sardines-tomate-haricots.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["ANTI_INFLAMMATOIRE"],
    tempsMinutes: 15,
    macros: { calories: 615, proteines: 40, glucides: 68, lipides: 20 },
    portion: "2 grandes tartines",
    allergenes: ["Poisson", "Gluten"],
    conservation: "À assembler au dernier moment ; la préparation haricots-tomate se conserve 2 jours et les sardines ouvertes 24 heures au frais.",
    variantes: {
      LEAN: "Une grande tartine, 120 g de sardines et 150 g de haricots blancs.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute une troisième tartine après un entraînement long.",
      MASS: "Ajoute pain, haricots blancs et un filet d'huile d'olive.",
    },
    ingredients: ["2 grandes tranches de pain complet au levain", "100 g de sardines égouttées", "120 g de haricots blancs cuits", "150 g de tomates", "1/2 citron", "Persil, ail et poivre"],
    etapes: ["Écraser grossièrement les haricots avec tomate, ail, citron et poivre.", "Griller le pain puis répartir la préparation aux haricots.", "Déposer les sardines, ajouter persil et zeste de citron, puis servir immédiatement."],
  },
  {
    slug: "bowl-tempeh-patate-douce-chou-rouge",
    nom: "Bowl tempeh, patate douce et chou rouge",
    description: "Un bowl végétarien coloré et rassasiant avec tempeh doré et sauce tahini-citron.",
    photoQuery: "tempeh sweet potato red cabbage broccoli bowl tahini",
    photoLocale: "/repas/dejeuner-bowl-tempeh-patate-douce-chou.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["VEGETARIEN", "ANTI_INFLAMMATOIRE"],
    tempsMinutes: 35,
    macros: { calories: 755, proteines: 38, glucides: 82, lipides: 32 },
    portion: "1 grand bowl",
    allergenes: ["Soja", "Sésame"],
    conservation: "3 jours au réfrigérateur, sauce séparée ; réchauffer tempeh, patate douce et brocoli avant assemblage.",
    variantes: {
      LEAN: "160 g de tempeh, 160 g de patate douce et 10 g de tahini.",
      RESET_TRX: "Version de base avec 15 g de tahini.",
      HYBRID: "Ajoute 120 g de patate douce les jours intenses.",
      MASS: "Ajoute tempeh, patate douce, tahini et graines de courge.",
    },
    ingredients: ["180 g de tempeh", "250 g de patate douce", "120 g de chou rouge", "120 g de brocoli", "80 g de concombre", "20 g de tahini", "1/2 citron", "Paprika et poivre"],
    etapes: ["Rôtir les cubes de patate douce au paprika 25 minutes à 200°C et cuire le brocoli à la vapeur.", "Trancher le tempeh et le dorer à la poêle sur les deux faces.", "Délayer le tahini avec citron et eau, puis assembler avec chou rouge et concombre crus."],
  },
  {
    slug: "poulet-satay-riz-legumes",
    nom: "Poulet satay, riz et légumes",
    description: "Un bowl complet au poulet grillé avec une sauce cacahuète-citron vert légère et mesurée.",
    photoQuery: "chicken satay rice vegetable bowl peanut sauce",
    photoLocale: "/repas/dejeuner-poulet-satay-riz-legumes.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["SANS_GLUTEN"],
    tempsMinutes: 30,
    macros: { calories: 735, proteines: 58, glucides: 75, lipides: 22 },
    portion: "1 grand bowl",
    allergenes: ["Arachides", "Soja"],
    conservation: "3 jours au réfrigérateur, sauce séparée ; réchauffer poulet, riz et légumes à cœur.",
    variantes: {
      LEAN: "50 g de riz sec, 180 g de poulet et 10 g de purée de cacahuète.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 30 g de riz sec après une séance intense.",
      MASS: "Ajoute riz, sauce cacahuète et une portion de noix de cajou.",
    },
    ingredients: ["160 g de blanc de poulet", "70 g de riz jasmin, poids sec", "120 g de brocoli", "80 g de carotte", "80 g de poivron rouge", "60 g de concombre", "20 g de purée de cacahuète", "1 c. à soupe de tamari sans gluten", "Citron vert et coriandre"],
    etapes: ["Cuire le riz et les légumes en gardant brocoli, carotte et poivron légèrement croquants.", "Griller le poulet, le laisser reposer puis le trancher.", "Délayer purée de cacahuète, tamari, citron vert et eau chaude, puis servir en filet mesuré sur le bowl."],
  },
  {
    slug: "salade-nicoise-thon",
    nom: "Salade niçoise au thon",
    description: "Une salade composée complète avec thon, œuf, pommes de terre et haricots verts.",
    photoQuery: "tuna Nicoise salad potato green beans egg olives",
    photoLocale: "/repas/dejeuner-salade-nicoise-thon.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["SANS_GLUTEN", "ANTI_INFLAMMATOIRE"],
    tempsMinutes: 30,
    macros: { calories: 600, proteines: 49, glucides: 52, lipides: 22 },
    portion: "1 grande salade",
    allergenes: ["Poisson", "Œufs", "Moutarde"],
    conservation: "24 heures au réfrigérateur, vinaigrette séparée ; utiliser du thon fraîchement ouvert.",
    variantes: {
      LEAN: "180 g de thon, 150 g de pommes de terre et seulement trois olives.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute 120 g de pommes de terre et un fruit.",
      MASS: "Ajoute pommes de terre, huile d'olive et pain complet.",
    },
    ingredients: ["150 g de thon au naturel égoutté", "220 g de pommes de terre grenaille", "150 g de haricots verts", "1 œuf", "120 g de tomates cerises", "30 g d'olives noires", "60 g de laitue", "10 g d'huile d'olive", "1 c. à café de moutarde", "Citron et poivre"],
    etapes: ["Cuire les pommes de terre, les haricots verts et l'œuf, puis laisser refroidir.", "Égoutter le thon et couper les tomates, l'œuf et les pommes de terre.", "Mélanger huile, moutarde et citron, puis composer la salade et ajouter la vinaigrette au service."],
  },
  {
    slug: "sandwich-roast-beef-moutarde-salade",
    nom: "Sandwich roast-beef, moutarde et salade",
    description: "Un sandwich complet riche en protéines avec roast-beef maigre et sauce moutarde au yaourt.",
    photoQuery: "wholegrain roast beef mustard arugula tomato sandwich",
    photoLocale: "/repas/dejeuner-sandwich-roast-beef-moutarde.jpg",
    typeRepas: "DEJEUNER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: [],
    tempsMinutes: 12,
    macros: { calories: 595, proteines: 50, glucides: 55, lipides: 19 },
    portion: "1 grand sandwich",
    allergenes: ["Gluten", "Lait", "Moutarde"],
    conservation: "À consommer dans les 12 heures au réfrigérateur ; conserver la sauce séparément pour garder le pain ferme.",
    variantes: {
      LEAN: "80 g de pain, 180 g de roast-beef et davantage de salade.",
      RESET_TRX: "Version de base.",
      HYBRID: "Ajoute un fruit et un yaourt après la séance.",
      MASS: "Ajoute pain, roast-beef, huile d'olive et fromage affiné.",
    },
    ingredients: ["100 g de pain complet tranché", "150 g de roast-beef maigre", "80 g de tomate", "60 g de concombre", "40 g de roquette", "70 g de yaourt grec", "1 c. à café de moutarde à l'ancienne", "Poivre"],
    etapes: ["Mélanger le yaourt, la moutarde et le poivre.", "Tartiner le pain puis répartir roast-beef, tomate, concombre et roquette.", "Refermer, presser légèrement et couper en deux."],
  },
  {
    slug: "poulet-tikka-riz-chou-fleur",
    nom: "Poulet tikka, riz et chou-fleur rôti",
    description: "Un tikka léger à base de tomate et yaourt, servi avec riz basmati et chou-fleur rôti.",
    photoQuery: "light chicken tikka basmati rice roasted cauliflower",
    photoLocale: "/repas/diner-poulet-tikka-riz-chou-fleur.jpg",
    typeRepas: "DINER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["SANS_GLUTEN"],
    tempsMinutes: 40,
    macros: { calories: 665, proteines: 55, glucides: 75, lipides: 15 },
    portion: "1 grande assiette",
    allergenes: ["Lait"],
    conservation: "3 jours au réfrigérateur ou 2 mois au congélateur ; réchauffer à cœur.",
    variantes: { LEAN: "50 g de riz sec, 180 g de poulet et davantage de chou-fleur.", RESET_TRX: "Version de base.", HYBRID: "Ajoute 30 g de riz sec les jours intenses.", MASS: "Ajoute riz, yaourt entier et noix de cajou." },
    ingredients: ["160 g de blanc de poulet", "70 g de riz basmati, poids sec", "250 g de chou-fleur", "150 g de tomates concassées", "100 g de yaourt grec", "1 petit oignon", "Garam masala, gingembre, ail et coriandre"],
    etapes: ["Mariner le poulet dans la moitié du yaourt et les épices, puis le saisir.", "Rôtir le chou-fleur 25 minutes à 200°C et cuire le riz.", "Cuire oignon, tomate et épices, ajouter poulet et reste de yaourt hors feu, puis servir."],
  },
  {
    slug: "colin-four-ratatouille-pommes-terre",
    nom: "Colin au four, ratatouille et pommes de terre",
    description: "Un dîner méditerranéen complet avec poisson blanc, légumes mijotés et grenailles rôties.",
    photoQuery: "baked pollock ratatouille roasted baby potatoes",
    photoLocale: "/repas/diner-colin-ratatouille-pommes-terre.jpg",
    typeRepas: "DINER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["SANS_GLUTEN", "ANTI_INFLAMMATOIRE"],
    tempsMinutes: 45,
    macros: { calories: 610, proteines: 46, glucides: 61, lipides: 18 },
    portion: "1 grande assiette",
    allergenes: ["Poisson"],
    conservation: "2 jours au réfrigérateur ; ratatouille et pommes de terre se congèlent 2 mois, poisson de préférence frais.",
    variantes: { LEAN: "220 g de colin, 180 g de pommes de terre et double ratatouille.", RESET_TRX: "Version de base.", HYBRID: "Ajoute 120 g de pommes de terre.", MASS: "Ajoute pommes de terre, huile d'olive et pain complet." },
    ingredients: ["200 g de filet de colin", "250 g de pommes de terre grenaille", "100 g de courgette", "100 g d'aubergine", "100 g de poivron rouge", "150 g de tomate", "10 g d'huile d'olive", "Citron, thym et persil"],
    etapes: ["Rôtir les pommes de terre avec la moitié de l'huile 30 minutes à 200°C.", "Mijoter courgette, aubergine, poivron et tomate avec thym.", "Cuire le colin au four 12 à 15 minutes, puis servir avec citron et persil."],
  },
  {
    slug: "boulettes-dinde-tomate-pates",
    nom: "Boulettes de dinde, tomate et pâtes complètes",
    description: "Des boulettes maigres dans une sauce tomate maison avec spaghetti complets.",
    photoQuery: "turkey meatballs tomato sauce wholegrain spaghetti",
    photoLocale: "/repas/diner-boulettes-dinde-tomate-pates.jpg",
    typeRepas: "DINER",
    objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: [],
    tempsMinutes: 40,
    macros: { calories: 690, proteines: 55, glucides: 76, lipides: 18 },
    portion: "4 boulettes avec pâtes",
    allergenes: ["Gluten", "Œufs"],
    conservation: "3 jours au réfrigérateur ou 2 mois au congélateur pour les boulettes et la sauce.",
    variantes: { LEAN: "60 g de pâtes sèches, 200 g de dinde et davantage de sauce tomate.", RESET_TRX: "Version de base.", HYBRID: "Ajoute 30 g de pâtes sèches.", MASS: "Ajoute pâtes, huile d'olive et parmesan." },
    ingredients: ["180 g de dinde hachée", "80 g de spaghetti complets, poids sec", "250 g de tomates concassées", "1/2 œuf battu", "15 g de chapelure complète", "1 petit oignon", "Ail, basilic et origan"],
    etapes: ["Mélanger dinde, œuf, chapelure et herbes, puis former quatre boulettes.", "Dorer les boulettes et les mijoter 15 minutes dans la tomate avec oignon et ail.", "Cuire les pâtes al dente et servir avec la sauce et le basilic."],
  },
  {
    slug: "lasagnes-courgette-boeuf",
    nom: "Lasagnes courgette et bœuf",
    description: "Des lasagnes riches en légumes, au bœuf maigre et avec une couche de fromage mesurée.",
    photoQuery: "zucchini lean beef wholegrain lasagna",
    photoLocale: "/repas/diner-lasagnes-courgette-boeuf.jpg",
    typeRepas: "DINER",
    objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: [],
    tempsMinutes: 60,
    macros: { calories: 725, proteines: 53, glucides: 65, lipides: 28 },
    portion: "1 grande part",
    allergenes: ["Gluten", "Lait"],
    conservation: "3 jours au réfrigérateur ou 2 mois au congélateur en parts individuelles.",
    variantes: { LEAN: "Deux couches de pâtes, 180 g de bœuf 5 % et davantage de courgette.", RESET_TRX: "Version de base.", HYBRID: "Ajoute une couche de pâtes et une salade.", MASS: "Ajoute pâtes, mozzarella et huile d'olive." },
    ingredients: ["150 g de bœuf haché 5 %", "60 g de feuilles de lasagnes complètes", "250 g de courgette", "250 g de tomates concassées", "50 g de mozzarella", "1 petit oignon", "Ail, basilic et origan"],
    etapes: ["Faire revenir bœuf, oignon et ail, puis ajouter tomate et herbes.", "Tailler la courgette en rubans et monter les couches avec pâtes, courgette et sauce.", "Terminer par la mozzarella et cuire 35 à 40 minutes à 190°C."],
  },
  {
    slug: "curry-vert-tofu-legumes",
    nom: "Curry vert de tofu et légumes",
    description: "Un curry thaï végétarien léger en lait de coco, servi avec une portion de riz jasmin.",
    photoQuery: "Thai green tofu vegetable curry jasmine rice",
    photoLocale: "/repas/diner-curry-vert-tofu-legumes.jpg",
    typeRepas: "DINER",
    objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"],
    regimes: ["VEGETARIEN", "SANS_GLUTEN"],
    tempsMinutes: 30,
    macros: { calories: 655, proteines: 32, glucides: 76, lipides: 25 },
    portion: "1 grand bowl",
    allergenes: ["Soja"],
    conservation: "3 jours au réfrigérateur ou 2 mois au congélateur ; conserver le riz séparément.",
    variantes: { LEAN: "45 g de riz sec, 220 g de tofu et lait de coco allégé.", RESET_TRX: "Version de base.", HYBRID: "Ajoute 30 g de riz sec.", MASS: "Ajoute riz, tofu et lait de coco entier." },
    ingredients: ["200 g de tofu ferme", "60 g de riz jasmin, poids sec", "100 ml de lait de coco allégé", "100 g de brocoli", "80 g de courgette", "80 g de haricots verts", "60 g de poivron rouge", "1 c. à soupe de pâte de curry vert", "Basilic et citron vert"],
    etapes: ["Dorer les cubes de tofu et cuire le riz.", "Sauter les légumes, ajouter pâte de curry et lait de coco puis mijoter 8 minutes.", "Remettre le tofu, terminer avec basilic et citron vert, puis servir avec le riz."],
  },
];

RECETTES.push(...RECETTES_EXTENSION);
RECETTES.push(...RECETTES_V6);

export function filtrerRecettes(recettes: Recette[], filtres: { typeRepas?: TypeRepas; objectif?: ObjectifRecette; regime?: RegimeRecette }) {
  return recettes.filter((r) => {
    if (filtres.typeRepas && r.typeRepas !== filtres.typeRepas) return false;
    if (filtres.objectif && !r.objectifs.includes(filtres.objectif)) return false;
    if (filtres.regime && !r.regimes.includes(filtres.regime)) return false;
    return true;
  });
}

export const TYPE_REPAS_LABEL: Record<TypeRepas, string> = {
  PETIT_DEJEUNER: "Petit-déjeuner",
  DEJEUNER: "Déjeuner",
  DINER: "Dîner",
  COLLATION: "Collation",
};

export const OBJECTIF_RECETTE_LABEL: Record<ObjectifRecette, string> = {
  PERTE_DE_POIDS: "Perte de poids",
  PRISE_DE_MASSE: "Prise de masse",
  EQUILIBRE: "Équilibre",
};

export const REGIME_LABEL: Record<RegimeRecette, string> = {
  VEGETARIEN: "Végétarien",
  SANS_GLUTEN: "Sans gluten",
  ANTI_INFLAMMATOIRE: "Anti-inflammatoire",
};
