import type { Recette } from "./recettes";

// Série CoAI v7 — recettes végétales ou végétariennes, sans gluten et riches en protéines.
// Les macros sont des estimations indicatives pour une portion.
type BaseRecette = Omit<Recette, "photoQuery" | "conservation" | "variantes">;

const conservation = "À conserver jusqu’à 3 jours au réfrigérateur dans une boîte hermétique.";

const variantes: NonNullable<Recette["variantes"]> = {
  LEAN: "Réduis de 15 % la portion de féculents et augmente les légumes.",
  RESET_TRX: "Garde la portion indiquée et ajoute une crudité selon la faim.",
  HYBRID: "Ajoute 25 à 30 g de féculents secs après une séance longue.",
  MASS: "Ajoute une portion de féculents et 1 c. à café d’huile d’olive.",
};

const base: BaseRecette[] = [
  { slug: "bowl-tofu-quinoa-coai", nom: "Bowl tofu, quinoa et edamame", description: "Un bowl végétal complet, coloré et généreux en protéines.", photoLocale: "/repas/bowl-tofu-quinoa-vegan-sans-gluten-v1.png", typeRepas: "DEJEUNER", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN", "SANS_GLUTEN", "ANTI_INFLAMMATOIRE"], tempsMinutes: 25, macros: { calories: 650, proteines: 38, glucides: 61, lipides: 29 }, portion: "1 grand bowl", allergenes: ["Soja", "Sésame"], ingredients: ["180 g de tofu ferme", "120 g de quinoa cuit", "100 g d’edamame", "Brocoli et chou rouge", "1/2 avocat", "15 g de tahini", "Citron vert"], etapes: ["Griller le tofu et le brocoli 12 minutes.", "Disposer le quinoa, les edamame et les crudités dans un bowl.", "Ajouter l’avocat et napper de tahini citronné."] },
  { slug: "pates-lentilles-tempeh", nom: "Pâtes de lentilles au tempeh", description: "Des pâtes de légumineuses avec une sauce tomate crémeuse et du tempeh doré.", photoLocale: "/repas/pates-lentilles-tempeh-vegan-sans-gluten-v1.png", typeRepas: "DINER", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 25, macros: { calories: 610, proteines: 42, glucides: 70, lipides: 19 }, portion: "1 assiette", allergenes: ["Soja"], ingredients: ["90 g de pâtes de lentilles corail", "120 g de tempeh certifié sans gluten", "150 g de passata", "Épinards", "Champignons", "Ail et basilic"], etapes: ["Cuire les pâtes selon le paquet.", "Dorer le tempeh et les champignons.", "Ajouter passata et épinards, puis mélanger avec les pâtes."] },
  { slug: "mousse-chocolat-tofu-framboise", nom: "Mousse chocolat au tofu et framboises", description: "Une crème chocolatée végétale, onctueuse et naturellement protéinée.", photoLocale: "/repas/mousse-chocolat-tofu-vegan-sans-gluten-v1.png", typeRepas: "COLLATION", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 8, macros: { calories: 390, proteines: 25, glucides: 29, lipides: 22 }, portion: "1 bowl", allergenes: ["Soja", "Fruits à coque"], ingredients: ["250 g de tofu soyeux", "20 g de cacao non sucré", "15 g de sirop d’érable", "100 g de framboises", "10 g de chia", "15 g de pistaches", "10 g de purée d’amande"], etapes: ["Mixer tofu, cacao et sirop jusqu’à obtenir une crème lisse.", "Réserver 2 heures au frais.", "Ajouter framboises, chia, pistaches et purée d’amande."] },
  { slug: "pancakes-pois-chiches-sales", nom: "Pancakes salés de pois chiches", description: "Des pancakes végétaux moelleux avec avocat et sauce tofu aux herbes.", photoLocale: "/repas/pancakes-pois-chiches-vegan-sans-gluten-v1.png", typeRepas: "PETIT_DEJEUNER", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 20, macros: { calories: 520, proteines: 32, glucides: 48, lipides: 24 }, portion: "4 pancakes", allergenes: ["Soja"], ingredients: ["100 g de farine de pois chiches", "160 ml d’eau", "100 g de tofu soyeux", "Épinards", "1/2 avocat", "Tomates cerises", "Citron et herbes"], etapes: ["Fouetter la farine de pois chiches avec l’eau et les épinards.", "Cuire quatre pancakes dans une poêle antiadhésive.", "Mixer tofu, citron et herbes puis dresser avec avocat et tomates."] },
  { slug: "curry-lentilles-tofu-fume", nom: "Curry de lentilles au tofu fumé", description: "Un curry végétal réconfortant aux épinards et au chou-fleur.", photoLocale: "/repas/curry-lentilles-tofu-vegan-sans-gluten-v1.png", typeRepas: "DINER", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN", "SANS_GLUTEN", "ANTI_INFLAMMATOIRE"], tempsMinutes: 30, macros: { calories: 640, proteines: 39, glucides: 76, lipides: 20 }, portion: "1 grand bowl", allergenes: ["Soja"], ingredients: ["180 g de lentilles corail cuites", "160 g de tofu fumé", "100 g de riz basmati cuit", "Épinards", "Chou-fleur", "Tomate", "Curry et gingembre"], etapes: ["Mijoter lentilles, tomate et épices 15 minutes.", "Rôtir le chou-fleur et dorer le tofu.", "Ajouter les épinards puis servir avec le riz, le tofu et le chou-fleur."] },
  { slug: "bowl-mexicain-tofu-quinoa", nom: "Bowl mexicain au tofu", description: "Un bowl frais aux haricots noirs, quinoa et tofu grillé.", photoLocale: "/repas/bowl-mexicain-tofu-vegan-sans-gluten-v1.png", typeRepas: "DEJEUNER", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 25, macros: { calories: 690, proteines: 40, glucides: 78, lipides: 25 }, portion: "1 grand bowl", allergenes: ["Soja"], ingredients: ["160 g de tofu", "150 g de haricots noirs", "100 g de quinoa cuit", "Maïs", "Salsa tomate", "Laitue", "1/2 avocat", "Citron vert"], etapes: ["Griller le tofu avec paprika et cumin.", "Réchauffer les haricots, le quinoa et le maïs.", "Assembler avec laitue, salsa, avocat et citron vert."] },
  { slug: "chia-mangue-creme-soja", nom: "Chia mangue et crème de soja", description: "Un pudding tropical frais, riche en protéines végétales et en fibres.", photoLocale: "/repas/chia-mangue-soja-vegan-sans-gluten-v1.png", typeRepas: "PETIT_DEJEUNER", objectifs: ["EQUILIBRE", "PERTE_DE_POIDS"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 8, macros: { calories: 430, proteines: 27, glucides: 40, lipides: 20 }, portion: "1 bowl", allergenes: ["Soja"], ingredients: ["30 g de chia", "200 ml de boisson au soja", "180 g de spécialité fermentée au soja enrichie en protéines", "120 g de mangue", "1 fruit de la passion", "15 g de graines de chanvre", "10 g de coco"], etapes: ["Mélanger chia et boisson au soja.", "Réserver une nuit au réfrigérateur.", "Ajouter la spécialité au soja, les fruits, le chanvre et la coco."] },
  { slug: "poivrons-farcis-soja-quinoa", nom: "Poivrons farcis au soja et quinoa", description: "Des poivrons généreusement farcis de soja texturé, quinoa et haricots noirs.", photoLocale: "/repas/poivrons-farcis-soja-vegan-sans-gluten-v1.png", typeRepas: "DINER", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 40, macros: { calories: 560, proteines: 36, glucides: 72, lipides: 14 }, portion: "2 demi-poivrons", allergenes: ["Soja"], ingredients: ["1 grand poivron", "60 g de protéines de soja texturées certifiées sans gluten", "100 g de quinoa cuit", "100 g de haricots noirs", "Tomate", "Cumin et coriandre"], etapes: ["Réhydrater les protéines de soja.", "Mélanger avec quinoa, haricots, tomate et épices.", "Garnir les poivrons et cuire 30 minutes à 190°C."] },
  { slug: "omelette-cottage-epinards", nom: "Omelette cottage et épinards", description: "Une omelette généreuse aux épinards, accompagnée d’une salade fraîche.", photoLocale: "/repas/omelette-cottage-epinards-vegetarienne-sans-gluten-v1.png", typeRepas: "PETIT_DEJEUNER", objectifs: ["EQUILIBRE", "PERTE_DE_POIDS"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 15, macros: { calories: 480, proteines: 41, glucides: 14, lipides: 29 }, portion: "1 omelette", allergenes: ["Œufs", "Lait"], ingredients: ["3 œufs", "150 g de cottage cheese", "100 g d’épinards", "Herbes fraîches", "Tomates cerises", "Roquette"], etapes: ["Faire tomber les épinards à la poêle.", "Verser les œufs battus et cuire à feu doux.", "Garnir de cottage, plier et servir avec tomates et roquette."] },
  { slug: "patate-douce-cottage-haricots", nom: "Patate douce au cottage et haricots", description: "Une patate douce rôtie et généreusement garnie pour un repas complet.", photoLocale: "/repas/patate-douce-cottage-haricots-vegetarienne-sans-gluten-v1.png", typeRepas: "DEJEUNER", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 50, macros: { calories: 590, proteines: 35, glucides: 74, lipides: 19 }, portion: "1 grande patate douce", allergenes: ["Lait"], ingredients: ["1 grande patate douce", "200 g de cottage cheese", "120 g de haricots noirs", "Maïs", "1/2 avocat", "Coriandre et citron vert"], etapes: ["Cuire la patate douce 45 minutes à 200°C.", "L’ouvrir sans séparer les deux moitiés.", "Garnir de cottage, haricots, maïs, avocat et coriandre."] },
  { slug: "skyr-myrtilles-sarrasin", nom: "Skyr aux myrtilles et sarrasin", description: "Un bowl frais et croquant, parfait au petit-déjeuner ou en collation.", photoLocale: "/repas/skyr-myrtilles-sarrasin-vegetarien-sans-gluten-v1.png", typeRepas: "PETIT_DEJEUNER", objectifs: ["EQUILIBRE", "PERTE_DE_POIDS"], regimes: ["VEGETARIEN", "SANS_GLUTEN", "ANTI_INFLAMMATOIRE"], tempsMinutes: 10, macros: { calories: 430, proteines: 32, glucides: 46, lipides: 14 }, portion: "1 bowl", allergenes: ["Lait", "Fruits à coque"], ingredients: ["300 g de skyr", "100 g de myrtilles", "30 g de sarrasin grillé", "15 g d’amandes", "Zeste de citron"], etapes: ["Compoter brièvement la moitié des myrtilles.", "Verser le skyr dans un bowl.", "Ajouter compotée, fruits frais, sarrasin, amandes et citron."] },
  { slug: "shakshuka-proteinee-pois-chiches", nom: "Shakshuka protéinée aux pois chiches", description: "Des œufs mijotés avec tomate, poivron, pois chiches et feta.", photoLocale: "/repas/shakshuka-proteinee-vegetarienne-sans-gluten-v1.png", typeRepas: "DEJEUNER", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 30, macros: { calories: 540, proteines: 36, glucides: 42, lipides: 25 }, portion: "1 poêle individuelle", allergenes: ["Œufs", "Lait"], ingredients: ["3 œufs", "120 g de pois chiches", "60 g de feta", "250 g de tomates concassées", "1/2 poivron", "Oignon", "Paprika et persil"], etapes: ["Mijoter tomate, poivron, oignon et paprika 15 minutes.", "Ajouter les pois chiches et creuser trois puits.", "Cuire les œufs à couvert puis parsemer de feta et persil."] },
  { slug: "gratin-quinoa-brocoli-cottage", nom: "Gratin quinoa, brocoli et cottage", description: "Un gratin végétarien complet, crémeux et riche en légumes.", photoLocale: "/repas/gratin-quinoa-brocoli-vegetarien-sans-gluten-v1.png", typeRepas: "DINER", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 35, macros: { calories: 570, proteines: 39, glucides: 45, lipides: 26 }, portion: "1 plat individuel", allergenes: ["Œufs", "Lait"], ingredients: ["150 g de quinoa cuit", "200 g de cottage cheese", "2 œufs", "200 g de brocoli", "40 g de fromage râpé", "Muscade"], etapes: ["Cuire le brocoli à la vapeur.", "Mélanger quinoa, cottage, œufs, brocoli et muscade.", "Couvrir légèrement de fromage et cuire 25 minutes à 190°C."] },
  { slug: "salade-halloumi-lentilles", nom: "Salade halloumi et lentilles", description: "Une salade tiède aux légumes rôtis, halloumi grillé et grenade.", photoLocale: "/repas/salade-halloumi-lentilles-vegetarienne-sans-gluten-v1.png", typeRepas: "DEJEUNER", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN", "SANS_GLUTEN", "ANTI_INFLAMMATOIRE"], tempsMinutes: 25, macros: { calories: 620, proteines: 38, glucides: 50, lipides: 30 }, portion: "1 grande salade", allergenes: ["Lait"], ingredients: ["120 g de halloumi", "180 g de lentilles cuites", "200 g de légumes à rôtir", "Roquette", "Grenade", "Citron", "1 c. à café d’huile d’olive"], etapes: ["Rôtir les légumes et griller le halloumi.", "Mélanger lentilles, roquette, citron et huile.", "Ajouter légumes, halloumi et grenade."] },
  { slug: "gaufres-skyr-fraises", nom: "Gaufres protéinées au skyr", description: "Des gaufres moelleuses aux fraises et à la purée d’amande.", photoLocale: "/repas/gaufres-skyr-vegetariennes-sans-gluten-v1.png", typeRepas: "PETIT_DEJEUNER", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 20, macros: { calories: 510, proteines: 37, glucides: 52, lipides: 18 }, portion: "2 gaufres", allergenes: ["Œufs", "Lait", "Fruits à coque"], ingredients: ["2 œufs", "200 g de skyr", "60 g de farine d’avoine certifiée sans gluten", "Levure sans gluten", "120 g de fraises", "15 g de purée d’amande"], etapes: ["Mixer les œufs, 150 g de skyr, la farine et la levure.", "Cuire la pâte dans un gaufrier chaud.", "Servir avec le reste de skyr, les fraises et la purée d’amande."] },
  { slug: "lasagnes-courgettes-ricotta", nom: "Lasagnes de courgettes à la ricotta", description: "Des lasagnes sans pâtes, riches en légumes et en protéines laitières.", photoLocale: "/repas/lasagnes-courgettes-vegetariennes-sans-gluten-v1.png", typeRepas: "DINER", objectifs: ["EQUILIBRE", "PERTE_DE_POIDS"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 50, macros: { calories: 520, proteines: 44, glucides: 30, lipides: 26 }, portion: "1 grande part", allergenes: ["Lait"], ingredients: ["2 courgettes", "150 g de ricotta", "200 g de cottage cheese", "100 g d’épinards", "180 g de sauce tomate", "30 g de mozzarella"], etapes: ["Tailler les courgettes en rubans, les saler puis les griller.", "Monter les couches avec courgettes, fromages, épinards et tomate.", "Cuire 30 minutes à 190°C et laisser reposer 10 minutes."] },
];

export const RECETTES_V7: Recette[] = base.map((recette) => ({
  ...recette,
  photoQuery: recette.nom,
  conservation,
  variantes,
}));
