import type { Recette } from "./recettes";

// Série Diet COAI — 50 recettes inédites avec visuels HD dédiés.
// Les macros sont des estimations indicatives pour une portion et servent de repères.
type BaseRecette = Omit<Recette, "photoQuery" | "conservation" | "variantes">;

const variantes: NonNullable<Recette["variantes"]> = {
  LEAN: "Réduis de 15 % la portion de féculents et ajoute des légumes.",
  RESET_TRX: "Garde la portion indiquée et ajoute une crudité si la faim revient.",
  HYBRID: "Ajoute 25 à 30 g de féculents secs après une séance longue.",
  MASS: "Ajoute une portion de féculents et 1 c. à café d'huile d'olive.",
};

const conservation = "À conserver 3 jours au réfrigérateur dans une boîte hermétique ; congélation possible si précisé.";

const base: BaseRecette[] = [
  { slug: "overnight-oats-poire-cannelle", nom: "Overnight oats poire et cannelle", description: "Un petit-déjeuner préparé la veille, crémeux et riche en fibres.", photoLocale: "/repas/overnight-oats-poire-cannelle.png", typeRepas: "PETIT_DEJEUNER", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["VEGETARIEN"], tempsMinutes: 8, macros: { calories: 390, proteines: 20, glucides: 54, lipides: 11 }, portion: "1 bocal", allergenes: ["Gluten", "Lait", "Fruits à coque"], ingredients: ["50 g de flocons d'avoine", "150 g de skyr", "1 poire", "100 ml de lait", "Cannelle et 10 g de noix"], etapes: ["Mélanger avoine, skyr et lait dans un bocal.", "Ajouter la poire en dés et la cannelle.", "Réserver une nuit au frais puis parsemer de noix." ] },
  { slug: "saumon-quinoa-asperges", nom: "Saumon, quinoa et asperges", description: "Une assiette complète avec oméga-3, quinoa et légumes verts.", photoLocale: "/repas/saumon-quinoa-asperges.png", typeRepas: "DEJEUNER", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["SANS_GLUTEN", "ANTI_INFLAMMATOIRE"], tempsMinutes: 25, macros: { calories: 610, proteines: 42, glucides: 53, lipides: 25 }, portion: "1 assiette", allergenes: ["Poisson"], ingredients: ["160 g de saumon", "70 g de quinoa sec", "180 g d'asperges", "1 c. à café d'huile d'olive", "Citron, aneth et poivre"], etapes: ["Cuire le quinoa puis l'égoutter.", "Rôtir les asperges 12 minutes avec l'huile.", "Cuire le saumon à la poêle et servir avec citron et aneth." ] },
  { slug: "soba-tofu-edamame", nom: "Nouilles soba, tofu et edamame", description: "Un bowl végétarien riche en protéines végétales et prêt en 20 minutes.", photoLocale: "/repas/soba-tofu-edamame.png", typeRepas: "DEJEUNER", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN"], tempsMinutes: 20, macros: { calories: 570, proteines: 29, glucides: 73, lipides: 18 }, portion: "1 bowl", allergenes: ["Gluten", "Soja", "Sésame"], ingredients: ["80 g de soba", "180 g de tofu ferme", "100 g d'edamame", "1 carotte", "Sauce soja, citron vert et sésame"], etapes: ["Cuire les soba et les rincer à l'eau froide.", "Dorer le tofu en cubes avec la sauce soja.", "Assembler avec carotte, edamame, citron vert et sésame." ] },
  { slug: "bowl-poulet-haricots-mais", nom: "Bowl poulet, haricots noirs et maïs", description: "Un bowl coloré et rassasiant, idéal pour le batch cooking.", photoLocale: "/repas/bowl-poulet-haricots-mais.png", typeRepas: "DEJEUNER", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["SANS_GLUTEN"], tempsMinutes: 25, macros: { calories: 585, proteines: 45, glucides: 67, lipides: 13 }, portion: "1 bowl", allergenes: [], ingredients: ["150 g de poulet", "60 g de riz sec", "100 g de haricots noirs cuits", "80 g de maïs", "Tomate, citron vert et coriandre"], etapes: ["Cuire le riz et égoutter les haricots.", "Griller le poulet avec paprika et cumin.", "Réunir riz, poulet, maïs, haricots et salsa tomate." ] },
  { slug: "porridge-proteine-banane", nom: "Porridge protéiné banane-amande", description: "Un porridge chaud et réconfortant pour soutenir la récupération.", photoLocale: "/repas/porridge-proteine-banane.png", typeRepas: "PETIT_DEJEUNER", objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"], regimes: ["VEGETARIEN"], tempsMinutes: 10, macros: { calories: 475, proteines: 30, glucides: 61, lipides: 13 }, portion: "1 bol", allergenes: ["Gluten", "Lait", "Fruits à coque"], ingredients: ["60 g d'avoine", "200 ml de lait", "25 g de whey ou protéine végétale", "1 banane", "10 g de purée d'amande"], etapes: ["Cuire l'avoine dans le lait 5 minutes.", "Hors du feu, incorporer la protéine.", "Ajouter banane et purée d'amande avant de servir." ] },
  { slug: "tartine-avocat-oeuf", nom: "Tartine avocat et œuf mollet", description: "Une tartine équilibrée, rapide et riche en bons lipides.", photoLocale: "/repas/tartine-avocat-oeuf.png", typeRepas: "PETIT_DEJEUNER", objectifs: ["EQUILIBRE", "PERTE_DE_POIDS"], regimes: ["VEGETARIEN"], tempsMinutes: 12, macros: { calories: 410, proteines: 20, glucides: 38, lipides: 22 }, portion: "2 tartines", allergenes: ["Gluten", "Œufs"], ingredients: ["2 tranches de pain complet", "1/2 avocat", "2 œufs", "Tomates cerises", "Citron, piment et graines de courge"], etapes: ["Cuire les œufs 6 minutes puis les refroidir.", "Écraser l'avocat avec citron et piment.", "Tartiner le pain, ajouter œuf, tomates et graines." ] },
  { slug: "pancakes-skyr-myrtilles", nom: "Pancakes au skyr et myrtilles", description: "Des pancakes moelleux et protéinés sans sucre ajouté.", photoLocale: "/repas/pancakes-skyr-myrtilles.png", typeRepas: "PETIT_DEJEUNER", objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"], regimes: ["VEGETARIEN"], tempsMinutes: 15, macros: { calories: 430, proteines: 28, glucides: 55, lipides: 11 }, portion: "1 pile", allergenes: ["Gluten", "Lait", "Œufs"], ingredients: ["50 g de farine d'avoine", "1 œuf", "120 g de skyr", "80 g de myrtilles", "Levure et vanille"], etapes: ["Fouetter œuf, skyr et vanille.", "Ajouter farine et levure puis laisser reposer 5 minutes.", "Cuire les pancakes à feu moyen et servir avec les myrtilles." ] },
  { slug: "chia-pudding-framboise", nom: "Chia pudding coco-framboise", description: "Une collation fraîche et riche en fibres, préparée en quelques minutes.", photoLocale: "/repas/chia-pudding-framboise.png", typeRepas: "PETIT_DEJEUNER", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 5, macros: { calories: 320, proteines: 14, glucides: 32, lipides: 16 }, portion: "1 verrine", allergenes: [], ingredients: ["25 g de graines de chia", "180 ml de boisson coco", "100 g de framboises", "100 g de skyr", "Vanille et zeste de citron"], etapes: ["Mélanger chia, boisson coco et vanille.", "Réfrigérer au moins 4 heures.", "Ajouter skyr, framboises et zeste au moment de servir." ] },
  { slug: "burrito-oeufs-haricots", nom: "Burrito œufs et haricots rouges", description: "Un burrito salé riche en protéines pour un matin actif.", photoLocale: "/repas/burrito-oeufs-haricots.png", typeRepas: "PETIT_DEJEUNER", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: [], tempsMinutes: 15, macros: { calories: 510, proteines: 29, glucides: 55, lipides: 19 }, portion: "1 burrito", allergenes: ["Gluten", "Œufs", "Lait"], ingredients: ["1 grande tortilla complète", "2 œufs", "80 g de haricots rouges", "30 g de cheddar", "Poivron, salsa et coriandre"], etapes: ["Faire revenir le poivron puis ajouter les œufs battus.", "Réchauffer les haricots et la tortilla.", "Garnir, ajouter cheddar et salsa puis rouler." ] },
  { slug: "toast-cottage-tomates", nom: "Toast cottage cheese et tomates", description: "Un toast frais, simple et riche en protéines.", photoLocale: "/repas/toast-cottage-tomates.png", typeRepas: "PETIT_DEJEUNER", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["VEGETARIEN"], tempsMinutes: 8, macros: { calories: 300, proteines: 22, glucides: 33, lipides: 9 }, portion: "2 toasts", allergenes: ["Gluten", "Lait"], ingredients: ["2 tranches de pain au levain", "120 g de cottage cheese", "1 tomate", "Basilic", "Poivre et filet d'huile d'olive"], etapes: ["Toaster le pain.", "Étaler le cottage cheese et poivrer.", "Ajouter tomate, basilic et un filet d'huile." ] },
  { slug: "bowl-yaourt-mangue-graines", nom: "Bowl yaourt, mangue et graines", description: "Un bowl fruité avec croquant de graines et protéines laitières.", photoLocale: "/repas/bowl-yaourt-mangue-graines.png", typeRepas: "PETIT_DEJEUNER", objectifs: ["EQUILIBRE", "PERTE_DE_POIDS"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 7, macros: { calories: 360, proteines: 23, glucides: 45, lipides: 10 }, portion: "1 bowl", allergenes: ["Lait", "Fruits à coque"], ingredients: ["200 g de yaourt grec", "120 g de mangue", "20 g de graines de courge", "15 g de noix de coco", "Citron vert"], etapes: ["Verser le yaourt dans un bowl.", "Ajouter la mangue en dés.", "Parsemer de graines, coco et zeste de citron vert." ] },
  { slug: "shakshuka-feta", nom: "Shakshuka tomate, poivron et feta", description: "Des œufs mijotés dans une sauce tomate épicée, prêts en une seule poêle.", photoLocale: "/repas/shakshuka-feta.png", typeRepas: "DEJEUNER", objectifs: ["EQUILIBRE", "PERTE_DE_POIDS"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 25, macros: { calories: 440, proteines: 27, glucides: 31, lipides: 23 }, portion: "1 poêle", allergenes: ["Œufs", "Lait"], ingredients: ["2 œufs", "250 g de tomates concassées", "1 poivron", "40 g de feta", "Oignon, paprika fumé et cumin"], etapes: ["Faire fondre oignon et poivron avec les épices.", "Ajouter les tomates et mijoter 12 minutes.", "Casser les œufs, couvrir puis finir avec la feta." ] },
  { slug: "salade-poulet-patate-douce", nom: "Salade poulet, patate douce et roquette", description: "Une salade complète qui se transporte facilement au bureau.", photoLocale: "/repas/salade-poulet-patate-douce.png", typeRepas: "DEJEUNER", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["SANS_GLUTEN"], tempsMinutes: 30, macros: { calories: 520, proteines: 43, glucides: 48, lipides: 16 }, portion: "1 grande salade", allergenes: [], ingredients: ["150 g de poulet", "220 g de patate douce", "70 g de roquette", "1/2 avocat", "Moutarde, citron et huile d'olive"], etapes: ["Rôtir la patate douce en cubes 25 minutes.", "Griller le poulet puis le trancher.", "Mélanger roquette, avocat, patate douce et vinaigrette." ] },
  { slug: "poke-thon-edamame", nom: "Poke thon, riz et edamame", description: "Un poke frais, riche en protéines et en textures croquantes.", photoLocale: "/repas/poke-thon-edamame.png", typeRepas: "DEJEUNER", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["SANS_GLUTEN"], tempsMinutes: 20, macros: { calories: 535, proteines: 39, glucides: 64, lipides: 13 }, portion: "1 bowl", allergenes: ["Poisson", "Soja", "Sésame"], ingredients: ["140 g de thon au naturel", "65 g de riz à sushi sec", "100 g d'edamame", "Concombre et carotte", "Soja sans gluten, gingembre et sésame"], etapes: ["Cuire le riz puis le laisser tiédir.", "Émincer concombre et carotte.", "Assembler avec thon, edamame, sauce soja et sésame." ] },
  { slug: "couscous-pois-chiches-legumes", nom: "Couscous pois chiches et légumes rôtis", description: "Un plat végétarien généreux, parfumé aux épices douces.", photoLocale: "/repas/couscous-pois-chiches-legumes.png", typeRepas: "DEJEUNER", objectifs: ["EQUILIBRE", "PERTE_DE_POIDS"], regimes: ["VEGETARIEN"], tempsMinutes: 35, macros: { calories: 500, proteines: 20, glucides: 76, lipides: 14 }, portion: "1 assiette", allergenes: ["Gluten"], ingredients: ["70 g de semoule complète", "140 g de pois chiches cuits", "Courgette, carotte et poivron", "1 c. à café d'huile", "Ras el-hanout, citron et persil"], etapes: ["Rôtir les légumes avec huile et épices.", "Réhydrater la semoule avec un bouillon chaud.", "Mélanger pois chiches, légumes, semoule et citron." ] },
  { slug: "crevettes-riz-ananas", nom: "Crevettes, riz et ananas citron vert", description: "Une assiette sucrée-salée légère avec crevettes et légumes croquants.", photoLocale: "/repas/crevettes-riz-ananas.png", typeRepas: "DINER", objectifs: ["EQUILIBRE", "PERTE_DE_POIDS"], regimes: ["SANS_GLUTEN"], tempsMinutes: 25, macros: { calories: 490, proteines: 35, glucides: 68, lipides: 9 }, portion: "1 assiette", allergenes: ["Crustacés"], ingredients: ["170 g de crevettes", "65 g de riz basmati sec", "100 g d'ananas", "Poivron et pois gourmands", "Citron vert, ail et coriandre"], etapes: ["Cuire le riz.", "Sauter poivron et pois gourmands puis ajouter les crevettes.", "Incorporer l'ananas, le citron vert et servir avec le riz." ] },
  { slug: "steak-quinoa-haricots", nom: "Steak, quinoa et haricots verts", description: "Un plat simple et protéiné pour les jours de renforcement.", photoLocale: "/repas/steak-quinoa-haricots.png", typeRepas: "DINER", objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"], regimes: ["SANS_GLUTEN"], tempsMinutes: 25, macros: { calories: 620, proteines: 48, glucides: 53, lipides: 23 }, portion: "1 assiette", allergenes: [], ingredients: ["170 g de steak maigre", "70 g de quinoa sec", "200 g de haricots verts", "1 c. à café d'huile", "Ail, thym et moutarde"], etapes: ["Cuire le quinoa et les haricots verts.", "Saisir le steak selon la cuisson souhaitée.", "Servir avec thym, moutarde et un filet d'huile." ] },
  { slug: "poulet-pesto-boulgour", nom: "Poulet pesto et boulgour", description: "Un plat méditerranéen rapide avec tomates et roquette.", photoLocale: "/repas/poulet-pesto-boulgour.png", typeRepas: "DEJEUNER", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: [], tempsMinutes: 25, macros: { calories: 590, proteines: 46, glucides: 61, lipides: 17 }, portion: "1 assiette", allergenes: ["Gluten", "Fruits à coque", "Lait"], ingredients: ["160 g de poulet", "75 g de boulgour sec", "1 c. à soupe de pesto", "Tomates cerises", "Roquette et citron"], etapes: ["Cuire le boulgour.", "Griller le poulet puis le couper.", "Mélanger boulgour, pesto, tomates, roquette et poulet." ] },
  { slug: "cabillaud-puree-poireaux", nom: "Cabillaud, purée de poireaux et pommes de terre", description: "Un dîner doux et digeste, riche en protéines maigres.", photoLocale: "/repas/cabillaud-puree-poireaux.png", typeRepas: "DINER", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["SANS_GLUTEN"], tempsMinutes: 35, macros: { calories: 470, proteines: 42, glucides: 51, lipides: 11 }, portion: "1 assiette", allergenes: ["Poisson", "Lait"], ingredients: ["170 g de cabillaud", "220 g de pommes de terre", "2 poireaux", "40 ml de lait", "Citron, muscade et persil"], etapes: ["Cuire pommes de terre et poireaux à la vapeur.", "Écraser avec le lait et la muscade.", "Cuire le cabillaud au four 12 minutes puis servir avec citron." ] },
  { slug: "tofu-curry-legumes", nom: "Tofu curry, légumes et riz", description: "Un curry végétarien parfumé, coloré et facile à personnaliser.", photoLocale: "/repas/tofu-curry-legumes.png", typeRepas: "DINER", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 30, macros: { calories: 560, proteines: 29, glucides: 72, lipides: 17 }, portion: "1 bowl", allergenes: ["Soja"], ingredients: ["200 g de tofu", "60 g de riz sec", "Brocoli, courgette et poivron", "100 ml de lait de coco léger", "Curry, gingembre et citron vert"], etapes: ["Cuire le riz.", "Dorer le tofu puis ajouter les légumes et les épices.", "Verser le lait de coco, mijoter 8 minutes et servir." ] },
  { slug: "boulettes-lentilles-tomate", nom: "Boulettes de lentilles, sauce tomate", description: "Des boulettes végétariennes moelleuses avec une sauce tomate maison.", photoLocale: "/repas/boulettes-lentilles-tomate.png", typeRepas: "DINER", objectifs: ["EQUILIBRE", "PERTE_DE_POIDS"], regimes: ["VEGETARIEN"], tempsMinutes: 40, macros: { calories: 510, proteines: 24, glucides: 73, lipides: 13 }, portion: "1 assiette", allergenes: ["Gluten", "Œufs"], ingredients: ["180 g de lentilles cuites", "1 œuf", "40 g de flocons d'avoine", "250 g de coulis de tomate", "Oignon, ail, basilic et paprika"], etapes: ["Mixer lentilles, œuf, avoine et épices.", "Former des boulettes puis cuire au four 20 minutes.", "Réchauffer dans le coulis de tomate et servir avec une salade." ] },
  { slug: "orge-saumon-epinards", nom: "Orge perlé, saumon et épinards", description: "Une assiette fondante qui associe céréale complète et poisson gras.", photoLocale: "/repas/orge-saumon-epinards.png", typeRepas: "DINER", objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"], regimes: ["ANTI_INFLAMMATOIRE"], tempsMinutes: 35, macros: { calories: 640, proteines: 43, glucides: 65, lipides: 23 }, portion: "1 assiette", allergenes: ["Gluten", "Poisson"], ingredients: ["160 g de saumon", "75 g d'orge perlé", "150 g d'épinards", "1 échalote", "Citron, aneth et huile d'olive"], etapes: ["Cuire l'orge dans un bouillon.", "Cuire le saumon au four avec citron et aneth.", "Faire tomber les épinards puis réunir le tout." ] },
  { slug: "poulet-fajitas-poivrons", nom: "Poulet fajitas et poivrons", description: "Une poêlée épicée à servir dans des tortillas ou avec du riz.", photoLocale: "/repas/poulet-fajitas-poivrons.png", typeRepas: "DINER", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: [], tempsMinutes: 25, macros: { calories: 555, proteines: 45, glucides: 54, lipides: 16 }, portion: "2 fajitas", allergenes: ["Gluten"], ingredients: ["160 g de poulet", "2 tortillas complètes", "Poivron rouge et oignon", "80 g de yaourt grec", "Paprika, cumin, citron vert et coriandre"], etapes: ["Émincer et saisir poulet, poivron et oignon avec les épices.", "Réchauffer les tortillas.", "Garnir de yaourt, poulet et coriandre puis rouler." ] },
  { slug: "gnocchis-dinde-courgettes", nom: "Gnocchis de dinde et courgettes", description: "Un plat réconfortant équilibré par une généreuse portion de courgettes.", photoLocale: "/repas/gnocchis-dinde-courgettes.png", typeRepas: "DINER", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: [], tempsMinutes: 25, macros: { calories: 610, proteines: 43, glucides: 76, lipides: 14 }, portion: "1 assiette", allergenes: ["Gluten", "Lait"], ingredients: ["160 g de dinde hachée", "180 g de gnocchis", "1 courgette", "30 g de parmesan", "Tomates concassées, ail et basilic"], etapes: ["Dorer la dinde puis ajouter courgette et ail.", "Ajouter tomates et mijoter 10 minutes.", "Cuire les gnocchis, mélanger et finir avec parmesan." ] },
  { slug: "tempeh-riz-brocoli", nom: "Tempeh, riz et brocoli sésame", description: "Un bowl végétal consistant avec une sauce soja-sésame maison.", photoLocale: "/repas/tempeh-riz-brocoli.png", typeRepas: "DEJEUNER", objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"], regimes: ["VEGETARIEN"], tempsMinutes: 25, macros: { calories: 600, proteines: 31, glucides: 76, lipides: 18 }, portion: "1 bowl", allergenes: ["Soja", "Sésame"], ingredients: ["170 g de tempeh", "70 g de riz complet sec", "200 g de brocoli", "15 ml de sauce soja", "Tahini, citron et gingembre"], etapes: ["Cuire le riz et le brocoli à la vapeur.", "Poêler le tempeh jusqu'à coloration.", "Mélanger tahini, citron, soja et gingembre puis napper." ] },
  { slug: "salade-pates-poulet", nom: "Salade de pâtes au poulet et tomates", description: "Une salade complète à préparer en avance pour les journées chargées.", photoLocale: "/repas/salade-pates-poulet.png", typeRepas: "DEJEUNER", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: [], tempsMinutes: 20, macros: { calories: 575, proteines: 43, glucides: 69, lipides: 14 }, portion: "1 grand saladier", allergenes: ["Gluten", "Lait"], ingredients: ["75 g de pâtes complètes", "150 g de poulet", "Tomates cerises", "30 g de mozzarella", "Basilic et vinaigrette balsamique"], etapes: ["Cuire les pâtes puis les refroidir.", "Griller le poulet et le détailler.", "Mélanger pâtes, poulet, tomates, mozzarella et basilic." ] },
  { slug: "chili-boeuf-quinoa", nom: "Chili de bœuf et quinoa", description: "Un chili riche en fibres et en protéines, parfait après une séance.", photoLocale: "/repas/chili-boeuf-quinoa.png", typeRepas: "DINER", objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"], regimes: ["SANS_GLUTEN"], tempsMinutes: 35, macros: { calories: 650, proteines: 45, glucides: 69, lipides: 19 }, portion: "1 bowl", allergenes: [], ingredients: ["150 g de bœuf 5 %", "60 g de quinoa sec", "120 g de haricots rouges", "Tomates concassées et maïs", "Oignon, cumin et piment doux"], etapes: ["Faire revenir bœuf et oignon.", "Ajouter tomates, haricots, maïs et épices puis mijoter 20 minutes.", "Servir sur le quinoa cuit." ] },
  { slug: "omelette-pommes-terre-salade", nom: "Omelette pommes de terre et salade", description: "Une omelette généreuse et simple pour un dîner sans viande.", photoLocale: "/repas/omelette-pommes-terre-salade.png", typeRepas: "DINER", objectifs: ["EQUILIBRE", "PERTE_DE_POIDS"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 25, macros: { calories: 470, proteines: 27, glucides: 45, lipides: 20 }, portion: "1 omelette", allergenes: ["Œufs"], ingredients: ["3 œufs", "180 g de pommes de terre cuites", "1/2 oignon", "Salade verte", "Ciboulette, paprika et huile d'olive"], etapes: ["Faire dorer pommes de terre et oignon.", "Battre les œufs avec ciboulette et paprika.", "Verser, cuire à couvert puis servir avec salade." ] },
  { slug: "curry-crevettes-coco", nom: "Curry de crevettes coco et légumes", description: "Un curry express parfumé au citron vert et au gingembre.", photoLocale: "/repas/curry-crevettes-coco.png", typeRepas: "DINER", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["SANS_GLUTEN"], tempsMinutes: 25, macros: { calories: 545, proteines: 37, glucides: 57, lipides: 18 }, portion: "1 bowl", allergenes: ["Crustacés"], ingredients: ["180 g de crevettes", "60 g de riz jasmin sec", "120 ml de lait de coco léger", "Brocoli et poivron", "Curry, gingembre et citron vert"], etapes: ["Cuire le riz.", "Sauter les légumes avec curry et gingembre.", "Ajouter crevettes et lait de coco, mijoter 6 minutes puis servir." ] },
  { slug: "bowl-falafels-quinoa", nom: "Bowl falafels, quinoa et crudités", description: "Un bowl végétarien complet avec falafels dorés au four.", photoLocale: "/repas/bowl-falafels-quinoa.png", typeRepas: "DEJEUNER", objectifs: ["EQUILIBRE", "PERTE_DE_POIDS"], regimes: ["VEGETARIEN"], tempsMinutes: 35, macros: { calories: 540, proteines: 23, glucides: 76, lipides: 16 }, portion: "1 bowl", allergenes: ["Sésame"], ingredients: ["150 g de pois chiches cuits", "60 g de quinoa sec", "Concombre, tomate et chou rouge", "1 c. à soupe de tahini", "Cumin, persil et citron"], etapes: ["Mixer pois chiches, cumin et persil puis former les falafels.", "Cuire au four 20 minutes.", "Servir avec quinoa, crudités et sauce tahini-citron." ] },
  { slug: "skyr-fruits-graines", nom: "Skyr, fruits frais et graines", description: "Une collation riche en protéines prête en deux minutes.", photoLocale: "/repas/skyr-fruits-graines.png", typeRepas: "COLLATION", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 3, macros: { calories: 240, proteines: 22, glucides: 27, lipides: 6 }, portion: "1 bol", allergenes: ["Lait", "Fruits à coque"], ingredients: ["200 g de skyr", "100 g de fruits rouges", "1 kiwi", "10 g de graines de chia", "Cannelle"], etapes: ["Verser le skyr.", "Ajouter fruits et graines.", "Finir avec cannelle et déguster frais." ] },
  { slug: "pomme-cacahuete-cannelle", nom: "Pomme, purée de cacahuète et cannelle", description: "Une collation nomade avec fibres et bons lipides.", photoLocale: "/repas/pomme-cacahuete-cannelle.png", typeRepas: "COLLATION", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 4, macros: { calories: 210, proteines: 7, glucides: 28, lipides: 9 }, portion: "1 pomme", allergenes: ["Arachides"], ingredients: ["1 grosse pomme", "15 g de purée de cacahuète", "Cannelle", "10 g de graines de courge"], etapes: ["Laver et trancher la pomme.", "Ajouter la purée de cacahuète en filet.", "Parsemer de cannelle et de graines." ] },
  { slug: "muffins-oeufs-legumes", nom: "Muffins d'œufs aux légumes", description: "Des bouchées salées faciles à préparer pour plusieurs jours.", photoLocale: "/repas/muffins-oeufs-legumes.png", typeRepas: "COLLATION", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 25, macros: { calories: 220, proteines: 20, glucides: 8, lipides: 12 }, portion: "3 muffins", allergenes: ["Œufs", "Lait"], ingredients: ["2 œufs", "80 g de cottage cheese", "Poivron et épinards", "20 g de feta", "Poivre et herbes"], etapes: ["Battre œufs et cottage cheese.", "Ajouter légumes et feta.", "Répartir dans des moules et cuire 18 minutes à 180°C." ] },
  { slug: "crackers-thon-concombre", nom: "Crackers de seigle, thon et concombre", description: "Une collation salée fraîche avec une bonne dose de protéines.", photoLocale: "/repas/crackers-thon-concombre.png", typeRepas: "COLLATION", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: [], tempsMinutes: 7, macros: { calories: 260, proteines: 24, glucides: 24, lipides: 8 }, portion: "4 crackers", allergenes: ["Gluten", "Poisson", "Lait"], ingredients: ["4 crackers de seigle", "100 g de thon au naturel", "60 g de fromage frais", "1/2 concombre", "Citron et aneth"], etapes: ["Mélanger thon, fromage frais, citron et aneth.", "Étaler sur les crackers.", "Ajouter les rondelles de concombre." ] },
  { slug: "yaourt-grec-fruits-noix", nom: "Yaourt grec, fruits et noix", description: "Un encas simple avec protéines, fibres et croquant.", photoLocale: "/repas/yaourt-grec-fruits-noix.png", typeRepas: "COLLATION", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 4, macros: { calories: 310, proteines: 18, glucides: 29, lipides: 14 }, portion: "1 bol", allergenes: ["Lait", "Fruits à coque"], ingredients: ["170 g de yaourt grec", "1/2 pêche", "80 g de raisin", "15 g de noix", "Cannelle"], etapes: ["Verser le yaourt.", "Ajouter les fruits coupés.", "Parsemer de noix et cannelle." ] },
  { slug: "smoothie-banane-cafe-proteine", nom: "Smoothie banane, café et protéine", description: "Un smoothie énergisant pour une collation pré-entraînement.", photoLocale: "/repas/smoothie-banane-cafe-proteine.png", typeRepas: "COLLATION", objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"], regimes: ["VEGETARIEN"], tempsMinutes: 5, macros: { calories: 290, proteines: 24, glucides: 39, lipides: 6 }, portion: "1 shaker", allergenes: ["Lait", "Fruits à coque"], ingredients: ["1 banane", "150 ml de café froid", "150 ml de lait", "25 g de protéine en poudre", "Glaçons et cacao"], etapes: ["Placer tous les ingrédients dans un blender.", "Mixer 30 secondes.", "Servir immédiatement bien frais." ] },
  { slug: "edamame-cajou-citron", nom: "Edamame, noix de cajou et citron", description: "Une collation végétale salée riche en protéines et minéraux.", photoLocale: "/repas/edamame-cajou-citron.png", typeRepas: "COLLATION", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 8, macros: { calories: 250, proteines: 14, glucides: 18, lipides: 14 }, portion: "1 petit bol", allergenes: ["Soja", "Fruits à coque"], ingredients: ["150 g d'edamame", "15 g de noix de cajou", "Citron", "Piment doux et fleur de sel"], etapes: ["Cuire les edamame 5 minutes.", "Ajouter cajou, citron et épices.", "Servir tiède ou froid." ] },
  { slug: "tartine-ricotta-poire", nom: "Tartine ricotta, poire et noix", description: "Une tartine sucrée-salée élégante pour une pause rassasiante.", photoLocale: "/repas/tartine-ricotta-poire.png", typeRepas: "COLLATION", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN"], tempsMinutes: 7, macros: { calories: 285, proteines: 12, glucides: 33, lipides: 12 }, portion: "1 tartine", allergenes: ["Gluten", "Lait", "Fruits à coque"], ingredients: ["1 tranche de pain complet", "70 g de ricotta", "1/2 poire", "10 g de noix", "Miel et thym"], etapes: ["Toaster le pain.", "Étaler la ricotta et ajouter la poire.", "Finir avec noix, thym et une pointe de miel." ] },
  { slug: "pois-chiches-grilles-curcuma", nom: "Pois chiches grillés au curcuma", description: "Un snack croustillant riche en fibres, sans friture.", photoLocale: "/repas/pois-chiches-grilles-curcuma.png", typeRepas: "COLLATION", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["VEGETARIEN", "SANS_GLUTEN", "ANTI_INFLAMMATOIRE"], tempsMinutes: 30, macros: { calories: 230, proteines: 10, glucides: 31, lipides: 7 }, portion: "1 ramequin", allergenes: [], ingredients: ["160 g de pois chiches cuits", "1 c. à café d'huile", "Curcuma, paprika et cumin", "Sel et poivre"], etapes: ["Sécher les pois chiches.", "Mélanger avec huile et épices.", "Rôtir 25 minutes à 200°C en secouant à mi-cuisson." ] },
  { slug: "fromage-blanc-cacao-noisettes", nom: "Fromage blanc cacao et noisettes", description: "Un dessert minute riche en protéines et peu sucré.", photoLocale: "/repas/fromage-blanc-cacao-noisettes.png", typeRepas: "COLLATION", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 4, macros: { calories: 230, proteines: 22, glucides: 16, lipides: 9 }, portion: "1 ramequin", allergenes: ["Lait", "Fruits à coque"], ingredients: ["200 g de fromage blanc", "1 c. à café de cacao non sucré", "10 g de noisettes", "Vanille", "Quelques framboises"], etapes: ["Mélanger fromage blanc, cacao et vanille.", "Ajouter les framboises.", "Parsemer de noisettes concassées." ] },
  { slug: "wrap-poulet-avocat", nom: "Mini-wrap poulet et avocat", description: "Un mini-wrap pratique pour une pause salée complète.", photoLocale: "/repas/wrap-poulet-avocat.png", typeRepas: "COLLATION", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: [], tempsMinutes: 12, macros: { calories: 320, proteines: 25, glucides: 29, lipides: 12 }, portion: "1 mini-wrap", allergenes: ["Gluten"], ingredients: ["1 petite tortilla", "90 g de poulet cuit", "1/4 avocat", "Salade et tomate", "Yaourt, citron et paprika"], etapes: ["Mélanger yaourt, citron et paprika.", "Garnir la tortilla de salade, poulet, avocat et tomate.", "Rouler serré et couper en deux." ] },
  { slug: "pudding-chocolat-tofu", nom: "Pudding chocolat au tofu soyeux", description: "Une crème dessert végétale onctueuse et riche en protéines.", photoLocale: "/repas/pudding-chocolat-tofu.png", typeRepas: "COLLATION", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 6, macros: { calories: 250, proteines: 18, glucides: 24, lipides: 10 }, portion: "1 verrine", allergenes: ["Soja"], ingredients: ["180 g de tofu soyeux", "15 g de cacao", "1 banane", "Vanille", "10 g de purée de noisette"], etapes: ["Mixer tofu, banane, cacao et vanille.", "Verser dans une verrine.", "Réfrigérer 30 minutes et ajouter la purée de noisette." ] },
  { slug: "mini-pancakes-proteines", nom: "Mini-pancakes protéinés", description: "De petites bouchées moelleuses pour une pause gourmande maîtrisée.", photoLocale: "/repas/mini-pancakes-proteines.png", typeRepas: "COLLATION", objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"], regimes: ["VEGETARIEN"], tempsMinutes: 12, macros: { calories: 275, proteines: 20, glucides: 33, lipides: 7 }, portion: "6 mini-pancakes", allergenes: ["Gluten", "Œufs", "Lait"], ingredients: ["35 g de farine d'avoine", "1 œuf", "80 g de skyr", "1/2 banane", "Levure et fruits rouges"], etapes: ["Écraser banane puis mélanger avec œuf et skyr.", "Ajouter farine et levure.", "Cuire de petites louches et servir avec fruits rouges." ] },
  { slug: "houmous-poivrons-crudites", nom: "Houmous et crudités de poivrons", description: "Une pause croquante avec houmous onctueux et légumes frais.", photoLocale: "/repas/houmous-poivrons-crudites.png", typeRepas: "COLLATION", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 8, macros: { calories: 215, proteines: 8, glucides: 23, lipides: 10 }, portion: "1 coupelle", allergenes: ["Sésame"], ingredients: ["80 g de pois chiches", "1 c. à café de tahini", "1/2 citron", "Poivron, concombre et carotte", "Cumin et ail"], etapes: ["Mixer pois chiches, tahini, citron, ail et cumin.", "Tailler les crudités en bâtonnets.", "Servir le houmous avec les légumes." ] },
  { slug: "boules-avoine-coco", nom: "Boules énergie avoine et coco", description: "Des bouchées maison à emporter avant une séance.", photoLocale: "/repas/boules-avoine-coco.png", typeRepas: "COLLATION", objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"], regimes: ["VEGETARIEN"], tempsMinutes: 15, macros: { calories: 260, proteines: 9, glucides: 28, lipides: 13 }, portion: "3 boules", allergenes: ["Gluten", "Fruits à coque"], ingredients: ["40 g d'avoine", "20 g de purée d'amande", "15 g de noix de coco râpée", "1 c. à soupe de miel", "Cacao et graines de chia"], etapes: ["Mélanger tous les ingrédients.", "Former des boules entre les paumes.", "Réfrigérer 30 minutes avant de déguster." ] },
  { slug: "roules-dinde-concombre", nom: "Roulés de dinde et concombre", description: "Une collation salée très légère et riche en protéines.", photoLocale: "/repas/roules-dinde-concombre.png", typeRepas: "COLLATION", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["SANS_GLUTEN"], tempsMinutes: 6, macros: { calories: 180, proteines: 24, glucides: 5, lipides: 7 }, portion: "4 roulés", allergenes: ["Lait"], ingredients: ["4 tranches de blanc de dinde", "60 g de fromage frais", "1/2 concombre", "Ciboulette et poivre"], etapes: ["Tartiner chaque tranche de fromage frais.", "Ajouter des bâtonnets de concombre.", "Rouler et couper en bouchées." ] },
  { slug: "compote-poire-skyr", nom: "Compote poire, skyr et granola", description: "Une collation douce avec fruit chaud et topping croquant.", photoLocale: "/repas/compote-poire-skyr.png", typeRepas: "COLLATION", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["VEGETARIEN"], tempsMinutes: 12, macros: { calories: 245, proteines: 18, glucides: 34, lipides: 5 }, portion: "1 verrine", allergenes: ["Lait", "Gluten", "Fruits à coque"], ingredients: ["1 poire", "150 g de skyr", "20 g de granola", "Cannelle", "Un filet de citron"], etapes: ["Cuire la poire en dés avec citron et cannelle 8 minutes.", "Laisser tiédir.", "Ajouter skyr puis granola." ] },
  { slug: "omelette-muffin-courgette", nom: "Muffin omelette à la courgette", description: "Une bouchée salée moelleuse pour utiliser les légumes du frigo.", photoLocale: "/repas/omelette-muffin-courgette.png", typeRepas: "COLLATION", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 22, macros: { calories: 205, proteines: 18, glucides: 8, lipides: 11 }, portion: "2 muffins", allergenes: ["Œufs", "Lait"], ingredients: ["2 œufs", "100 g de courgette râpée", "40 g de feta", "1 c. à soupe de flocons d'avoine", "Menthe et poivre"], etapes: ["Presser la courgette râpée.", "Mélanger avec œufs, feta, avoine et menthe.", "Cuire dans des moules 16 minutes à 180°C." ] },
  { slug: "trail-mix-noix-fruits-secs", nom: "Trail mix noix et fruits secs", description: "Un mélange nomade à portionner pour éviter le grignotage automatique.", photoLocale: "/repas/trail-mix-noix-fruits-secs.png", typeRepas: "COLLATION", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 3, macros: { calories: 270, proteines: 7, glucides: 24, lipides: 17 }, portion: "1 portion de 40 g", allergenes: ["Fruits à coque"], ingredients: ["15 g d'amandes", "10 g de noix de cajou", "10 g d'abricots secs", "5 g de graines de courge", "Cannelle"], etapes: ["Peser une portion de 40 g.", "Mélanger noix, fruits secs et graines.", "Conserver en sachet individuel." ] },
  { slug: "tartine-beurre-amande-banane", nom: "Tartine beurre d'amande et banane", description: "Une tartine pré-entraînement rapide avec glucides et bons lipides.", photoLocale: "/repas/tartine-beurre-amande-banane.png", typeRepas: "COLLATION", objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"], regimes: ["VEGETARIEN"], tempsMinutes: 5, macros: { calories: 300, proteines: 9, glucides: 39, lipides: 12 }, portion: "1 tartine", allergenes: ["Gluten", "Fruits à coque"], ingredients: ["1 tranche de pain complet", "15 g de beurre d'amande", "1/2 banane", "Graines de chia", "Cannelle"], etapes: ["Toaster le pain.", "Étaler le beurre d'amande.", "Ajouter banane, chia et cannelle." ] },
];

export const RECETTES_V6: Recette[] = base.map((recette) => ({
  ...recette,
  photoQuery: recette.nom,
  conservation,
  variantes,
}));

