import type { Recette } from "./recettes";

// Extension de la bibliothèque Diet COAI : recettes 66 à 114.
// Les macros sont des estimations indicatives par portion et les visuels
// associés montrent uniquement les ingrédients réellement listés ici.
export const RECETTES_EXTENSION: Recette[] = [
  {
    slug: "dhal-lentilles-corail-epinards",
    nom: "Dhal de lentilles corail et épinards",
    description: "Un dîner végétarien onctueux, riche en fibres et facile à préparer en batch cooking.",
    photoQuery: "red lentil spinach dhal basmati rice bowl",
    photoLocale: "/repas/diner-dhal-lentilles-corail-epinards.jpg",
    typeRepas: "DINER", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["VEGETARIEN", "SANS_GLUTEN", "ANTI_INFLAMMATOIRE"], tempsMinutes: 30,
    macros: { calories: 560, proteines: 25, glucides: 83, lipides: 14 }, portion: "1 grand bowl", allergenes: [],
    conservation: "4 jours au réfrigérateur ou 2 mois au congélateur ; conserver le riz séparément.",
    variantes: { LEAN: "50 g de riz sec et 250 g d'épinards.", RESET_TRX: "Version de base.", HYBRID: "Ajoute 30 g de riz sec après une séance longue.", MASS: "Ajoute riz, lait de coco et noix de cajou." },
    ingredients: ["80 g de lentilles corail sèches", "60 g de riz basmati sec", "150 g d'épinards", "200 g de tomates concassées", "80 ml de lait de coco léger", "1/2 oignon", "Curry, cumin, gingembre et citron"],
    etapes: ["Rincer les lentilles et cuire le riz séparément.", "Faire revenir l'oignon et les épices, puis ajouter tomate, lentilles et 250 ml d'eau.", "Mijoter 18 minutes, incorporer lait de coco et épinards, puis servir avec le riz."],
  },
  {
    slug: "risotto-orge-poulet-champignons",
    nom: "Risotto d'orge au poulet et champignons",
    description: "Une version complète et rassasiante du risotto, avec orge perlé et poulet maigre.",
    photoQuery: "pearl barley chicken mushroom risotto",
    photoLocale: "/repas/diner-risotto-orge-poulet-champignons.jpg",
    typeRepas: "DINER", objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"], regimes: [], tempsMinutes: 40,
    macros: { calories: 650, proteines: 52, glucides: 76, lipides: 17 }, portion: "1 assiette creuse", allergenes: ["Gluten", "Lait"],
    conservation: "3 jours au réfrigérateur ; réchauffer avec un peu d'eau ou de bouillon.",
    variantes: { LEAN: "60 g d'orge sec et davantage de champignons.", RESET_TRX: "Version de base.", HYBRID: "Ajoute 25 g d'orge sec.", MASS: "Ajoute orge, parmesan et huile d'olive." },
    ingredients: ["170 g de blanc de poulet", "80 g d'orge perlé sec", "200 g de champignons", "500 ml de bouillon peu salé", "30 g de parmesan", "1 échalote", "1 c. à café d'huile d'olive", "Thym et poivre"],
    etapes: ["Dorer le poulet en dés puis réserver.", "Faire revenir échalote, champignons et orge, puis ajouter le bouillon progressivement.", "Cuire 25 minutes en remuant, remettre le poulet et terminer avec parmesan et thym."],
  },
  {
    slug: "saumon-teriyaki-nouilles-soba",
    nom: "Saumon teriyaki et nouilles soba",
    description: "Un dîner d'inspiration japonaise avec saumon laqué, soba et légumes verts.",
    photoQuery: "teriyaki salmon soba noodles broccoli bowl",
    photoLocale: "/repas/diner-saumon-teriyaki-nouilles-soba.jpg",
    typeRepas: "DINER", objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"], regimes: ["ANTI_INFLAMMATOIRE"], tempsMinutes: 25,
    macros: { calories: 690, proteines: 43, glucides: 76, lipides: 25 }, portion: "1 grand bowl", allergenes: ["Poisson", "Soja", "Gluten", "Sésame"],
    conservation: "2 jours au réfrigérateur ; sauce séparée si possible.",
    variantes: { LEAN: "60 g de soba et 250 g de brocoli.", RESET_TRX: "Version de base.", HYBRID: "Ajoute 30 g de soba.", MASS: "Ajoute soba, edamame et sésame." },
    ingredients: ["160 g de saumon", "80 g de nouilles soba sèches", "180 g de brocoli", "80 g de carotte", "15 ml de sauce soja réduite en sel", "1 c. à café de miel", "Gingembre", "1 c. à café de sésame"],
    etapes: ["Mélanger soja, miel et gingembre, puis en badigeonner le saumon.", "Cuire les soba et les légumes en les gardant légèrement fermes.", "Poêler le saumon 3 à 4 minutes par face, assembler et parsemer de sésame."],
  },
  {
    slug: "curry-cabillaud-lait-coco",
    nom: "Curry de cabillaud au lait de coco",
    description: "Un curry doux de poisson blanc, légumes et riz, parfumé au citron vert.",
    photoQuery: "cod coconut curry vegetables basmati rice",
    photoLocale: "/repas/diner-curry-cabillaud-lait-coco.jpg",
    typeRepas: "DINER", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["SANS_GLUTEN"], tempsMinutes: 30,
    macros: { calories: 595, proteines: 45, glucides: 65, lipides: 18 }, portion: "1 bowl", allergenes: ["Poisson"],
    conservation: "2 jours au réfrigérateur ; ne pas recongeler un poisson déjà décongelé.",
    variantes: { LEAN: "50 g de riz sec et lait de coco allégé.", RESET_TRX: "Version de base.", HYBRID: "Ajoute 30 g de riz sec.", MASS: "Ajoute riz et lait de coco entier." },
    ingredients: ["200 g de cabillaud", "65 g de riz basmati sec", "100 ml de lait de coco léger", "120 g de courgette", "100 g de poivron", "100 g de tomates concassées", "Curry, ail, coriandre et citron vert"],
    etapes: ["Cuire le riz.", "Mijoter tomate, lait de coco, courgette, poivron et épices 10 minutes.", "Ajouter le cabillaud en cubes, cuire doucement 7 minutes et terminer au citron vert."],
  },
  {
    slug: "moussaka-legere-dinde",
    nom: "Moussaka légère à la dinde",
    description: "Une moussaka riche en légumes avec dinde maigre et sauce yaourt gratinée.",
    photoQuery: "light turkey eggplant moussaka slice",
    photoLocale: "/repas/diner-moussaka-legere-dinde.jpg",
    typeRepas: "DINER", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["SANS_GLUTEN"], tempsMinutes: 55,
    macros: { calories: 540, proteines: 48, glucides: 38, lipides: 23 }, portion: "1 grande part", allergenes: ["Lait", "Œufs"],
    conservation: "3 jours au réfrigérateur ou 2 mois au congélateur en parts.",
    variantes: { LEAN: "Dinde 5 %, yaourt 0 % et davantage d'aubergine.", RESET_TRX: "Version de base.", HYBRID: "Ajoute 250 g de pommes de terre au plat.", MASS: "Ajoute pommes de terre, huile d'olive et feta." },
    ingredients: ["180 g de dinde hachée", "300 g d'aubergine", "200 g de tomates concassées", "150 g de pomme de terre", "100 g de yaourt grec", "1 œuf", "1/2 oignon", "Cannelle, origan et ail"],
    etapes: ["Rôtir les tranches d'aubergine et de pomme de terre 20 minutes à 200°C.", "Cuire dinde, oignon, tomate, ail et épices.", "Monter les couches, napper du mélange yaourt-œuf et gratiner 25 minutes à 190°C."],
  },
  {
    slug: "burger-vegetarien-haricots-noirs",
    nom: "Burger végétarien aux haricots noirs",
    description: "Un burger végétal maison, protéiné, avec crudités et pommes de terre rôties.",
    photoQuery: "black bean veggie burger wholegrain bun roasted potatoes",
    photoLocale: "/repas/diner-burger-haricots-noirs.jpg",
    typeRepas: "DINER", objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"], regimes: ["VEGETARIEN"], tempsMinutes: 35,
    macros: { calories: 680, proteines: 28, glucides: 104, lipides: 18 }, portion: "1 burger avec accompagnement", allergenes: ["Gluten", "Œufs"],
    conservation: "Galettes : 3 jours au réfrigérateur ou 2 mois au congélateur ; assembler au dernier moment.",
    variantes: { LEAN: "Burger sans fromage, pain fin et grande salade.", RESET_TRX: "Version de base.", HYBRID: "Ajoute 150 g de pommes de terre.", MASS: "Ajoute fromage, avocat et davantage de pommes de terre." },
    ingredients: ["180 g de haricots noirs cuits", "1 pain burger complet", "200 g de pommes de terre", "1/2 œuf", "20 g de flocons d'avoine", "Tomate, laitue et oignon rouge", "Paprika, cumin et moutarde"],
    etapes: ["Écraser les haricots avec œuf, avoine et épices, puis former une galette.", "Cuire la galette à la poêle et rôtir les pommes de terre au four.", "Assembler le burger avec moutarde, tomate, laitue et oignon."],
  },
  {
    slug: "mijote-boeuf-carottes-pommes-terre",
    nom: "Mijoté de bœuf, carottes et pommes de terre",
    description: "Un plat familial réconfortant à base de bœuf maigre et légumes fondants.",
    photoQuery: "lean beef stew carrots potatoes bowl",
    photoLocale: "/repas/diner-mijote-boeuf-carottes-pommes-terre.jpg",
    typeRepas: "DINER", objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"], regimes: ["SANS_GLUTEN"], tempsMinutes: 100,
    macros: { calories: 625, proteines: 49, glucides: 63, lipides: 20 }, portion: "1 assiette creuse", allergenes: [],
    conservation: "4 jours au réfrigérateur ou 3 mois au congélateur.",
    variantes: { LEAN: "180 g de pommes de terre et davantage de carottes.", RESET_TRX: "Version de base.", HYBRID: "Ajoute 150 g de pommes de terre.", MASS: "Ajoute pommes de terre, huile et pain complet." },
    ingredients: ["180 g de bœuf à mijoter maigre", "250 g de pommes de terre", "200 g de carottes", "100 g de champignons", "1/2 oignon", "300 ml de bouillon", "Thym, laurier et poivre"],
    etapes: ["Dorer le bœuf et l'oignon dans une cocotte.", "Ajouter carottes, champignons, bouillon et aromates, puis mijoter 60 minutes.", "Ajouter les pommes de terre et poursuivre 30 minutes jusqu'à tendreté."],
  },
  {
    slug: "poelee-fajitas-poulet",
    nom: "Poêlée fajitas au poulet",
    description: "Une poêlée rapide de poulet, poivrons et haricots noirs servie avec tortillas.",
    photoQuery: "chicken fajita skillet peppers black beans tortillas",
    photoLocale: "/repas/diner-poelee-fajitas-poulet.jpg",
    typeRepas: "DINER", objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"], regimes: [], tempsMinutes: 25,
    macros: { calories: 640, proteines: 55, glucides: 70, lipides: 16 }, portion: "2 tortillas garnies", allergenes: ["Gluten", "Lait selon garniture"],
    conservation: "3 jours au réfrigérateur, tortillas et garnitures séparées.",
    variantes: { LEAN: "Une tortilla, 200 g de poulet et plus de légumes.", RESET_TRX: "Version de base.", HYBRID: "Ajoute une tortilla et un fruit.", MASS: "Ajoute tortilla, avocat et fromage." },
    ingredients: ["180 g de poulet", "2 petites tortillas complètes", "100 g de haricots noirs cuits", "1 poivron rouge", "1 poivron jaune", "1/2 oignon", "Paprika fumé, cumin et citron vert"],
    etapes: ["Émincer poulet, poivrons et oignon.", "Saisir le poulet avec les épices, ajouter les légumes puis les haricots.", "Réchauffer les tortillas et garnir avec la poêlée et le citron vert."],
  },
  {
    slug: "courgettes-farcies-thon",
    nom: "Courgettes farcies au thon",
    description: "Des courgettes gratinées au thon, tomate et quinoa pour un dîner léger mais complet.",
    photoQuery: "tuna stuffed zucchini tomato quinoa baked",
    photoLocale: "/repas/diner-courgettes-farcies-thon.jpg",
    typeRepas: "DINER", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["SANS_GLUTEN"], tempsMinutes: 40,
    macros: { calories: 495, proteines: 47, glucides: 49, lipides: 14 }, portion: "2 demi-courgettes", allergenes: ["Poisson", "Lait"],
    conservation: "2 jours au réfrigérateur ; réchauffer au four.",
    variantes: { LEAN: "50 g de quinoa sec et fromage allégé.", RESET_TRX: "Version de base.", HYBRID: "Ajoute 30 g de quinoa sec.", MASS: "Ajoute quinoa, mozzarella et huile d'olive." },
    ingredients: ["2 courgettes moyennes", "160 g de thon au naturel égoutté", "60 g de quinoa sec", "150 g de tomates concassées", "40 g de mozzarella", "1/2 oignon", "Basilic et poivre"],
    etapes: ["Cuire le quinoa et évider les courgettes.", "Mélanger chair de courgette, thon, tomate, oignon et quinoa.", "Garnir, couvrir de mozzarella et cuire 25 minutes à 190°C."],
  },
  {
    slug: "gratin-quinoa-epinards-feta",
    nom: "Gratin de quinoa, épinards et feta",
    description: "Un gratin végétarien complet, riche en protéines et facile à portionner.",
    photoQuery: "quinoa spinach feta bake casserole",
    photoLocale: "/repas/diner-gratin-quinoa-epinards-feta.jpg",
    typeRepas: "DINER", objectifs: ["EQUILIBRE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 40,
    macros: { calories: 585, proteines: 31, glucides: 63, lipides: 24 }, portion: "1 grande part", allergenes: ["Lait", "Œufs"],
    conservation: "3 jours au réfrigérateur ou 2 mois au congélateur en parts.",
    variantes: { LEAN: "60 g de quinoa sec et 40 g de feta.", RESET_TRX: "Version de base.", HYBRID: "Ajoute 30 g de quinoa sec.", MASS: "Ajoute feta, huile d'olive et noix." },
    ingredients: ["80 g de quinoa sec", "220 g d'épinards", "70 g de feta", "2 œufs", "100 g de yaourt grec", "100 g de tomates cerises", "Ail, muscade et poivre"],
    etapes: ["Cuire le quinoa et faire tomber les épinards.", "Mélanger quinoa, épinards, œufs, yaourt, tomates et la moitié de la feta.", "Verser dans un plat, ajouter le reste de feta et gratiner 25 minutes à 190°C."],
  },
  {
    slug: "crevettes-ail-polenta",
    nom: "Crevettes à l'ail et polenta",
    description: "Des crevettes citronnées sur une polenta crémeuse avec tomates et épinards.",
    photoQuery: "garlic shrimp creamy polenta spinach tomatoes",
    photoLocale: "/repas/diner-crevettes-ail-polenta.jpg",
    typeRepas: "DINER", objectifs: ["EQUILIBRE"], regimes: ["SANS_GLUTEN"], tempsMinutes: 25,
    macros: { calories: 565, proteines: 46, glucides: 64, lipides: 15 }, portion: "1 assiette creuse", allergenes: ["Crustacés", "Lait"],
    conservation: "2 jours au réfrigérateur ; conserver la polenta séparément.",
    variantes: { LEAN: "60 g de polenta et lait allégé.", RESET_TRX: "Version de base.", HYBRID: "Ajoute 30 g de polenta.", MASS: "Ajoute polenta, parmesan et huile d'olive." },
    ingredients: ["200 g de crevettes décortiquées", "75 g de polenta sèche", "250 ml de lait demi-écrémé", "120 g d'épinards", "120 g de tomates cerises", "1 gousse d'ail", "Citron, persil et paprika"],
    etapes: ["Cuire la polenta dans le lait et de l'eau selon le paquet.", "Saisir les crevettes avec ail et paprika, puis ajouter tomates et épinards.", "Servir les crevettes sur la polenta avec citron et persil."],
  },
  {
    slug: "filet-mignon-pomme-chou-rouge",
    nom: "Filet mignon, pomme et chou rouge",
    description: "Un plat sucré-salé équilibré avec porc maigre, chou rouge braisé et pomme.",
    photoQuery: "pork tenderloin apple braised red cabbage potatoes",
    photoLocale: "/repas/diner-filet-mignon-pomme-chou-rouge.jpg",
    typeRepas: "DINER", objectifs: ["EQUILIBRE"], regimes: ["SANS_GLUTEN"], tempsMinutes: 45,
    macros: { calories: 620, proteines: 48, glucides: 66, lipides: 18 }, portion: "1 grande assiette", allergenes: ["Moutarde"],
    conservation: "3 jours au réfrigérateur ; trancher la viande au moment de servir.",
    variantes: { LEAN: "180 g de pommes de terre et davantage de chou.", RESET_TRX: "Version de base.", HYBRID: "Ajoute 150 g de pommes de terre.", MASS: "Ajoute pommes de terre et huile de noix." },
    ingredients: ["180 g de filet mignon de porc", "250 g de chou rouge", "1 petite pomme", "220 g de pommes de terre", "1 c. à café de moutarde", "1 c. à café d'huile d'olive", "Thym et poivre"],
    etapes: ["Rôtir les pommes de terre 30 minutes à 200°C.", "Braiser le chou émincé avec la pomme et un fond d'eau.", "Saisir puis cuire le filet mignon, laisser reposer, trancher et servir avec moutarde."],
  },
  {
    slug: "ramen-poulet-legumes",
    nom: "Ramen au poulet et légumes",
    description: "Un bouillon complet avec poulet, nouilles, œuf et légumes croquants.",
    photoQuery: "chicken ramen egg bok choy mushrooms bowl",
    photoLocale: "/repas/diner-ramen-poulet-legumes.jpg",
    typeRepas: "DINER", objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"], regimes: [], tempsMinutes: 30,
    macros: { calories: 650, proteines: 52, glucides: 76, lipides: 16 }, portion: "1 grand bol", allergenes: ["Gluten", "Œufs", "Soja"],
    conservation: "Bouillon et garniture 3 jours au réfrigérateur ; nouilles cuites séparément.",
    variantes: { LEAN: "60 g de nouilles et davantage de légumes.", RESET_TRX: "Version de base.", HYBRID: "Ajoute 30 g de nouilles.", MASS: "Ajoute nouilles, œuf et huile de sésame." },
    ingredients: ["170 g de blanc de poulet", "80 g de nouilles ramen sèches", "1 œuf", "100 g de pak-choï", "100 g de champignons", "80 g de carotte", "600 ml de bouillon", "Sauce soja, gingembre et ciboule"],
    etapes: ["Cuire l'œuf 7 minutes et pocher le poulet dans le bouillon.", "Ajouter champignons, carotte et pak-choï, puis cuire les nouilles séparément.", "Assembler le bol avec poulet tranché, œuf et ciboule."],
  },
  {
    slug: "chili-tempeh-cacao",
    nom: "Chili de tempeh au cacao",
    description: "Un chili végétarien profond en goût, avec tempeh, haricots rouges et cacao non sucré.",
    photoQuery: "tempeh black bean chili cocoa tomato bowl",
    photoLocale: "/repas/diner-chili-tempeh-cacao.jpg",
    typeRepas: "DINER", objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 35,
    macros: { calories: 625, proteines: 36, glucides: 75, lipides: 22 }, portion: "1 grand bowl", allergenes: ["Soja"],
    conservation: "4 jours au réfrigérateur ou 3 mois au congélateur.",
    variantes: { LEAN: "150 g de haricots et davantage de poivron.", RESET_TRX: "Version de base.", HYBRID: "Ajoute 60 g de riz sec.", MASS: "Ajoute riz, avocat et graines de courge." },
    ingredients: ["180 g de tempeh", "180 g de haricots rouges cuits", "250 g de tomates concassées", "1 poivron rouge", "1/2 oignon", "1 c. à café de cacao non sucré", "Cumin, paprika fumé et coriandre"],
    etapes: ["Émietter et dorer le tempeh.", "Faire revenir oignon et poivron, puis ajouter tomate, haricots, cacao et épices.", "Mijoter 20 minutes, remettre le tempeh et servir avec coriandre."],
  },
  {
    slug: "colin-puree-petits-pois",
    nom: "Colin et purée de petits pois",
    description: "Un dîner frais et protéiné avec poisson blanc, purée verte et pommes grenailles.",
    photoQuery: "baked pollock pea puree baby potatoes plate",
    photoLocale: "/repas/diner-colin-puree-petits-pois.jpg",
    typeRepas: "DINER", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["SANS_GLUTEN"], tempsMinutes: 30,
    macros: { calories: 525, proteines: 47, glucides: 59, lipides: 12 }, portion: "1 grande assiette", allergenes: ["Poisson", "Lait"],
    conservation: "2 jours au réfrigérateur ; purée 3 jours séparément.",
    variantes: { LEAN: "180 g de pommes de terre et plus de petits pois.", RESET_TRX: "Version de base.", HYBRID: "Ajoute 120 g de pommes de terre.", MASS: "Ajoute pommes de terre, huile d'olive et yaourt." },
    ingredients: ["200 g de filet de colin", "220 g de petits pois", "220 g de pommes de terre grenaille", "50 g de yaourt grec", "1 c. à café d'huile d'olive", "Citron, menthe et poivre"],
    etapes: ["Rôtir les pommes de terre 25 minutes à 200°C.", "Cuire les petits pois puis les mixer avec yaourt, menthe et poivre.", "Cuire le colin 12 à 15 minutes au four et servir avec citron."],
  },
  {
    slug: "parmentier-dinde-patate-douce",
    nom: "Parmentier de dinde à la patate douce",
    description: "Un parmentier riche en protéines, surmonté d'une purée de patate douce.",
    photoQuery: "turkey sweet potato shepherd pie serving",
    photoLocale: "/repas/diner-parmentier-dinde-patate-douce.jpg",
    typeRepas: "DINER", objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"], regimes: ["SANS_GLUTEN"], tempsMinutes: 50,
    macros: { calories: 640, proteines: 50, glucides: 72, lipides: 18 }, portion: "1 grande part", allergenes: ["Lait"],
    conservation: "3 jours au réfrigérateur ou 2 mois au congélateur en parts.",
    variantes: { LEAN: "250 g de patate douce et dinde 5 %.", RESET_TRX: "Version de base.", HYBRID: "Ajoute 120 g de patate douce.", MASS: "Ajoute patate douce, fromage et huile d'olive." },
    ingredients: ["180 g de dinde hachée", "320 g de patate douce", "100 g de carotte", "80 g de petits pois", "1/2 oignon", "50 ml de lait", "30 g de fromage râpé", "Thym et muscade"],
    etapes: ["Cuire la patate douce et l'écraser avec le lait et la muscade.", "Cuire dinde, oignon, carotte, petits pois et thym.", "Placer la viande dans un plat, couvrir de purée et fromage, puis gratiner 20 minutes."],
  },
  {
    slug: "bolognaise-lentilles-champignons",
    nom: "Bolognaise de lentilles et champignons",
    description: "Une bolognaise végétale généreuse servie avec des spaghetti complets.",
    photoQuery: "lentil mushroom bolognese wholegrain spaghetti",
    photoLocale: "/repas/diner-bolognaise-lentilles-champignons.jpg",
    typeRepas: "DINER", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["VEGETARIEN"], tempsMinutes: 35,
    macros: { calories: 610, proteines: 27, glucides: 100, lipides: 11 }, portion: "1 grande assiette", allergenes: ["Gluten"],
    conservation: "Sauce : 4 jours au réfrigérateur ou 3 mois au congélateur ; pâtes séparées.",
    variantes: { LEAN: "60 g de pâtes et 250 g de champignons.", RESET_TRX: "Version de base.", HYBRID: "Ajoute 30 g de pâtes sèches.", MASS: "Ajoute pâtes, parmesan et huile d'olive." },
    ingredients: ["80 g de spaghetti complets secs", "180 g de lentilles cuites", "180 g de champignons", "250 g de tomates concassées", "1 carotte", "1/2 oignon", "Ail, basilic et origan"],
    etapes: ["Hacher et faire revenir champignons, carotte, oignon et ail.", "Ajouter tomate, lentilles et herbes, puis mijoter 20 minutes.", "Cuire les spaghetti al dente et servir avec la sauce."],
  },
  {
    slug: "muffin-proteine-banane",
    nom: "Muffin protéiné à la banane",
    description: "Un muffin moelleux à l'avoine, facile à emporter après l'entraînement.",
    photoQuery: "banana protein oat muffin single snack",
    photoLocale: "/repas/collation-muffin-proteine-banane.jpg",
    typeRepas: "COLLATION", objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"], regimes: ["VEGETARIEN"], tempsMinutes: 25,
    macros: { calories: 245, proteines: 15, glucides: 34, lipides: 6 }, portion: "1 gros muffin", allergenes: ["Gluten", "Œufs", "Lait"],
    conservation: "3 jours au réfrigérateur ou 2 mois au congélateur.",
    variantes: { LEAN: "Demi-banane et yaourt 0 %.", RESET_TRX: "Version de base.", HYBRID: "Ajoute une banane entière autour de la séance.", MASS: "Ajoute pépites de chocolat et purée d'amande." },
    ingredients: ["40 g de flocons d'avoine mixés", "1/2 banane mûre", "1 œuf", "80 g de skyr", "15 g de poudre protéinée vanille", "1/2 c. à café de levure", "Cannelle"],
    etapes: ["Écraser la banane et mélanger avec œuf et skyr.", "Ajouter avoine, poudre protéinée, levure et cannelle.", "Verser dans un moule et cuire 18 à 20 minutes à 180°C."],
  },
  {
    slug: "energy-balls-dattes-cacao-amandes",
    nom: "Energy balls dattes, cacao et amandes",
    description: "Des bouchées énergétiques sans cuisson, à portionner pour les jours actifs.",
    photoQuery: "date cocoa almond energy balls plate",
    photoLocale: "/repas/collation-energy-balls-dattes-cacao-amandes.jpg",
    typeRepas: "COLLATION", objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 15,
    macros: { calories: 230, proteines: 6, glucides: 30, lipides: 11 }, portion: "3 petites bouchées", allergenes: ["Fruits à coque"],
    conservation: "7 jours au réfrigérateur ou 2 mois au congélateur.",
    variantes: { LEAN: "Deux petites bouchées.", RESET_TRX: "Version de base.", HYBRID: "Trois bouchées avant un effort long.", MASS: "Quatre bouchées avec purée d'amande." },
    ingredients: ["45 g de dattes dénoyautées", "25 g d'amandes", "10 g de flocons d'avoine sans gluten", "1 c. à café de cacao non sucré", "1 c. à café d'eau", "Pincée de sel"],
    etapes: ["Mixer dattes, amandes, avoine, cacao et sel.", "Ajouter juste assez d'eau pour obtenir une pâte.", "Former trois boules et placer 30 minutes au frais."],
  },
  {
    slug: "cottage-concombre-herbes",
    nom: "Cottage cheese, concombre et herbes",
    description: "Une collation salée fraîche, riche en protéines et prête en cinq minutes.",
    photoQuery: "cottage cheese cucumber herbs savory bowl",
    photoLocale: "/repas/collation-cottage-concombre-herbes.jpg",
    typeRepas: "COLLATION", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 5,
    macros: { calories: 190, proteines: 24, glucides: 10, lipides: 6 }, portion: "1 bol", allergenes: ["Lait"],
    conservation: "24 heures au réfrigérateur ; ajouter les herbes au service.",
    variantes: { LEAN: "Cottage allégé et davantage de concombre.", RESET_TRX: "Version de base.", HYBRID: "Ajoute deux galettes de riz.", MASS: "Ajoute pain complet et huile d'olive." },
    ingredients: ["200 g de cottage cheese", "150 g de concombre", "1 c. à café d'huile d'olive", "Ciboulette et aneth", "Jus de citron et poivre"],
    etapes: ["Couper le concombre en petits dés.", "Mélanger avec le cottage cheese, les herbes et le citron.", "Terminer par l'huile et le poivre."],
  },
  {
    slug: "houmous-carottes-crackers-complets",
    nom: "Houmous, carottes et crackers complets",
    description: "Une collation croquante et riche en fibres avec une portion de houmous mesurée.",
    photoQuery: "hummus carrot sticks wholegrain crackers snack",
    photoLocale: "/repas/collation-houmous-carottes-crackers.jpg",
    typeRepas: "COLLATION", objectifs: ["EQUILIBRE"], regimes: ["VEGETARIEN"], tempsMinutes: 5,
    macros: { calories: 285, proteines: 9, glucides: 39, lipides: 11 }, portion: "1 plateau individuel", allergenes: ["Gluten", "Sésame"],
    conservation: "Houmous 3 jours au réfrigérateur ; crackers au sec.",
    variantes: { LEAN: "40 g de houmous, carottes à volonté et deux crackers.", RESET_TRX: "Version de base.", HYBRID: "Ajoute deux crackers.", MASS: "Ajoute houmous, crackers et olives." },
    ingredients: ["60 g de houmous", "150 g de bâtonnets de carotte", "30 g de crackers complets", "Paprika et citron"],
    etapes: ["Placer le houmous dans un petit bol.", "Tailler les carottes en bâtonnets.", "Servir avec crackers, paprika et un trait de citron."],
  },
  {
    slug: "pomme-yaourt-cannelle",
    nom: "Pomme, yaourt et cannelle",
    description: "Une collation simple, fruitée et protéinée pour les petites faims.",
    photoQuery: "Greek yogurt apple cinnamon snack bowl",
    photoLocale: "/repas/collation-pomme-yaourt-cannelle.jpg",
    typeRepas: "COLLATION", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 5,
    macros: { calories: 205, proteines: 19, glucides: 30, lipides: 2 }, portion: "1 bol", allergenes: ["Lait"],
    conservation: "À consommer dans les 12 heures ; citronner la pomme si préparée en avance.",
    variantes: { LEAN: "Yaourt 0 % et petite pomme.", RESET_TRX: "Version de base.", HYBRID: "Ajoute 30 g de granola.", MASS: "Ajoute granola et purée d'amande." },
    ingredients: ["200 g de yaourt grec ou skyr", "1 petite pomme", "Cannelle", "1 c. à café de jus de citron"],
    etapes: ["Couper la pomme en dés et la citronner.", "Verser le yaourt dans un bol.", "Ajouter la pomme et une généreuse pincée de cannelle."],
  },
  {
    slug: "mousse-chocolat-proteinee",
    nom: "Mousse au chocolat protéinée",
    description: "Une mousse express au cacao et skyr, onctueuse sans crème ajoutée.",
    photoQuery: "protein chocolate mousse skyr glass",
    photoLocale: "/repas/collation-mousse-chocolat-proteinee.jpg",
    typeRepas: "COLLATION", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 10,
    macros: { calories: 220, proteines: 27, glucides: 22, lipides: 4 }, portion: "1 verrine", allergenes: ["Lait"],
    conservation: "24 heures au réfrigérateur dans une verrine couverte.",
    variantes: { LEAN: "Skyr 0 % et sans sirop.", RESET_TRX: "Version de base.", HYBRID: "Ajoute une banane.", MASS: "Ajoute granola et purée de noisette." },
    ingredients: ["200 g de skyr", "15 g de cacao non sucré", "15 g de poudre protéinée chocolat", "1 c. à café de sirop d'érable", "2 c. à soupe de lait"],
    etapes: ["Tamiser le cacao et la poudre protéinée.", "Fouetter avec skyr, lait et sirop jusqu'à texture lisse.", "Réfrigérer 30 minutes avant de servir."],
  },
  {
    slug: "pois-chiches-rotis-paprika",
    nom: "Pois chiches rôtis au paprika",
    description: "Une collation salée et croustillante, riche en fibres et facile à conserver.",
    photoQuery: "crispy roasted chickpeas paprika snack bowl",
    photoLocale: "/repas/collation-pois-chiches-rotis-paprika.jpg",
    typeRepas: "COLLATION", objectifs: ["EQUILIBRE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 35,
    macros: { calories: 240, proteines: 11, glucides: 34, lipides: 7 }, portion: "1 petit bol", allergenes: [],
    conservation: "3 jours dans une boîte non hermétique à température ambiante pour préserver le croquant.",
    variantes: { LEAN: "120 g de pois chiches et 3 g d'huile.", RESET_TRX: "Version de base.", HYBRID: "Ajoute un fruit.", MASS: "Ajoute noix de cajou et huile d'olive." },
    ingredients: ["150 g de pois chiches cuits et égouttés", "1 c. à café d'huile d'olive", "Paprika fumé", "Cumin", "Pincée de sel"],
    etapes: ["Rincer puis sécher parfaitement les pois chiches.", "Mélanger avec huile et épices.", "Rôtir 25 à 30 minutes à 200°C en remuant à mi-cuisson."],
  },
  {
    slug: "skyr-kiwi-pistaches",
    nom: "Skyr, kiwi et pistaches",
    description: "Un bol frais riche en protéines, vitamine C et texture croquante.",
    photoQuery: "skyr kiwi pistachio snack bowl",
    photoLocale: "/repas/collation-skyr-kiwi-pistaches.jpg",
    typeRepas: "COLLATION", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 5,
    macros: { calories: 260, proteines: 24, glucides: 27, lipides: 8 }, portion: "1 bol", allergenes: ["Lait", "Fruits à coque"],
    conservation: "24 heures au réfrigérateur ; pistaches ajoutées au dernier moment.",
    variantes: { LEAN: "10 g de pistaches et skyr 0 %.", RESET_TRX: "Version de base.", HYBRID: "Ajoute 30 g de muesli.", MASS: "Ajoute muesli, miel et pistaches." },
    ingredients: ["220 g de skyr", "1 kiwi", "15 g de pistaches non salées", "Zeste de citron vert"],
    etapes: ["Verser le skyr dans un bol.", "Éplucher et couper le kiwi.", "Ajouter kiwi, pistaches concassées et zeste de citron vert."],
  },
  {
    slug: "galettes-riz-dinde-avocat",
    nom: "Galettes de riz, dinde et avocat",
    description: "Une collation salée rapide avec protéines maigres et avocat.",
    photoQuery: "rice cakes turkey avocado snack",
    photoLocale: "/repas/collation-galettes-riz-dinde-avocat.jpg",
    typeRepas: "COLLATION", objectifs: ["EQUILIBRE"], regimes: ["SANS_GLUTEN"], tempsMinutes: 5,
    macros: { calories: 285, proteines: 22, glucides: 26, lipides: 11 }, portion: "3 galettes garnies", allergenes: [],
    conservation: "À assembler au dernier moment ; garniture 24 heures au réfrigérateur.",
    variantes: { LEAN: "Deux galettes et 30 g d'avocat.", RESET_TRX: "Version de base.", HYBRID: "Ajoute deux galettes et un fruit.", MASS: "Ajoute galettes, avocat et fromage frais." },
    ingredients: ["3 galettes de riz", "100 g de blanc de dinde cuit", "50 g d'avocat", "Tomates cerises", "Citron et poivre"],
    etapes: ["Écraser l'avocat avec citron et poivre.", "Tartiner les galettes.", "Ajouter la dinde et les tomates juste avant de manger."],
  },
  {
    slug: "chia-framboises-yaourt",
    nom: "Chia, framboises et yaourt",
    description: "Un pudding frais riche en fibres, préparé la veille en quelques minutes.",
    photoQuery: "chia raspberry yogurt pudding jar",
    photoLocale: "/repas/collation-chia-framboises-yaourt.jpg",
    typeRepas: "COLLATION", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 5,
    macros: { calories: 270, proteines: 20, glucides: 27, lipides: 10 }, portion: "1 verrine", allergenes: ["Lait"],
    conservation: "2 jours au réfrigérateur dans un pot fermé.",
    variantes: { LEAN: "15 g de chia et yaourt 0 %.", RESET_TRX: "Version de base.", HYBRID: "Ajoute une banane.", MASS: "Ajoute granola et purée d'amande." },
    ingredients: ["180 g de yaourt grec", "20 g de graines de chia", "80 ml de lait", "100 g de framboises", "Vanille"],
    etapes: ["Mélanger yaourt, lait, chia et vanille.", "Réfrigérer au moins 3 heures en remuant après 10 minutes.", "Ajouter les framboises au service."],
  },
  {
    slug: "barre-avoine-cacahuete-proteines",
    nom: "Barre avoine, cacahuète et protéines",
    description: "Une barre maison dense et pratique pour compléter l'apport énergétique autour des séances.",
    photoQuery: "homemade oat peanut protein bar single",
    photoLocale: "/repas/collation-barre-avoine-cacahuete-proteines.jpg",
    typeRepas: "COLLATION", objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"], regimes: ["VEGETARIEN"], tempsMinutes: 15,
    macros: { calories: 310, proteines: 20, glucides: 36, lipides: 11 }, portion: "1 grande barre", allergenes: ["Gluten", "Arachides", "Lait"],
    conservation: "5 jours au réfrigérateur ou 2 mois au congélateur.",
    variantes: { LEAN: "Petite barre avec 10 g de purée de cacahuète.", RESET_TRX: "Version de base.", HYBRID: "Ajoute banane ou miel avant séance.", MASS: "Ajoute cacahuètes et chocolat noir." },
    ingredients: ["45 g de flocons d'avoine", "20 g de poudre protéinée", "20 g de purée de cacahuète", "30 g de compote sans sucre", "1 c. à café de miel", "Pincée de sel"],
    etapes: ["Mélanger tous les ingrédients jusqu'à obtenir une pâte compacte.", "Presser dans un petit moule chemisé.", "Réfrigérer 2 heures puis découper en barre."],
  },
  {
    slug: "oeufs-durs-tomates-cerises",
    nom: "Œufs durs et tomates cerises",
    description: "Une collation salée très simple, rassasiante et naturellement sans gluten.",
    photoQuery: "hard boiled eggs cherry tomatoes snack plate",
    photoLocale: "/repas/collation-oeufs-durs-tomates-cerises.jpg",
    typeRepas: "COLLATION", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 12,
    macros: { calories: 205, proteines: 15, glucides: 7, lipides: 13 }, portion: "2 œufs avec tomates", allergenes: ["Œufs"],
    conservation: "Œufs non écalés : 3 jours au réfrigérateur ; tomates séparées.",
    variantes: { LEAN: "Un œuf entier et deux blancs.", RESET_TRX: "Version de base.", HYBRID: "Ajoute pain complet ou galettes de riz.", MASS: "Ajoute avocat et pain complet." },
    ingredients: ["2 œufs", "150 g de tomates cerises", "Paprika", "Ciboulette", "Poivre"],
    etapes: ["Cuire les œufs 9 minutes dans l'eau frémissante.", "Les refroidir, les écaler et les couper en deux.", "Servir avec tomates, paprika, ciboulette et poivre."],
  },
  {
    slug: "edamame-citron-vert",
    nom: "Edamame, fleur de sel et citron vert",
    description: "Une collation végétale chaude ou froide, riche en protéines et rapide à préparer.",
    photoQuery: "steamed edamame lime sea salt bowl",
    photoLocale: "/repas/collation-edamame-citron-vert.jpg",
    typeRepas: "COLLATION", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 8,
    macros: { calories: 205, proteines: 18, glucides: 16, lipides: 9 }, portion: "1 bol sans cosses", allergenes: ["Soja"],
    conservation: "2 jours au réfrigérateur dans une boîte fermée.",
    variantes: { LEAN: "150 g d'edamame et peu de sel.", RESET_TRX: "Version de base.", HYBRID: "Ajoute un fruit.", MASS: "Ajoute riz, sésame et avocat." },
    ingredients: ["180 g d'edamame écossé", "1/2 citron vert", "Fleur de sel", "Piment doux facultatif"],
    etapes: ["Cuire l'edamame 4 à 5 minutes dans l'eau frémissante.", "Égoutter soigneusement.", "Assaisonner de citron vert, fleur de sel et piment doux."],
  },
  {
    slug: "cookies-banane-avoine",
    nom: "Cookies banane et avoine",
    description: "Des cookies moelleux à trois ingrédients, sans sucre ajouté.",
    photoQuery: "banana oatmeal cookies healthy snack plate",
    photoLocale: "/repas/collation-cookies-banane-avoine.jpg",
    typeRepas: "COLLATION", objectifs: ["EQUILIBRE"], regimes: ["VEGETARIEN"], tempsMinutes: 20,
    macros: { calories: 235, proteines: 7, glucides: 42, lipides: 6 }, portion: "3 petits cookies", allergenes: ["Gluten", "Fruits à coque"],
    conservation: "3 jours dans une boîte au frais ou 2 mois au congélateur.",
    variantes: { LEAN: "Deux cookies sans purée d'amande.", RESET_TRX: "Version de base.", HYBRID: "Trois cookies avant ou après séance.", MASS: "Ajoute chocolat noir et noix." },
    ingredients: ["1 petite banane mûre", "45 g de flocons d'avoine", "10 g de purée d'amande", "Cannelle"],
    etapes: ["Écraser la banane avec la purée d'amande.", "Incorporer avoine et cannelle.", "Former trois cookies et cuire 12 à 15 minutes à 180°C."],
  },
  {
    slug: "smoothie-fruits-rouges-kefir",
    nom: "Smoothie fruits rouges et kéfir",
    description: "Une boisson fraîche et protéinée, pratique quand l'appétit est limité.",
    photoQuery: "berry kefir smoothie glass",
    photoLocale: "/repas/collation-smoothie-fruits-rouges-kefir.jpg",
    typeRepas: "COLLATION", objectifs: ["EQUILIBRE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 5,
    macros: { calories: 255, proteines: 16, glucides: 39, lipides: 5 }, portion: "1 grand verre", allergenes: ["Lait"],
    conservation: "À boire immédiatement ou dans les 12 heures au réfrigérateur.",
    variantes: { LEAN: "Sans banane, avec davantage de fruits rouges.", RESET_TRX: "Version de base.", HYBRID: "Ajoute banane et avoine.", MASS: "Ajoute avoine, miel et purée d'amande." },
    ingredients: ["250 ml de kéfir", "120 g de fruits rouges surgelés", "1/2 banane", "1 c. à café de graines de lin moulues", "Vanille"],
    etapes: ["Placer tous les ingrédients dans un blender.", "Mixer jusqu'à texture lisse.", "Servir immédiatement dans un grand verre."],
  },
  {
    slug: "tartine-puree-amande-poire",
    nom: "Tartine purée d'amande et poire",
    description: "Une tartine sucrée équilibrée, idéale avant une séance modérée.",
    photoQuery: "almond butter pear wholegrain toast",
    photoLocale: "/repas/collation-tartine-amande-poire.jpg",
    typeRepas: "COLLATION", objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"], regimes: ["VEGETARIEN"], tempsMinutes: 5,
    macros: { calories: 290, proteines: 9, glucides: 43, lipides: 11 }, portion: "1 grande tartine", allergenes: ["Gluten", "Fruits à coque"],
    conservation: "À assembler au dernier moment ; poire citronnée 12 heures au frais.",
    variantes: { LEAN: "10 g de purée d'amande et demi-poire.", RESET_TRX: "Version de base.", HYBRID: "Ajoute une seconde tartine.", MASS: "Ajoute tartine, purée d'amande et miel." },
    ingredients: ["1 grande tranche de pain complet", "18 g de purée d'amande", "1/2 poire", "Cannelle", "Quelques gouttes de citron"],
    etapes: ["Griller légèrement le pain.", "Tartiner de purée d'amande.", "Ajouter la poire en fines tranches, citronner et saupoudrer de cannelle."],
  },
  {
    slug: "barquettes-concombre-thon",
    nom: "Barquettes de concombre au thon",
    description: "Une collation très fraîche et protéinée avec une garniture thon-yaourt.",
    photoQuery: "cucumber boats tuna yogurt filling snack",
    photoLocale: "/repas/collation-barquettes-concombre-thon.jpg",
    typeRepas: "COLLATION", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["SANS_GLUTEN"], tempsMinutes: 10,
    macros: { calories: 220, proteines: 35, glucides: 10, lipides: 5 }, portion: "4 barquettes", allergenes: ["Poisson", "Lait", "Moutarde"],
    conservation: "24 heures au réfrigérateur, dans une boîte fermée.",
    variantes: { LEAN: "Yaourt 0 % et davantage de concombre.", RESET_TRX: "Version de base.", HYBRID: "Ajoute crackers complets.", MASS: "Ajoute pain, avocat et huile d'olive." },
    ingredients: ["1 grand concombre", "130 g de thon au naturel égoutté", "60 g de yaourt grec", "1 c. à café de moutarde", "Ciboulette, citron et poivre"],
    etapes: ["Couper le concombre en quatre tronçons puis les creuser.", "Mélanger thon, yaourt, moutarde, citron et ciboulette.", "Garnir les barquettes et poivrer."],
  },
  {
    slug: "cottage-ananas-graines",
    nom: "Cottage cheese, ananas et graines",
    description: "Un bol sucré-salé riche en protéines avec ananas frais et graines croquantes.",
    photoQuery: "cottage cheese pineapple pumpkin seeds bowl",
    photoLocale: "/repas/collation-cottage-ananas-graines.jpg",
    typeRepas: "COLLATION", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 5,
    macros: { calories: 260, proteines: 25, glucides: 26, lipides: 8 }, portion: "1 bol", allergenes: ["Lait"],
    conservation: "24 heures au réfrigérateur ; graines ajoutées au dernier moment.",
    variantes: { LEAN: "Cottage allégé et 100 g d'ananas.", RESET_TRX: "Version de base.", HYBRID: "Ajoute 30 g de granola.", MASS: "Ajoute granola, graines et noix de coco." },
    ingredients: ["220 g de cottage cheese", "140 g d'ananas frais", "12 g de graines de courge", "Zeste de citron vert"],
    etapes: ["Verser le cottage cheese dans un bol.", "Couper l'ananas en dés.", "Ajouter ananas, graines de courge et zeste de citron vert."],
  },
  {
    slug: "fromage-blanc-peche-chia",
    nom: "Fromage blanc, pêche et graines de chia",
    description: "Une collation fraîche et rassasiante, prête en trois minutes avec une vraie dose de protéines.",
    photoQuery: "cottage cheese peach chia seed snack bowl",
    photoLocale: "/repas/collation-fromage-blanc-peche-chia.jpg",
    typeRepas: "COLLATION", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 3,
    macros: { calories: 185, proteines: 21, glucides: 21, lipides: 4 }, portion: "1 bol", allergenes: ["Lait"],
    conservation: "À consommer dans les 12 heures au réfrigérateur ; ajouter la pêche au dernier moment.",
    variantes: { LEAN: "Fromage blanc 0 % et une petite pêche.", RESET_TRX: "Version de base.", HYBRID: "Ajoute 20 g de granola après une séance.", MASS: "Ajoute 15 g de noix et une cuillère de miel." },
    ingredients: ["200 g de fromage blanc", "1 pêche", "10 g de graines de chia", "Vanille ou cannelle"],
    etapes: ["Verser le fromage blanc dans un bol.", "Couper la pêche en dés.", "Ajouter la pêche, les graines de chia et la vanille."],
  },
  {
    slug: "shake-banane-cacao-avoine",
    nom: "Shake banane, cacao et avoine",
    description: "Un shake onctueux à préparer en 2 minutes quand il faut une collation énergétique autour de l'entraînement.",
    photoQuery: "banana cocoa oat protein shake glass snack",
    photoLocale: "/repas/collation-shake-banane-cacao-avoine.jpg",
    typeRepas: "COLLATION", objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"], regimes: ["VEGETARIEN"], tempsMinutes: 2,
    macros: { calories: 320, proteines: 23, glucides: 45, lipides: 7 }, portion: "1 grand verre", allergenes: ["Lait", "Gluten selon l'avoine", "Fruits à coque selon la boisson"],
    conservation: "À boire immédiatement ; bien secouer si conservé moins de 4 heures au frais.",
    variantes: { LEAN: "Demi-banane, eau ou lait écrémé et sans miel.", RESET_TRX: "Version de base.", HYBRID: "Version complète après une séance longue.", MASS: "Ajoute 20 g de purée de cacahuète et 20 g d'avoine." },
    ingredients: ["1 banane", "250 ml de lait ou boisson végétale", "20 g de flocons d'avoine", "10 g de cacao non sucré", "20 g de poudre protéinée vanille", "Glaçons"],
    etapes: ["Placer tous les ingrédients dans un blender.", "Mixer 30 à 45 secondes jusqu'à texture lisse.", "Servir frais sans ajouter de sucre."],
  },
  {
    slug: "tortilla-houmous-oeuf-crudites",
    nom: "Tortilla houmous, œuf et crudités",
    description: "Un roulé salé pratique à emporter, avec protéines, fibres et croquant.",
    photoQuery: "hummus egg vegetable tortilla wrap snack",
    photoLocale: "/repas/collation-tortilla-houmous-oeuf.jpg",
    typeRepas: "COLLATION", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN"], tempsMinutes: 10,
    macros: { calories: 295, proteines: 15, glucides: 32, lipides: 12 }, portion: "1 tortilla roulée", allergenes: ["Gluten", "Œufs", "Sésame"],
    conservation: "12 heures au réfrigérateur, roulée dans du papier et sans tomate trop humide.",
    variantes: { LEAN: "Petite tortilla, 40 g de houmous et beaucoup de crudités.", RESET_TRX: "Version de base.", HYBRID: "Ajoute un fruit à côté.", MASS: "Ajoute une deuxième tortilla ou 30 g de feta." },
    ingredients: ["1 tortilla complète", "1 œuf dur", "50 g de houmous", "80 g de concombre et carotte", "Quelques feuilles de roquette", "Paprika et citron"],
    etapes: ["Tartiner le houmous sur la tortilla.", "Ajouter l'œuf en rondelles, les crudités et la roquette.", "Assaisonner, rouler serré puis couper en deux."],
  },
  {
    slug: "mini-wrap-poulet-crudites",
    nom: "Mini-wrap poulet et crudités",
    description: "Une option nomade riche en protéines pour éviter le grignotage improvisé entre deux rendez-vous.",
    photoQuery: "mini chicken vegetable wholegrain wrap snack",
    photoLocale: "/repas/collation-mini-wrap-poulet.jpg",
    typeRepas: "COLLATION", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: [], tempsMinutes: 10,
    macros: { calories: 245, proteines: 24, glucides: 25, lipides: 6 }, portion: "2 mini-wraps", allergenes: ["Gluten", "Lait"],
    conservation: "24 heures au réfrigérateur dans une boîte fermée ; garder la sauce à part si possible.",
    variantes: { LEAN: "Deux petites galettes, yaourt 0 % et davantage de salade.", RESET_TRX: "Version de base.", HYBRID: "Ajoute une banane les jours de volume élevé.", MASS: "Ajoute avocat ou fromage frais." },
    ingredients: ["2 petites tortillas complètes", "100 g de poulet cuit", "60 g de yaourt grec", "Carotte râpée et laitue", "Citron, paprika et poivre"],
    etapes: ["Mélanger le yaourt avec citron et paprika.", "Garnir les tortillas de sauce, poulet et crudités.", "Rouler, couper en deux et conserver au frais."],
  },
  {
    slug: "muffins-sales-thon-courgette",
    nom: "Muffins salés thon et courgette",
    description: "Des bouchées protéinées à préparer en avance, parfaites pour une collation salée ou un trajet.",
    photoQuery: "savory tuna zucchini egg muffins snack",
    photoLocale: "/repas/collation-muffins-thon-courgette.jpg",
    typeRepas: "COLLATION", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["SANS_GLUTEN"], tempsMinutes: 30,
    macros: { calories: 210, proteines: 27, glucides: 9, lipides: 7 }, portion: "3 petits muffins", allergenes: ["Poisson", "Œufs", "Lait"],
    conservation: "3 jours au réfrigérateur ; réchauffer doucement ou manger froid.",
    variantes: { LEAN: "Utilise du thon au naturel et du fromage blanc 0 %.", RESET_TRX: "Version de base.", HYBRID: "Ajoute une tranche de pain complet.", MASS: "Ajoute fromage râpé et une portion de féculent." },
    ingredients: ["1 boîte de thon au naturel (120 g égoutté)", "2 œufs", "100 g de courgette râpée et pressée", "60 g de fromage blanc", "20 g de parmesan", "Herbes, poivre"],
    etapes: ["Préchauffer le four à 180°C et huiler légèrement trois empreintes.", "Mélanger thon, œufs, courgette, fromage blanc, parmesan et herbes.", "Répartir dans les moules et cuire 20 minutes."],
  },
  {
    slug: "yaourt-soja-mangue-coco",
    nom: "Yaourt soja, mangue et coco",
    description: "Une collation végétale douce et fraîche, avec une texture crémeuse et une touche tropicale.",
    photoQuery: "soy yogurt mango coconut snack bowl",
    photoLocale: "/repas/collation-yaourt-soja-mangue.jpg",
    typeRepas: "COLLATION", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 5,
    macros: { calories: 220, proteines: 13, glucides: 28, lipides: 6 }, portion: "1 bol", allergenes: ["Soja"],
    conservation: "24 heures au réfrigérateur ; ajouter la noix de coco au moment de servir.",
    variantes: { LEAN: "Yaourt soja nature et 100 g de mangue.", RESET_TRX: "Version de base.", HYBRID: "Ajoute 25 g de granola.", MASS: "Ajoute granola, noix de cajou et une cuillère de sirop d'érable." },
    ingredients: ["200 g de yaourt soja nature", "120 g de mangue", "10 g de noix de coco râpée", "Citron vert et vanille"],
    etapes: ["Verser le yaourt dans un bol.", "Ajouter la mangue en dés.", "Terminer avec coco, citron vert et vanille."],
  },
  {
    slug: "galettes-sarrasin-fromage-frais-radis",
    nom: "Galettes de sarrasin au fromage frais et radis",
    description: "Une collation croquante sans gluten, simple à préparer et facile à portionner.",
    photoQuery: "buckwheat crackers cream cheese radish snack plate",
    photoLocale: "/repas/collation-galettes-sarrasin-radis.jpg",
    typeRepas: "COLLATION", objectifs: ["EQUILIBRE", "PERTE_DE_POIDS"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 5,
    macros: { calories: 195, proteines: 11, glucides: 22, lipides: 7 }, portion: "4 galettes garnies", allergenes: ["Lait"],
    conservation: "À assembler au dernier moment ; fromage frais fermé 3 jours au réfrigérateur.",
    variantes: { LEAN: "Fromage frais allégé et trois galettes.", RESET_TRX: "Version de base.", HYBRID: "Ajoute un fruit.", MASS: "Ajoute une galette et 15 g de noix." },
    ingredients: ["4 galettes de sarrasin soufflé", "80 g de fromage frais", "5 radis", "Ciboulette, citron et poivre"],
    etapes: ["Tartiner les galettes de fromage frais.", "Trancher finement les radis.", "Ajouter radis, ciboulette, citron et poivre."],
  },
  {
    slug: "compote-skyr-noix",
    nom: "Compote sans sucre, skyr et noix",
    description: "Une collation minute qui combine douceur, protéines et croquant sans ajout de sucre raffiné.",
    photoQuery: "unsweetened apple compote skyr walnuts snack bowl",
    photoLocale: "/repas/collation-compote-skyr-noix.jpg",
    typeRepas: "COLLATION", objectifs: ["PERTE_DE_POIDS", "EQUILIBRE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 3,
    macros: { calories: 230, proteines: 20, glucides: 27, lipides: 6 }, portion: "1 bol", allergenes: ["Lait", "Fruits à coque"],
    conservation: "24 heures au réfrigérateur ; mélanger juste avant de manger.",
    variantes: { LEAN: "Compote sans sucre, skyr 0 % et 5 g de noix.", RESET_TRX: "Version de base.", HYBRID: "Ajoute 20 g de flocons d'avoine.", MASS: "Ajoute 30 g d'avoine et 15 g de noix." },
    ingredients: ["120 g de compote de pomme sans sucre", "180 g de skyr", "10 g de noix concassées", "Cannelle"],
    etapes: ["Verser la compote puis le skyr dans un bol.", "Ajouter les noix.", "Saupoudrer de cannelle et mélanger légèrement."],
  },
  {
    slug: "pois-chiches-concombre-feta",
    nom: "Salade minute pois chiches, concombre et feta",
    description: "Une petite salade salée riche en fibres, idéale quand une collation doit vraiment rassasier.",
    photoQuery: "chickpea cucumber feta snack salad bowl",
    photoLocale: "/repas/collation-pois-chiches-concombre-feta.jpg",
    typeRepas: "COLLATION", objectifs: ["EQUILIBRE", "PERTE_DE_POIDS"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 8,
    macros: { calories: 255, proteines: 12, glucides: 31, lipides: 9 }, portion: "1 petit bol", allergenes: ["Lait"],
    conservation: "24 heures au réfrigérateur ; ajouter la feta et le citron au dernier moment.",
    variantes: { LEAN: "100 g de pois chiches et davantage de concombre.", RESET_TRX: "Version de base.", HYBRID: "Ajoute une tranche de pain complet.", MASS: "Ajoute huile d'olive, feta et pain pita." },
    ingredients: ["120 g de pois chiches cuits", "150 g de concombre", "35 g de feta", "1 c. à café d'huile d'olive", "Citron, menthe et poivre"],
    etapes: ["Rincer et égoutter les pois chiches.", "Couper le concombre et émietter la feta.", "Mélanger avec citron, huile, menthe et poivre."],
  },
  {
    slug: "boules-coco-proteinees",
    nom: "Boules coco et protéines",
    description: "Des bouchées moelleuses sans cuisson, faciles à préparer le dimanche pour toute la semaine.",
    photoQuery: "coconut protein energy balls snack plate",
    photoLocale: "/repas/collation-boules-coco-proteinees.jpg",
    typeRepas: "COLLATION", objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 15,
    macros: { calories: 250, proteines: 16, glucides: 24, lipides: 10 }, portion: "3 boules", allergenes: ["Lait", "Fruits à coque"],
    conservation: "5 jours au réfrigérateur ou 2 mois au congélateur.",
    variantes: { LEAN: "Deux boules et compote sans sucre à côté.", RESET_TRX: "Version de base.", HYBRID: "Trois boules avant un effort long.", MASS: "Ajoute 10 g de purée d'amande dans la pâte." },
    ingredients: ["30 g de noix de coco râpée", "35 g de flocons d'avoine sans gluten", "20 g de poudre protéinée vanille", "60 g de compote sans sucre", "15 g de purée d'amande", "Vanille"],
    etapes: ["Mélanger coco, avoine et protéine.", "Ajouter compote, purée d'amande et vanille jusqu'à obtenir une pâte.", "Former trois boules et réfrigérer 30 minutes."],
  },
  {
    slug: "bowl-skyr-kiwi-granola",
    nom: "Bowl skyr, kiwi et granola",
    description: "Un petit-déjeuner frais et protéiné, prêt en quelques minutes pour démarrer avec une énergie stable.",
    photoQuery: "skyr kiwi granola breakfast bowl",
    photoLocale: "/repas/bowl-skyr-kiwi-granola.png",
    typeRepas: "PETIT_DEJEUNER", objectifs: ["PERTE_DE_POIDS", "PRISE_DE_MASSE", "EQUILIBRE"], regimes: ["VEGETARIEN"], tempsMinutes: 5,
    macros: { calories: 390, proteines: 28, glucides: 48, lipides: 10 }, portion: "1 bol", allergenes: ["Lait", "Gluten selon le granola"],
    conservation: "À consommer immédiatement ; préparation possible la veille sans le granola.",
    variantes: { LEAN: "Skyr 0 % et 25 g de granola.", RESET_TRX: "Ajoute le kiwi et 10 g de graines.", HYBRID: "Ajoute une cuillère de miel les jours longs.", MASS: "Double le granola et ajoute 15 g de purée de cacahuète." },
    ingredients: ["200 g de skyr", "1 kiwi", "35 g de granola", "10 g de graines de chia", "Cannelle"],
    etapes: ["Verser le skyr dans un bol.", "Ajouter le kiwi en rondelles et les graines de chia.", "Parsemer de granola et de cannelle juste avant de servir."],
  },
  {
    slug: "dinde-patate-douce-haricots-verts",
    nom: "Dinde, patate douce et haricots verts",
    description: "Un dîner simple et rassasiant qui associe protéines maigres, glucides de qualité et légumes croquants.",
    photoQuery: "turkey sweet potato green beans healthy dinner plate",
    photoLocale: "/repas/dinde-patate-douce-haricots-verts.png",
    typeRepas: "DINER", objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"], regimes: ["SANS_GLUTEN"], tempsMinutes: 35,
    macros: { calories: 560, proteines: 46, glucides: 56, lipides: 16 }, portion: "1 assiette", allergenes: [],
    conservation: "3 jours au réfrigérateur dans une boîte hermétique ; réchauffer doucement.",
    variantes: { LEAN: "150 g de patate douce et 5 g d'huile.", RESET_TRX: "Version de base.", HYBRID: "Ajoute 100 g de patate douce les jours de volume.", MASS: "Ajoute 50 g de patate douce et 10 g d'huile d'olive." },
    ingredients: ["170 g d'escalope de dinde", "250 g de patate douce", "180 g de haricots verts", "10 g d'huile d'olive", "Paprika, ail, thym, sel et poivre"],
    etapes: ["Couper la patate douce en cubes et cuire 25 minutes au four à 200°C avec la moitié de l'huile.", "Cuire les haricots verts 8 à 10 minutes puis les égoutter.", "Saisir la dinde avec l'huile restante et les épices, puis servir avec les légumes."],
  },
  {
    slug: "bouchees-dattes-cacahuete-proteinees",
    nom: "Bouchées dattes, cacahuète et cacao",
    description: "Une collation sans cuisson, pratique avant une séance ou pour éviter le grignotage improvisé.",
    photoQuery: "date peanut butter cocoa protein energy bites snack",
    photoLocale: "/repas/bouchees-dattes-cacahuete-proteinees.png",
    typeRepas: "COLLATION", objectifs: ["PRISE_DE_MASSE", "EQUILIBRE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 10,
    macros: { calories: 220, proteines: 8, glucides: 28, lipides: 9 }, portion: "3 bouchées", allergenes: ["Arachides", "Fruits à coque selon la protéine"],
    conservation: "4 jours au réfrigérateur ou 1 mois au congélateur.",
    variantes: { LEAN: "Deux bouchées et un fruit frais.", RESET_TRX: "Version de base.", HYBRID: "Trois bouchées avant une sortie longue.", MASS: "Ajoute 10 g de purée de cacahuète et une bouchée supplémentaire." },
    ingredients: ["90 g de dattes dénoyautées", "25 g de purée de cacahuète", "15 g de cacao non sucré", "25 g de flocons d'avoine sans gluten", "20 g de protéine en poudre", "1 pincée de sel"],
    etapes: ["Mixer les dattes avec la purée de cacahuète.", "Ajouter cacao, avoine, protéine et sel puis mixer jusqu'à obtenir une pâte.", "Former six petites bouchées et réfrigérer 30 minutes."],
  },
];
