import type { Recette } from "./recettes";

// Série CoAI v8 — recettes végétariennes orientées récupération après l’effort.
type BaseRecette = Omit<Recette, "photoQuery" | "conservation" | "variantes">;

const conservation = "À conserver jusqu’à 3 jours au réfrigérateur dans une boîte hermétique.";
const variantes: NonNullable<Recette["variantes"]> = {
  LEAN: "Réduis de 15 % la portion de féculents et augmente les légumes.",
  RESET_TRX: "Garde la portion indiquée pour soutenir la récupération.",
  HYBRID: "Ajoute 25 à 30 g de féculents secs après une séance longue.",
  MASS: "Ajoute une portion de féculents et 1 c. à café d’huile d’olive.",
};

const base: BaseRecette[] = [
  { slug: "bowl-recuperation-tofu-patate-douce", nom: "Bowl récupération tofu et patate douce", description: "Un bowl végétal complet associant glucides, protéines et légumes colorés.", photoLocale: "/repas/bowl-recuperation-tofu-patate-douce-v1.png", typeRepas: "DEJEUNER", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN", "SANS_GLUTEN", "ANTI_INFLAMMATOIRE"], tempsMinutes: 30, macros: { calories: 640, proteines: 36, glucides: 72, lipides: 24 }, portion: "1 grand bowl", allergenes: ["Soja", "Sésame"], ingredients: ["180 g de tofu ferme", "220 g de patate douce", "120 g de quinoa cuit", "Épinards", "Betterave", "15 g de graines de courge", "Tahini, curcuma et citron"], etapes: ["Rôtir la patate douce et dorer le tofu.", "Disposer quinoa, épinards et betterave dans un bowl.", "Ajouter tofu, graines et sauce tahini-curcuma."] },
  { slug: "galettes-pomme-terre-cottage-oeufs", nom: "Galettes de pomme de terre, cottage et œufs", description: "Une assiette salée riche en protéines et en glucides utiles après l’effort.", photoLocale: "/repas/galettes-pomme-terre-cottage-oeufs-v1.png", typeRepas: "DEJEUNER", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 30, macros: { calories: 560, proteines: 38, glucides: 52, lipides: 22 }, portion: "2 galettes et 2 œufs", allergenes: ["Œufs", "Lait"], ingredients: ["250 g de pomme de terre", "150 g de cottage cheese", "2 œufs", "Épinards", "Tomates cerises", "Herbes"], etapes: ["Râper la pomme de terre et former deux galettes avec la moitié du cottage.", "Dorer les galettes et pocher les œufs.", "Servir avec épinards, tomates et cottage restant."] },
  { slug: "smoothie-bowl-skyr-cerises-cacao", nom: "Smoothie bowl skyr, cerises et cacao", description: "Un bowl frais aux fruits rouges, cacao et graines de chanvre.", photoLocale: "/repas/smoothie-bowl-skyr-cerises-cacao-v1.png", typeRepas: "COLLATION", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN", "SANS_GLUTEN", "ANTI_INFLAMMATOIRE"], tempsMinutes: 8, macros: { calories: 430, proteines: 32, glucides: 55, lipides: 11 }, portion: "1 bowl", allergenes: ["Lait"], ingredients: ["250 g de skyr", "1 banane", "100 g de cerises", "80 g de myrtilles", "10 g de cacao", "15 g de graines de chanvre", "Éclats de cacao"], etapes: ["Mixer skyr, banane, cerises et cacao.", "Verser dans un bowl.", "Ajouter myrtilles, chanvre et éclats de cacao."] },
  { slug: "dal-lentilles-paneer-epinards", nom: "Dal de lentilles, paneer et épinards", description: "Un dal réconfortant au gingembre et curcuma, enrichi de paneer.", photoLocale: "/repas/dal-lentilles-paneer-epinards-v1.png", typeRepas: "DINER", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN", "SANS_GLUTEN", "ANTI_INFLAMMATOIRE"], tempsMinutes: 30, macros: { calories: 650, proteines: 37, glucides: 77, lipides: 22 }, portion: "1 grand bowl", allergenes: ["Lait"], ingredients: ["200 g de lentilles corail cuites", "120 g de paneer", "100 g de riz basmati cuit", "Épinards", "Tomate", "Curcuma, cumin et gingembre"], etapes: ["Mijoter lentilles, tomate et épices 15 minutes.", "Dorer le paneer et ajouter les épinards au dal.", "Servir avec le riz et le paneer."] },
  { slug: "bowl-quinoa-oeufs-betterave-edamame", nom: "Bowl quinoa, œufs et betterave", description: "Un bowl protéiné aux œufs, edamame, betterave et noix.", photoLocale: "/repas/bowl-quinoa-oeufs-betterave-edamame-v1.png", typeRepas: "DEJEUNER", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN", "SANS_GLUTEN", "ANTI_INFLAMMATOIRE"], tempsMinutes: 20, macros: { calories: 620, proteines: 34, glucides: 57, lipides: 29 }, portion: "1 grand bowl", allergenes: ["Œufs", "Soja", "Fruits à coque"], ingredients: ["2 œufs", "150 g de quinoa cuit", "100 g d’edamame", "Betterave rôtie", "Épinards", "1/2 avocat", "15 g de noix", "Citron et herbes"], etapes: ["Cuire les œufs 7 minutes.", "Disposer quinoa, edamame, betterave, épinards et avocat.", "Ajouter œufs, noix et vinaigrette citronnée."] },
  { slug: "baked-oats-skyr-myrtilles", nom: "Baked oats au skyr et myrtilles", description: "Un carré d’avoine moelleux pensé pour refaire les réserves après l’effort.", photoLocale: "/repas/baked-oats-skyr-myrtilles-v1.png", typeRepas: "PETIT_DEJEUNER", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 35, macros: { calories: 490, proteines: 31, glucides: 64, lipides: 13 }, portion: "1 grand carré", allergenes: ["Œufs", "Lait"], ingredients: ["70 g de flocons d’avoine certifiés sans gluten", "200 g de skyr", "2 œufs", "1 banane", "100 g de myrtilles", "Levure sans gluten"], etapes: ["Mélanger avoine, 150 g de skyr, œufs et banane écrasée.", "Ajouter les myrtilles et cuire 25 minutes à 180°C.", "Servir tiède avec le skyr restant."] },
  { slug: "nouilles-sarrasin-tofu-edamame", nom: "Nouilles de sarrasin, tofu et edamame", description: "Un bowl végétal au gingembre associant sarrasin, tofu et edamame.", photoLocale: "/repas/nouilles-sarrasin-tofu-edamame-v1.png", typeRepas: "DINER", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN", "SANS_GLUTEN", "ANTI_INFLAMMATOIRE"], tempsMinutes: 25, macros: { calories: 610, proteines: 38, glucides: 69, lipides: 22 }, portion: "1 grand bowl", allergenes: ["Soja", "Sésame"], ingredients: ["80 g de nouilles 100 % sarrasin", "180 g de tofu", "100 g d’edamame", "Pak-choï", "Champignons", "Tamari sans gluten", "Gingembre, citron vert et sésame"], etapes: ["Cuire les nouilles et les rincer.", "Dorer tofu, champignons et pak-choï.", "Assembler avec edamame et sauce tamari-gingembre-citron vert."] },
  { slug: "polenta-haricots-cottage-kale", nom: "Polenta, haricots blancs et cottage", description: "Un bowl crémeux aux haricots blancs, kale et champignons.", photoLocale: "/repas/polenta-haricots-cottage-kale-v1.png", typeRepas: "DINER", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 25, macros: { calories: 580, proteines: 36, glucides: 75, lipides: 16 }, portion: "1 grand bowl", allergenes: ["Lait"], ingredients: ["70 g de polenta", "160 g de haricots blancs", "180 g de cottage cheese", "Kale", "Champignons", "Romarin"], etapes: ["Cuire la polenta jusqu’à consistance crémeuse.", "Sauter champignons et kale avec le romarin.", "Ajouter haricots, légumes et cottage sur la polenta."] },
  { slug: "verrine-chia-yaourt-kiwi-banane", nom: "Verrine chia, yaourt, kiwi et banane", description: "Une collation fraîche apportant protéines, glucides et minéraux.", photoLocale: "/repas/verrine-chia-yaourt-kiwi-banane-v1.png", typeRepas: "COLLATION", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 10, macros: { calories: 420, proteines: 27, glucides: 49, lipides: 15 }, portion: "1 grande verrine", allergenes: ["Lait", "Fruits à coque"], ingredients: ["25 g de chia", "200 g de yaourt grec", "1 kiwi", "1 petite banane", "15 g de graines de courge", "15 g de pistaches"], etapes: ["Mélanger chia et la moitié du yaourt, puis réserver 4 heures.", "Alterner chia, kiwi, banane et yaourt dans une verrine.", "Terminer avec graines et pistaches."] },
  { slug: "pomme-terre-farcie-oeufs-cottage", nom: "Pomme de terre farcie aux œufs et cottage", description: "Une pomme de terre complète garnie d’œufs, cottage, épinards et haricots.", photoLocale: "/repas/pomme-terre-farcie-oeufs-cottage-v1.png", typeRepas: "DINER", objectifs: ["EQUILIBRE", "PRISE_DE_MASSE"], regimes: ["VEGETARIEN", "SANS_GLUTEN"], tempsMinutes: 50, macros: { calories: 590, proteines: 39, glucides: 65, lipides: 20 }, portion: "1 grande pomme de terre", allergenes: ["Œufs", "Lait"], ingredients: ["1 grande pomme de terre", "2 œufs", "150 g de cottage cheese", "100 g de haricots noirs", "Épinards", "Ciboulette", "Roquette"], etapes: ["Cuire la pomme de terre 45 minutes à 200°C.", "Brouiller les œufs avec les épinards et réchauffer les haricots.", "Ouvrir la pomme de terre, garnir avec œufs, cottage, haricots et ciboulette."] },
];

export const RECETTES_V8: Recette[] = base.map((recette) => ({ ...recette, photoQuery: recette.nom, conservation, variantes }));
