ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "pasMoyenParJour" INTEGER;
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "frequenceCardiaqueRepos" INTEGER;
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "sommeilMoyenHeures" DOUBLE PRECISION;
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "vo2Max" DOUBLE PRECISION;
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "caloriesMoyennesParJour" INTEGER;
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "resumeMontre" TEXT;
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "derniereAnalyseMontre" TIMESTAMP(3);
