import type { ProgrammePret } from "./catalogue";

// Packs ciblés de la rentrée 2026. Ils restent signalés « À valider » dans
// l'interface jusqu'au contrôle éditorial final d'Anthony.
export const PROGRAMMES_RENTREE: ProgrammePret[] = [
  {
    slug: "stretch-reset-6-semaines",
    nom: "Stretch Reset — Souplesse & mobilité",
    categorie: "STRETCH",
    niveau: "Tous niveaux",
    duree: "6 semaines",
    frequence: "3 séances / semaine, 25-35 min",
    badge: "Nouveau · À valider",
    accroche: "Six semaines pour bouger plus librement, sans forcer ni rebondir.",
    description:
      "Un cycle progressif mêlant mobilité active, yoga accessible et étirements statiques. Chaque séance couvre une priorité — hanches, chaîne postérieure ou épaules — avec des amplitudes adaptées et une respiration lente.",
    objectifs: [
      "Améliorer progressivement la mobilité des hanches, chevilles et épaules",
      "Réduire la sensation de raideur liée à la position assise",
      "Mieux tolérer les amplitudes utiles à l'entraînement",
      "Installer une routine de récupération autonome",
    ],
    photoQuery: "athlete mobility stretching premium studio",
    photoFemme: "/exercices/yoga-14-chameau-femme.jpg",
    photoHomme: "/exercices/yoga-10-guerrier-iii-homme.jpg",
    visuels: [
      { nom: "Guerrier I", photoFemme: "/exercices/yoga-09-guerrier-i-femme.jpg" },
      { nom: "Demi-lune", photoHomme: "/exercices/yoga-12-demi-lune-homme.jpg" },
      { nom: "Posture du chameau", photoFemme: "/exercices/yoga-14-chameau-femme.jpg" },
      { nom: "Posture de l'aigle", photoHomme: "/exercices/yoga-13-aigle-homme.jpg" },
      { nom: "Flexion avant jambes écartées", photoFemme: "/exercices/yoga-16-flexion-avant-jambes-ecartees-femme.jpg" },
      { nom: "Posture du poisson", photoHomme: "/exercices/yoga-15-poisson-homme.jpg" },
    ],
    progression: [
      { periode: "Semaines 1-2", titre: "Contrôle", contenu: "Reste dans une tension modérée, utilise un support et tiens 20 à 30 secondes sans rebondir." },
      { periode: "Semaines 3-4", titre: "Amplitude active", contenu: "Ajoute des transitions lentes et des maintiens actifs de 5 à 10 secondes avant chaque étirement." },
      { periode: "Semaines 5-6", titre: "Intégration", contenu: "Enchaîne les positions avec fluidité et compare seulement les amplitudes confortables à celles de la semaine 1." },
    ],
    jours: [
      { jour: "Séance A", focus: "Hanches & psoas", contenu: "Respiration 2 min, 90/90 2 x 6 par côté, fente basse 2 x 30 s, pigeon adapté 2 x 30 s et posture de l'enfant 60 s." },
      { jour: "Séance B", focus: "Chaîne postérieure", contenu: "Cat-cow 8 cycles, chien tête en bas dynamique 2 x 30 s, flexion avant jambes écartées 2 x 30 s, ischio avec sangle 2 x 30 s par côté." },
      { jour: "Séance C", focus: "Épaules & colonne", contenu: "Open book 2 x 8 par côté, aigle 2 x 20 s, passage de bâton 2 x 10, poisson soutenu 2 x 30 s et respiration lente 3 min." },
    ],
    nutrition: [
      { titre: "Hydratation", contenu: "Bois régulièrement sur la journée ; ajoute 300 à 500 ml autour de la séance selon la chaleur et ta transpiration." },
      { titre: "Assiette récupération", contenu: "Après une séance associée à un entraînement, combine une source de protéines, des légumes colorés et un féculent adapté à ton activité." },
      { titre: "Recettes liées", contenu: "Privilégie les variantes RESET/TRX de la bibliothèque Diet les jours légers et HYBRID après une séance plus longue." },
    ],
    recuperation: [
      { titre: "Intensité", contenu: "Vise une tension de 3 à 4/10, jamais une douleur vive, un engourdissement ou une sensation électrique." },
      { titre: "Respiration", contenu: "Expire lentement pendant la mise en tension et sors progressivement de chaque position." },
      { titre: "Sommeil", contenu: "Place la séance douce en soirée si elle t'aide à ralentir, mais évite de chercher des amplitudes maximales juste avant le coucher." },
    ],
    note: "En cas de douleur persistante, de blessure récente ou d'hypermobilité connue, demande l'avis d'un professionnel de santé avant de progresser.",
  },
  {
    slug: "abdos-core-6-semaines",
    nom: "Abdos & Core — Centre fort",
    categorie: "ABDOS",
    niveau: "Débutant à intermédiaire",
    duree: "6 semaines",
    frequence: "3 séances / semaine, 20-30 min",
    badge: "Nouveau · À valider",
    accroche: "Un centre plus fort pour mieux transmettre la force, sans massacrer la nuque.",
    description:
      "Un programme abdos complet qui alterne anti-extension, anti-rotation, flexion contrôlée et stabilité latérale. La progression porte d'abord sur la respiration et la qualité du bassin, puis sur le temps sous tension.",
    objectifs: [
      "Renforcer les abdominaux profonds et les obliques",
      "Améliorer la stabilité du bassin et du tronc",
      "Progresser sans tirer sur la nuque ni creuser le bas du dos",
      "Transférer le gainage vers la course et la musculation",
    ],
    photoQuery: "core workout pilates premium studio",
    photoFemme: "/exercices/pilates-11-criss-cross-femme.jpg",
    photoHomme: "/exercices/pilates-12-scissors-homme.jpg",
    visuels: [
      { nom: "Single Leg Stretch", photoFemme: "/exercices/pilates-09-single-leg-stretch-femme.jpg" },
      { nom: "Double Leg Stretch", photoHomme: "/exercices/pilates-10-double-leg-stretch-homme.jpg" },
      { nom: "Criss-Cross", photoFemme: "/exercices/pilates-11-criss-cross-femme.jpg" },
      { nom: "Scissors", photoHomme: "/exercices/pilates-12-scissors-homme.jpg" },
      { nom: "Corkscrew", photoHomme: "/exercices/pilates-13-corkscrew-homme.jpg" },
      { nom: "Side Kick à genoux", photoFemme: "/exercices/pilates-14-side-kick-kneeling-femme.jpg" },
    ],
    medias: [
      "Gainage planche",
      "Crunch",
      "Reverse crunch",
      "Relevé de jambes au sol",
      "Russian twist",
      "Gainage latéral",
      "Sit-up",
      "Relevé de genoux suspendu",
      "Mountain climber",
    ],
    progression: [
      { periode: "Semaines 1-2", titre: "Placement", contenu: "2 séries, tempo lent, expiration sur l'effort et arrêt dès que le bas du dos se creuse." },
      { periode: "Semaines 3-4", titre: "Temps sous tension", contenu: "Passe à 3 séries ou ajoute 5 à 10 secondes sur les gainages en gardant 2 répétitions propres en réserve." },
      { periode: "Semaines 5-6", titre: "Complexité", contenu: "Ajoute une variante unilatérale ou un levier plus long sur un seul exercice par séance." },
    ],
    jours: [
      { jour: "Séance A", focus: "Anti-extension", contenu: "Dead bug 3 x 8 par côté, gainage planche 3 x 20-40 s, Double Leg Stretch 3 x 8-12 et reverse crunch 3 x 10-15." },
      { jour: "Séance B", focus: "Obliques & anti-rotation", contenu: "Gainage latéral 3 x 20-35 s par côté, Criss-Cross 3 x 8 par côté, Pallof press élastique 3 x 10 par côté et bird-dog 3 x 8." },
      { jour: "Séance C", focus: "Contrôle dynamique", contenu: "Corkscrew 3 x 6 par sens, Scissors 3 x 8 par jambe, mountain climber lent 3 x 20 et farmer carry unilatéral 3 x 30 s par côté." },
    ],
    nutrition: [
      { titre: "Composition corporelle", contenu: "Les exercices abdos renforcent le tronc mais ne font pas perdre localement la graisse ; utilise LEAN seulement si ton objectif global justifie un léger déficit." },
      { titre: "Protéines réparties", contenu: "Répartis une source de protéines sur tes repas principaux et adapte les portions à ton profil plutôt que de supprimer les glucides." },
      { titre: "Recettes liées", contenu: "Les recettes LEAN conviennent à un objectif de perte de poids ; RESET/TRX soutient la remise en forme et HYBRID les jours plus actifs." },
    ],
    recuperation: [
      { titre: "Repos local", contenu: "Laisse au moins 24 heures entre deux séances ciblées et arrête toute série si la technique se dégrade." },
      { titre: "Bas du dos", contenu: "Ajoute cat-cow, posture de l'enfant et respiration diaphragmatique pendant 5 minutes après la séance." },
      { titre: "Progression", contenu: "Augmente d'abord la qualité et le temps sous tension ; le lest ne vient qu'après six semaines propres." },
    ],
    note: "Un ventre visible dépend surtout de la composition corporelle globale ; aucune promesse de résultat localisé n'est faite.",
  },
  {
    slug: "special-fessiers",
    nom: "Spécial Fessiers — Force & galbe",
    categorie: "FESSIERS",
    niveau: "Tous niveaux",
    duree: "6 semaines",
    frequence: "3 séances / semaine, 40-55 min",
    badge: "Nouveau · À valider",
    accroche: "Six semaines de progression mesurable sur l'extension, l'abduction et l'unilatéral.",
    description:
      "Un cycle fessiers complet, accessible aux femmes comme aux hommes, qui répartit le travail entre force, volume et stabilité. Les charges progressent uniquement lorsque l'amplitude et le bassin restent contrôlés.",
    objectifs: [
      "Renforcer grand, moyen et petit fessier",
      "Développer force et volume avec une progression structurée",
      "Améliorer la stabilité du bassin sur une jambe",
      "Limiter la compensation par le bas du dos",
    ],
    photoQuery: "glute strength workout premium gym",
    photoFemme: "/exercices/fentes-bulgares.jpg",
    photoHomme: "/exercices/pont-fessier-homme-metis-v2.jpg",
    visuels: [
      { nom: "Fentes bulgares", photoFemme: "/exercices/fentes-bulgares.jpg" },
      { nom: "Pont fessier", photoHomme: "/exercices/pont-fessier-homme-metis-v2.jpg" },
      { nom: "Hip thrust barre", photoHomme: "/exercices/hip-thrust-barre.jpg" },
      { nom: "Kickback élastique", photoFemme: "/exercices/kickback-fessier-elastique.jpg" },
      { nom: "Abduction de hanche", photoFemme: "/exercices/abduction-hanche-elastique.jpg" },
    ],
    medias: ["Goblet squat", "Fentes arrière haltères", "Step up", "Pont fessier", "Gainage latéral"],
    progression: [
      { periode: "Semaines 1-2", titre: "Activation & technique", contenu: "3 séries, 3 répétitions en réserve et pause d'une seconde en contraction maximale." },
      { periode: "Semaines 3-4", titre: "Surcharge progressive", contenu: "Ajoute 1 à 2 répétitions puis 2,5 à 5 % de charge lorsque toutes les séries restent propres." },
      { periode: "Semaines 5-6", titre: "Intensification", contenu: "4 séries sur le mouvement principal et une série longue contrôlée sur l'isolation, sans aller à l'échec technique." },
    ],
    jours: [
      { jour: "Séance A", focus: "Extension lourde", contenu: "Hip thrust 4 x 8-10, goblet squat 3 x 10-12, fente arrière 3 x 10 par jambe et abduction élastique 3 x 18." },
      { jour: "Séance B", focus: "Unilatéral & stabilité", contenu: "Fente bulgare 4 x 8-10 par jambe, step-up 3 x 10, RDL unijambiste 3 x 10 et gainage latéral 3 x 25 s." },
      { jour: "Séance C", focus: "Volume & contrôle", contenu: "Soulevé de terre roumain 4 x 8-10, pont fessier 3 x 15, kickback 3 x 15 par côté et frog pumps 2 x 25." },
    ],
    nutrition: [
      { titre: "Construction musculaire", contenu: "Choisis la variante MASS si tu vises la prise de volume, avec un léger surplus adapté ; HYBRID convient à un objectif force et performance." },
      { titre: "Protéines", contenu: "Répartis une source de protéines sur trois à quatre prises et utilise les portions individualisées de ton diagnostic." },
      { titre: "Autour de la séance", contenu: "Place une partie des glucides avant ou après l'entraînement selon ta tolérance, sans supprimer légumes, fibres et bonnes graisses." },
    ],
    recuperation: [
      { titre: "Espacement", contenu: "Garde au moins 48 heures entre deux séances fessiers exigeantes." },
      { titre: "Auto-massage", contenu: "30 à 60 secondes sur fessiers et quadriceps, pression modérée, jamais directement sur une articulation ou une douleur aiguë." },
      { titre: "Sommeil", contenu: "Vise une routine régulière et réduis la charge si les courbatures modifient ta marche ou ta technique." },
    ],
    note: "La progression dépend du niveau initial, de l'assiduité, de la récupération et de l'alimentation ; aucun résultat esthétique précis n'est garanti.",
  },
];
